<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 16               */
/* CACHE FILE: Generated: Tue, 29 Dec 2015 18:49:00 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_ipsthemes_16 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();


}

/* -- ipsEditorThemes --*/
function ipsEditorThemes() {
$IPBHTML = "";
$IPBHTML .= "" . (($this->settings['ipsEditorThemes_enabled'] == '1') ? ("<!-- Editor Themes by IPS Themes -->

<link rel=\"stylesheet\" type=\"text/css\" href=\"{$this->settings['css_base_url']}style_extra/ipsEditorThemes/css/font-awesome.min.css\" />
<link rel=\"stylesheet\" type=\"text/css\" href=\"{$this->settings['css_base_url']}style_extra/ipsEditorThemes/css/theme.min.css\" />

<style type=\"text/css\">
.cke_skin_ips .cke_top, .cke_skin_ips .cke_wrapper, .ipsSmileyTray { background: #{$this->settings['ipsEditorThemes_bg']} !important; }
.cke_skin_ips .cke_button a.cke_on { background-color: #{$this->settings['ipsEditorThemes_bgSelected']} !important; border: 0 !important; }
.cke_skin_ips .cke_button a:hover.cke_on, .cke_skin_ips .cke_button a:focus.cke_on, .cke_skin_ips .cke_button a:active.cke_on { background-color: #{$this->settings['ipsEditorThemes_bgSelected']} !important; }
.cke_skin_ips .cke_icon { color: #{$this->settings['ipsEditorThemes_icon']} !important; } /* Icon Colour */
.cke_skin_ips .cke_on .cke_icon { color: #{$this->settings['ipsEditorThemes_iconSelected']} !important; } /* Selected Icon Colour */
" . (($this->settings['ipsEditorThemes_style'] == 'style1') ? ("
.cke_skin_ips .cke_ltr .cke_rcombo { background: rgba(0,0,0,.05) !important; }
.cke_skin_ips .cke_rcombo a .cke_text { color: rgba(0,0,0,.5) !important; }
.cke_skin_ips .cke_ltr .cke_rcombo .cke_openbutton:after, .cke_skin_ips .cke_rcombo .cke_openbutton:after, .cke_skin_ips .cke_button .cke_buttonarrow:after { color: #444; }
") : ("")) . "") : ("")) . "
" . (($this->settings['ipsEditorThemes_style'] == 'style2') ? ("
.cke_skin_ips .cke_ltr .cke_rcombo { background: rgba(255,255,255,.1) !important; }
.cke_skin_ips .cke_rcombo a .cke_text { color: rgba(255,255,255,.5) !important; }
.cke_skin_ips .cke_ltr .cke_rcombo .cke_openbutton:after, .cke_skin_ips .cke_rcombo .cke_openbutton:after, .cke_skin_ips .cke_button .cke_buttonarrow:after { color: #DDD; }
") : ("")) . "
</style>

</if>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>