<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 14               */
/* CACHE FILE: Generated: Tue, 29 Dec 2015 18:27:01 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_boards_14 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['boardIndexTemplate'] = array('showSubForumsLit','subforums','showSubForumsLit','subforums','canSeeLastInfoRedirect','hasUnreadClass','hasUnread','hasQueuedAndCanSeeIcon','showSubForums','hideTopicInTitle','hideDateUrl','lastPosterID','hideLastInfo','canSeeLastInfo','forumRedirect','forums','canSeeLastInfoHeader','cat_has_forums','categories','side_blocks','markerhasunread','markernotredirect','markerforums','markerhasforums','markercategories','boardIndexTop','sideBarEnabledL','sidebarclosed','cats_forums','sidebarclosed2','sideBarEnabled2','markercatforums','showTotals','reputationType','reputationEnabled','statsLinks','showActive','onlineListEnabled','activeNames');
$this->_funcHooks['hookFacebookActivity'] = array('fbAppIdPresent');
$this->_funcHooks['hookLikesThisLeaders'] = array('mvp_hook','repleaders');
$this->_funcHooks['hookRecentTopics'] = array('topics_hook','recenttopics');
$this->_funcHooks['hookTagCloud'] = array('eachTag');
$this->_funcHooks['recentPosts'] = array('forum','starterInfo','firstPost','views','lastPostInfo','lastPost','posts','hasRecentPosts');
$this->_funcHooks['statusReplies'] = array('canDelete','isFirstCycle','innerLoop');
$this->_funcHooks['statusUpdates'] = array('canDelete','isLocked','canLock','noLocked','cImg','hasRepliesMain','hasRepliesButCannotReply','canReplyMain','hasMore','hasReplies','canReply','outerLoop');


}

/* -- boardIndexTemplate --*/
function boardIndexTemplate($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['boardIndexTemplate'] ) )
{
$count_fe91c8c5f9f0783f2a0260c5a17d751f = is_array($this->functionData['boardIndexTemplate']) ? count($this->functionData['boardIndexTemplate']) : 0;
$this->functionData['boardIndexTemplate'][$count_fe91c8c5f9f0783f2a0260c5a17d751f]['lastvisit'] = $lastvisit;
$this->functionData['boardIndexTemplate'][$count_fe91c8c5f9f0783f2a0260c5a17d751f]['stats'] = $stats;
$this->functionData['boardIndexTemplate'][$count_fe91c8c5f9f0783f2a0260c5a17d751f]['cat_data'] = $cat_data;
$this->functionData['boardIndexTemplate'][$count_fe91c8c5f9f0783f2a0260c5a17d751f]['show_side_blocks'] = $show_side_blocks;
$this->functionData['boardIndexTemplate'][$count_fe91c8c5f9f0783f2a0260c5a17d751f]['side_blocks'] = $side_blocks;
}

$this->templateVars['sidebar_enabled'] = "$show_side_blocks";
$this->__default__templateVars['sidebar_enabled'] = "$show_side_blocks";
$IPBHTML .= "" . (($this->settings['hoverDescriptions']='no') ? ("") : ("")) . "
" . (($this->settings['removeStatsColumn']='no') ? ("") : ("")) . "
" . (($this->settings['customForumIcons']='no') ? ("") : ("")) . "
<!-- -->
" . $this->registry->getClass('output')->addJSModule("board", "0" ) . "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'servers' ) ? $this->registry->getClass('output')->getTemplate('global')->servers() : '' ) . "
" . ((true) ? ("") : ("")) . "
<div id='board_index' class='ipsLayout " . (($this->templateVars['sidebar_enabled']) ? ("ipsLayout_withright") : ("")) . " ipsLayout_largeright clearfix " . ((IPSCookie::get('hide_sidebar') == '1') ? ("no_sidebar") : ("")) . "'>	
	<div id='categories' class='ipsLayout_content clearfix'>
	<!-- CATS AND FORUMS -->
		" . ((is_array( $cat_data ) AND count( $cat_data )) ? ("
			".$this->__f__a6538b4e5ac5011f0d170f1e7d29c236($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."		") : ("")) . "
	</div>
	" . (($this->templateVars['sidebar_enabled']) ? ("<div id='index_stats' class='ipsLayout_right clearfix' " . ((IPSCookie::get('hide_sidebar') == '1') ? ("style='display: none'") : ("")) . ">
			".$this->__f__e643cac9ddb61564f9f22303834f6da3($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."		</div>
		<a href='#' id='toggle_sidebar' title='{$this->lang->words['toggle_sidebar']}' data-closed=\"{$this->lang->words['_laquo']}\" data-open=\"&times;\">&nbsp;</a>") : ("")) . "
</div>
<script type='text/javascript'>
//<![CDATA[
	var markerURL  = ipb.vars['base_url'] + \"app=forums&module=ajax&section=markasread&i=1\"; // Ajax URL so don't use &amp;
	var unreadIcon = \"<img src='{$this->settings['img_url']}/f_icon_read.png' />\";
	
	" . ((is_array( $cat_data ) AND count( $cat_data )) ? ("
		".$this->__f__4f21e4bd3b1ea247c78790ccb3ea29e0($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."	") : ("")) . "
//]]>
</script>

" . (($this->settings['show_totals']) ? ("
	<div id='board_stats'>		
		<ul class='ipsType_small ipsList_inline'><ul class='ipsList_inline left'>

			<li class='clear'>
<span class='value'>Total Posts&nbsp;•&nbsp;
				{$stats['info']['total_posts']}</span>
			</li>
                    
			<li class='clear'>
<span class='value'>{$this->lang->words['total_members']}&nbsp;•&nbsp;
				{$stats['info']['mem_count']}</span>
			</li>


			<li class='clear' data-tooltip=\"{$stats['info']['most_time']}\">
                               <span class='value'> {$this->lang->words['online_at_once']}&nbsp;•&nbsp;
				{$stats['info']['most_online']}</span>
			</li></ul>
<ul class='ipsList_inline right'><li class='clear'>
				<span class='value'>
{$this->lang->words['newest_member']}
  " . IPSMember::makeProfileLink( $stats['info']['last_mem_name'], $stats['info']['last_mem_id'], $stats['info']['last_mem_seo']) . "
				</span>
			</li><ul class='ipsList_inline right'>
		</ul>
	</div> 
") : ("")) . "</br></br>
<div id='board_statistics' class='statistics clearfix'>
	<h4 class='statistics_head clearfix'><ul id='stat_links' class='ipsList_inline right ipsType_small'>
		" . ((1==1) ? ("<!-- Hook point -->
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats&amp;do=leaders", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['sm_forum_leaders_title']}\">{$this->lang->words['sm_forum_leaders']}</a></li>
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=extras&amp;section=stats", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['sm_all_posters_title']}\">{$this->lang->words['sm_today_posters']}</a></li>
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=list&amp;max_results=20&amp;sort_key=posts&amp;sort_order=desc&amp;filter=ALL", "public",'' ), "false", "" ) . "\" title=\"{$this->lang->words['sm_overall_posters_title']}\">{$this->lang->words['sm_overall_posters']}</a></li>
            " . (($this->settings['reputation_enabled']) ? ("<li>
                    <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=reputation&amp;section=most", "public",'' ), "most_liked", "most_liked" ) . "\">
                        " . (($this->settings['reputation_point_types'] == 'like') ? ("
                            {$this->lang->words['most_rep_likes']}
                        ") : ("
                            {$this->lang->words['most_rep_rep']}
                        ")) . "
                    </a>
                </li>") : ("")) . "") : ("")) . "
	</ul>
" . (($this->settings['show_active'] && $this->memberData['gbw_view_online_lists']) ? ("" . sprintf( $this->lang->words['online_right_now'], $stats['TOTAL'] ) . " {$this->lang->words['active_users']}") : ("")) . "</h4>
	" . (($this->settings['show_active']) ? ("<p class='statistics_brief desc'>
		" . sprintf( $this->lang->words['active_users_detail'], $stats['MEMBERS'], $stats['GUESTS'], $stats['ANON'] ) . "
		" . (($this->settings['allow_online_list']) ? ("&nbsp;&nbsp;<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=online&amp;sort_order=desc", "public",'' ), "", "" ) . "'>({$this->lang->words['online_link']})</a> ") : ("")) . "
	</p>") : ("")) . "
	
	" . ((count($stats['NAMES']) && $this->settings['show_active']) ? ("
		<br />
		<p>
			<span class='name'>" . implode( ",</span> <span class='name'>", $stats['NAMES'] ) . "</span>					
		</p>
	") : ("")) . "<!--hook.if.skin_boards.boardIndexTemplate.activeNames.post.endif-->
</div>";
return $IPBHTML;
}


function __f__4dc97f63ddf9939297b91979a4243304($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='',$forum_id='',$forum_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $forum_data['subforums'] as $__id => $__data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "</ol>
 <ol class='ipsList_inline ipsType_small subforums3' id='subforums_{$forum_data['id']}'>
" . (($__data[3]) ? ("
<li class='unread'>
  ") : ("
<li>
")) . "
  
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__8e1ddf62879f994a1363a378c764167f($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='',$forum_id='',$forum_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $forum_data['subforums'] as $__id => $__data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
  </ol>
<ol class='ipsList_inline ipsType_small subforums1' id='subforums_{$forum_data['id']}'>
  " . (($__data[3]) ? ("
  <li class='unread'>
  ") : ("
  <li>
  ")) . "
<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$__data[0]}", "public",'' ), "{$__data[2]}", "showforum" ) . "\" title='{$this->lang->words['go_to_forum']}'>{$__data[1]}</a>
</li>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__aeccb24fe80a4dec803f1c4092c92290($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
$imageURL = "{$this->settings['img_url']}";
															$imageFolder = basename($imageURL);
															$forumId = $forum_data['id'];

$imageURL = "{$this->settings['img_url']}";
																$imageFolder = basename($imageURL);
																$forumId = $forum_data['id'];

$imageURL = "{$this->settings['img_url']}";
																$imageFolder = basename($imageURL);
																$forumId = $forum_data['id'];

$total_topics_posts = $days = ereg_replace("[^0-9]", "", $forum_data['topics']) + $days = ereg_replace("[^0-9]", "", $forum_data['posts']);

/*$total_topics_posts = number_format($total_topics_posts, null, '.', '.');*/

		$__iteratorCount++;
		$_ips___x_retval .= "
										" . (($forum_data['redirect_on']) ? ("<tr class='redirect_forum' id='f_{$forum_data['id']}'>
												<td class='col_c_icon'>
													" . (($this->settings['customForumIcons']=='yes') ? ("														" . ((is_file( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_images/' . $imageFolder . '/forum_images/' . $forumId . '.png' )) ? ("
															<img src=\"{style_images_url}/forum_images/{$forum_data['id']}.png\" alt=\"\" />
														") : ("
															<img src=\"{style_images_url}/forum_images/default.png\" alt=\"\" />
														")) . "") : ("" . (($forum_data['id'] != 245) ? ("										<img src='{$this->settings['img_url']}/f_redirect.png' />
") : ("
<center><i class=\"fa fa-steam-square\" style=\"font-size: 38px; color: #fff;\"></i></center>
")) . "")) . "
												</td>
												<td " . (($this->settings['removeStatsColumn']=='no') ? ("" . (($this->memberData['gbw_view_last_info']) ? ("colspan='2'") : ("")) . "") : ("")) . " class='col_c_forum'>
													<h4 class='forum_name'><strong class='highlight_unread'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='" . IPSText::striptags( IPSText::htmlspecialchars( $forum_data['name'] ) ) . "'>{$forum_data['name']}</a></strong></h4>
													" . (($forum_data['description']) ? ("" . (($this->settings['hoverDescriptions']=='yes') ? ("<span class='forum_desc_pos'><span class='forum_desc_con'><span class='forum_description'>{$forum_data['description']}</span></span></span>") : ("<p class='desc forum_desc'>{$forum_data['description']}</p>")) . "") : ("")) . "
												</td>
												<td class='desc'>
													<ul class='last_post ipsType_small'>
                                                        							<li class='desc lighter'><em>" . $this->registry->getClass('class_localization')->formatNumber( $forum_data['redirect_hits'] ) . " {$this->lang->words['rd_hits']}</em></li>
                                                    							</ul>
												</td>
											</tr>") : ("<tr class='" . (($forum_data['_has_unread']) ? ("unread") : ("notnew")) . "'>
												<td class='col_c_icon'>
													" . (($forum_data['_has_unread']) ? ("<a id='forum_img_{$forum_data['id']}' href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=markasread&amp;marktype=forum&amp;forumid={$forum_data['id']}&amp;returntoforumid={$this->request['f']}&amp;i=1", "public",'' ), "", "" ) . "\" data-tooltip=\"{$this->lang->words['bi_markread']}\" class='forum_marker'>													
														" . (($this->settings['customForumIcons']=='yes') ? ("															" . ((is_file( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_images/' . $imageFolder . '/forum_images/' . $forumId . '.png' )) ? ("
																<img src=\"{style_images_url}/forum_images/{$forum_data['id']}.png\" alt=\"\" />
															") : ("
																<img src=\"{style_images_url}/forum_images/{$forum_data['id']}.png\" alt=\"\" />
															<else />
																<img src=\"{style_images_url}/forum_images/default.png\" alt=\"\" />
															")) . "") : ("
															<img src='{$this->settings['img_url']}/f_icon.png' />
														")) . "
														</a>") : ("" . (($this->settings['customForumIcons']=='yes') ? ("															" . ((is_file( DOC_IPS_ROOT_PATH . '/' . PUBLIC_DIRECTORY . '/style_images/' . $imageFolder . '/forum_images/' . $forumId . '.png' )) ? ("<img src=\"{style_images_url}/forum_images/{$forum_data['id']}.png\" alt=\"\" " . (($this->memberData['member_id']) ? ("class='fadedForumIcon'") : ("")) . " />") : ("<img src=\"{style_images_url}/forum_images/default.png\" alt=\"\" " . (($this->memberData['member_id']) ? ("class='fadedForumIcon'") : ("")) . " />")) . "") : ("
															<img src='{$this->settings['img_url']}/f_icon_read.png' />
														")) . "")) . "
												</td>
												<td class='col_c_forum' " . ((in_array($forum_data['id'], array(9999999999 , 9))) ? ("colspan='3'") : ("")) . ">

													
													<h4 class='forum_name'>
														" . ((!empty($forum_data['_has_queued_and_can_see_icon'])) ? ("
															<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}&amp;modfilter=unapproved", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "' title='{$this->lang->words['view_unapproved']}' class='ipsBadge ipsBadge_orange' data-tooltip=\"" . sprintf( $this->lang->words['f_queued'], $forum_data['queued_topics'], $forum_data['queued_posts']) . "\" style='vertical-align: top'>{$this->lang->words['f_queued_badge']}</a>
														") : ("")) . "
														<strong class='highlight_unread'><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='" . IPSText::striptags( IPSText::htmlspecialchars( $forum_data['name'] ) ) . "'>{$forum_data['name']}</a></strong> " . (($this->settings['customForumIcons']=='yes') ? ("" . (($forum_data['_has_unread']) ? ("<span class='ipsBadge ipsBadge_orange' style='vertical-align: top; margin-left: 5px;'>NEW</span>") : ("")) . "") : ("")) . "
													</h4>

							" . (($forum_data['description']) ? ("" . (($this->settings['hoverDescriptions']=='yes') ? ("<span class='forum_desc_pos'><span class='forum_desc_con'><span class='forum_description'>{$forum_data['description']}</span></span></span>") : ("<p class='desc forum_desc'>{$forum_data['description']}</p>")) . "") : ("")) . "
						
" . (($forum_data['show_subforums'] AND count( $forum_data['subforums'] ) AND $forum_data['show_subforums'] AND !in_array($forum_data['id'], array(28600000, 12))) ? ("


														<ol class='ipsList_inline ipsType_small subforums2' id='subforums_{$forum_data['id']}'>
  ".$this->__f__4dc97f63ddf9939297b91979a4243304($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data,$forum_id,$forum_data)." </ol>
<ol class='ipsList_inline ipsType_small subforums' id='subforums_{$forum_data['id']}'>
 ".$this->__f__8e1ddf62879f994a1363a378c764167f($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data,$forum_id,$forum_data)."  </ol>
													") : ("")) . "
																					
												</td>

" . ((!in_array($forum_data['id'], array(999999999 , 9))) ? ("<!--
												 <td class='col_c_stats ipsType_small'>
													<ul>
														<li>{$forum_data['topics']} {$this->lang->words['topics']}</li>
														<li>{$forum_data['posts']} {$this->lang->words['replies']}</li>
													</ul>
												</td>
--><td style='width: 10%;'><span class='nstatsNumber'>
" . $this->registry->getClass('class_localization')->formatNumber( intval( $total_topics_posts ) ) . " 

</span><span class='nstatsText'>mesaje</span></td>



                                                " . (($this->memberData['gbw_view_last_info']) ? ("<td class='col_c_post'>
													" . (($forum_data['hide_last_info']) ? ("
														<ul class='last_post'>
															<li class='desc lighter'><em>{$this->lang->words['f_protected']}</em></li>
														</ul>
													") : ("" . (($forum_data['_hide_last_date']) ? ("
                                                        " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array('member_id' => $forum_data['last_poster_id'], 'members_seo_name' => $forum_data['seo_last_name'], 'pp_small_photo' => $forum_data['pp_small_photo'], 'alt' => '' )) : '' ) . "
                                                        ") : ("
														" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array('member_id' => $forum_data['last_poster_id'], 'members_seo_name' => $forum_data['seo_last_name'], 'pp_small_photo' => $forum_data['pp_small_photo'], 'alt' => sprintf( $this->lang->words['bindex_userphoto_alt'], $forum_data['last_title'], $forum_data['members_display_name'] ) )) : '' ) . "
")) . "
														<ul class='last_post ipsType_small'>
															" . ((!$forum_data['last_id']) ? ("
																<li class='desc lighter'><em>{$this->lang->words['f_none']}</em></li>
															") : ("<li>
																	<span class='highlight_unread'>{$forum_data['last_topic_title']}</span>
																</li>
                                                                <li>
                                                                    <span class='desc lighter blend_links'>
                                                                    " . (($forum_data['_hide_last_date']) ? ("
                                                                        " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($forum_data['last_post'],"DATE", 0)) . "
                                                                    ") : ("
                                                                        <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$forum_data['last_id']}&amp;view=getlastpost", "public",'' ), "{$forum_data['seo_last_title']}", "showtopic" ) . "' title='{$this->lang->words['view_last_post']}'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($forum_data['last_post'],"DATE", 0)) . "</a>
                                                                    ")) . "</span>
                                                                    " . (($forum_data['last_poster_id']) ? ("
                                                                        {$this->lang->words['by']} " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($forum_data) : '' ) . "
                                                                    ") : ("")) . "
                                                                </li>")) . "
															
														</ul>")) . "
												</td>") : ("")) . "") : ("")) . "
											</tr>")) . "
									
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__a6538b4e5ac5011f0d170f1e7d29c236($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $cat_data as $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("<div id='category_{$_data['cat_data']['id']}' class='category_block block_wrap'>

						" . $this->registry->getClass('output')->getReplacement("header_start") . "<h3 class='maintitle'>


{$icon}
							<a class='toggle right' href='#' title=\"" . sprintf( $this->lang->words['toggle_cat'], IPSText::striptags( IPSText::htmlspecialchars($_data['cat_data']['name'] ) ) ) . "\">

<!--" . sprintf( $this->lang->words['toggle_cat'], $_data['cat_data']['name'] ) . "-->

</a> 


<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$_data['cat_data']['id']}", "public",'' ), "{$_data['cat_data']['name_seo']}", "showforum" ) . "\" title='" . sprintf( $this->lang->words['view_cat'], IPSText::striptags( IPSText::htmlspecialchars($_data['cat_data']['name'] ) ) ) . "'>{$_data['cat_data']['name']}</a>
						</h3>" . $this->registry->getClass('output')->getReplacement("header_end") . "
						<div class='ipsBox table_wrap removeDefault'>
							<div class='ipsBox_container'>
								<table class='ipb_table' summary=\"{$this->lang->words['forums_in_cat']} '{$_data['cat_data']['name']}'\">
									<tr class='header hide'>
										<th scope='col' class='col_c_icon'>&nbsp;</th>
										<th scope='col' class='col_c_forum'>{$this->lang->words['cat_name']}</th>
										" . (($this->settings['removeStatsColumn']=='no') ? ("<th scope='col' class='col_c_stats stats'>{$this->lang->words['stats']}</th>") : ("")) . "
										" . (($this->memberData['gbw_view_last_info']) ? ("<th scope='col' class='col_c_post'>{$this->lang->words['last_post_info']}</th>") : ("")) . "
									</tr>
									<!-- / CAT HEADER -->
									".$this->__f__aeccb24fe80a4dec803f1c4092c92290($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data)."								</table>
							</div>
						</div>" . $this->registry->getClass('output')->getReplacement("box_end") . "
						<br />
					</div>") : ("")) . "

" . (($_data['cat_data']['id'] == 1) ? ("

<div class='reclama' align='center'>
		<a href=\"http://steamcommunity.com/groups/aimerscommunity\"><img src=\"http://i.imgur.com/5m3A4Sg.png\" border=\"0\">  </a><a href=\"http://www.gametracker.com/clan/aimersroro/\"><img src=\"http://i.imgur.com/SCHSKu0.png\" border=\"1px solid #282828;\"></a>
	</div>
<br />
") : ("")) . "
			
";
	}
	$_ips___x_retval .= '<!--hook.foreach.skin_boards.boardIndexTemplate.categories.outer.post-->';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__e643cac9ddb61564f9f22303834f6da3($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '<!--hook.foreach.skin_boards.boardIndexTemplate.side_blocks.outer.pre-->';
	$__iteratorCount = 0;
	foreach( $side_blocks as $block )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				{$block}
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__0d0d948a54444a5d44722cc746e97850($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . ((!$forum_data['redirect_on']) ? ("" . (($forum_data['_has_unread']) ? ("
	ipb.global.registerMarker( \"forum_img_{$forum_data['id']}\", \"{$forum_data['img_new_post']}\", markerURL + \"&forumid={$forum_data['id']}\" );
						") : ("")) . "") : ("")) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__4f21e4bd3b1ea247c78790ccb3ea29e0($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $cat_data as $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("
				".$this->__f__0d0d948a54444a5d44722cc746e97850($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data)."			") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- customSidebarBlock --*/
function customSidebarBlock( $data='') {
$IPBHTML = "";
$IPBHTML .= "" . (($data['csb_use_box']) ? ("<div class='ipsSideBlock clearfix'>
	<h3 " . (($data['csb_no_collapse']) ? ("class='csbNoCollapse'") : ("")) . ">" . (($data['csb_image']) ? ("<img src='{$this->settings['img_url']}/{$data['csb_image']}' alt='{$this->lang->words['icon']}' />") : ("")) . " {$data['csb_title']}</h3>
	<div class='_sbcollapsable'>
		{$data['csb_content']}
	</div>
</div>") : ("
	<div class='_sbcollapsable' style='padding: 10px;'>
		{$data['csb_content']}
	</div>
")) . "";
return $IPBHTML;
}

/* -- hookBoardIndexStatusUpdates --*/
function hookBoardIndexStatusUpdates($updates=array()) {
$IPBHTML = "";
$IPBHTML .= "<script type='text/javascript' src=\"{$this->settings['public_dir']}js/ips.status.js\"> </script>
<div class='ipsSideBlock clearfix' id='statusHook'>
	<h3>{$this->lang->words['recent_status_updates']}</h3>
	<div class='_sbcollapsable'>
		<div id=\"status_wrapper\">
			<div id=\"status_wrapper_inside\">" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'statusUpdates' ) ? $this->registry->getClass('output')->getTemplate('boards')->statusUpdates($updates, 1, 1) : '' ) . "</div>
			<div class=\"status_main_content ipsType_small\" style='text-align: center; margin: 10px -10px -10px -10px;'>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=all", "public",'' ), "true", "members_status_all" ) . "' style='display: block; padding: 8px; font-weight: bold;'>{$this->lang->words['viewallupdates']}</a>
			</div>
		</div>
	</div>
</div>";
return $IPBHTML;
}

/* -- hookFacebookActivity --*/
function hookFacebookActivity() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookFacebookActivity'] ) )
{
$count_bfb1e2212299f0743371045053730d4c = is_array($this->functionData['hookFacebookActivity']) ? count($this->functionData['hookFacebookActivity']) : 0;
}
$IPBHTML .= "" . ((IPSLib::fbc_enabled()) ? ("
<div class='general_box clearfix'>
	<h3>{$this->lang->words['hook_facebookactivity']}</h3>
	<div  class='block_list clearfix _sbcollapsable'>
		<div><fb:activity site=\"\" width=\"270\" height=\"300\" header=\"false\" border_color=\"#FFF\" colorscheme=\"light\" /></div>
	</div>
</div><div id=\"fb-root\"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: '{$this->settings['fbc_appid']}', status: true, cookie: true,
             xfbml: true});
  };
  (function() {
    var e = document.createElement('script'); e.async = true;
    e.src = document.location.protocol +
      '//connect.facebook.net/{$this->settings['fb_locale']}/all.js';
    document.getElementById('fb-root').appendChild(e);
  }());
</script>
") : ("")) . "";
return $IPBHTML;
}

/* -- hookGroupNameIndicator --*/
function hookGroupNameIndicator($groups=array()) {
$IPBHTML = "";
$IPBHTML .= "<h4 class=\"statistics_head\">
	Legendă: " . implode( " ≈ ", $groups ) . "
</h4>";
return $IPBHTML;
}

/* -- hookLikesThisLeaders --*/
function hookLikesThisLeaders($ltl) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookLikesThisLeaders'] ) )
{
$count_038bfe253abbc94c09b6293d9e053e1b = is_array($this->functionData['hookLikesThisLeaders']) ? count($this->functionData['hookLikesThisLeaders']) : 0;
$this->functionData['hookLikesThisLeaders'][$count_038bfe253abbc94c09b6293d9e053e1b]['ltl'] = $ltl;
}
$IPBHTML .= "" . ((is_array( $ltl ) && count( $ltl )) ? ("
<div class='ipsSideBlock clearfix'>
	<h3>{$this->lang->words['lt_leaders']}</h3>
	<div class='_sbcollapsable'>
		<ul class='ipsList_withminiphoto'>
		".$this->__f__2edec2b61d0c78e8e51b813919206d96($ltl)."		</ul>
	</div>
</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__2edec2b61d0c78e8e51b813919206d96($ltl)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $ltl as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<li class='clearfix'>
					
				</p>

			" . (($r['member_id']) ? ("
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", "public",'' ), "{$r['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' class='ipsUserPhotoLink'>
			") : ("")) . "
			<img src='{$r['pp_mini_photo']}' alt=\"" . sprintf($this->lang->words['users_photo'],$r['members_display_name']) . "\" class='ipsUserPhoto ipsUserPhoto_mini left'/>
			" . (($r['member_id']) ? ("
				</a>
			") : ("")) . "
<div class='list_content'>
				<p class='desc ipsType_smaller'>
					" . (($r['members_display_name']) ? ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($r) : '' ) . "") : ("{$this->settings['guest_name_pre']}{$r['starter_name']}{$this->settings['guest_name_suf']}")) . "

</p>
</div>
<div class='list_content'><p class='desc ipsType_smaller'>{$this->lang->words['lt_rep']}:  " . $this->registry->getClass('class_localization')->formatNumber( $r['pp_reputation_points'] ) . "
                                 </p></div>
		</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hookMembersOnlineToday --*/
function hookMembersOnlineToday($mems=array(), $count=0, $state='expanded') {
$IPBHTML = "";
$IPBHTML .= "<script type='text/javascript'>
	function toggleMOT(elem)
	{
		Effect.toggle('mot_body', 'blind',{duration:.5, afterFinish: function(motb){
			var hookLangCollapse = '{$this->lang->words['hookLangCollapse']}', hookLangExpand = '{$this->lang->words['hookLangExpand']}',  vis = motb.element.visible();
			if(vis) {
				elem.update(hookLangCollapse);
				ipb.Cookie.set( 'membersOnlineToday', 0, 1 );
			}else{
				elem.update(hookLangExpand);
				ipb.Cookie.set( 'membersOnlineToday', 1, 1 );
			}
		}.bind(elem)});
	}
</script>
<br /><br />
<h4 class='statistics_head'>
	{$this->lang->words['hookLangOnlineToday']} {$count}
	" . (($this->settings['expcol_mot']) ? ("[<a href='#' onClick=\"toggleMOT(this); return false;\">" . (($state == 'collapsed') ? ("{$this->lang->words['hookLangExpand']}") : ("{$this->lang->words['hookLangCollapse']}")) . "</a>]") : ("")) . "
</h4>
<p id=\"mot_body\"" . (($this->settings['expcol_mot'] && $state == 'collapsed') ? (" class='collapsedMOT' style='display: none;'") : ("")) . ">
	" . (($this->settings['mot_show_most_online']) ? ("{$this->lang->words['hookLangOnlineMostEver']}<br /><br />") : ("")) . "" . ((count($mems)) ? ("
		{$this->lang->words['hookLangOnlineList']}<br />
		<span class='name'>" . implode( ",</span>\n<span class='name'>", $mems ) . "</span>				
	") : ("
		{$this->lang->words['hookLangOnlineTodayNone']}
	")) . "
</p>";
return $IPBHTML;
}

/* -- hookRecentTopics --*/
function hookRecentTopics($topics) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookRecentTopics'] ) )
{
$count_50dc1d2626c8f8b3031a6344c80e3fab = is_array($this->functionData['hookRecentTopics']) ? count($this->functionData['hookRecentTopics']) : 0;
$this->functionData['hookRecentTopics'][$count_50dc1d2626c8f8b3031a6344c80e3fab]['topics'] = $topics;
}
$IPBHTML .= "" . ((is_array( $topics ) && count( $topics )) ? ("
<div class='ipsSideBlock clearfix'>
	<h3>{$this->lang->words['recently_added_topics']}</h3>
	<div class='_sbcollapsable'>
		<ul class='ipsList_withminiphoto'>
		".$this->__f__abccd4788795a28cfc9c4a8ac5fcfad8($topics)."		</ul>
	</div>
</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__abccd4788795a28cfc9c4a8ac5fcfad8($topics)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topics as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<li class='clearfix'>
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($r) : '' ) . "
			<div class='list_content'>
				<strong><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['tid']}", "public",'' ), "{$r['title_seo']}", "showtopic" ) . "\" rel='bookmark' class='ipsType_small' title='" . strip_tags($r['topic_title']) . " {$this->lang->words['topic_started_on']} " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['start_date'],"LONG", 0)) . "'>{$r['topic_title']}</a></strong>
				<p class='desc ipsType_smaller'>
					" . (($r['members_display_name']) ? ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($r) : '' ) . "") : ("{$this->settings['guest_name_pre']}{$r['starter_name']}{$this->settings['guest_name_suf']}")) . "
					- " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['start_date'],"short", 0)) . "
				</p>
			</div>
		</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hookTagCloud --*/
function hookTagCloud($tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookTagCloud'] ) )
{
$count_18607f6abe02dff6c7f605de8d531403 = is_array($this->functionData['hookTagCloud']) ? count($this->functionData['hookTagCloud']) : 0;
$this->functionData['hookTagCloud'][$count_18607f6abe02dff6c7f605de8d531403]['tags'] = $tags;
}
$IPBHTML .= "<div class='ipsSideBlock clearfix'>
	<h3>{$this->lang->words['popular_tags']}</h3>
	<div class='_sbcollapsable'>
		<ul class='ipsList_inline'>
		".$this->__f__79923ee2205917e7acf3dd6a291a1e1f($tags)."		</ul>
	</div>
</div>";
return $IPBHTML;
}


function __f__79923ee2205917e7acf3dd6a291a1e1f($tags)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $tags['tags'] as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li><span class=\"{$data['className']}\">{$data['tagWithUrl']}</span></li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- recentPosts --*/
function recentPosts($recentPosts) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['recentPosts'] ) )
{
$count_d8004914881a1ccf0643913f9c6ceea4 = is_array($this->functionData['recentPosts']) ? count($this->functionData['recentPosts']) : 0;
$this->functionData['recentPosts'][$count_d8004914881a1ccf0643913f9c6ceea4]['recentPosts'] = $recentPosts;
}
$IPBHTML .= "" . ((is_array($recentPosts) && count($recentPosts)) ? ("
  <div class='ipsSideBlock'>
	<h3>{$this->lang->words['recentposts_title']}</h3>
    <ul class='ipsList'> 
      ".$this->__f__9eb56058565e8c8d00995a783615204f($recentPosts)."    </ul>
  </div>
  <br />
") : ("")) . "";
return $IPBHTML;
}


function __f__9eb56058565e8c8d00995a783615204f($recentPosts)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $recentPosts as $post )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
        <li class='ipsPad_half' style='word-break: break-word;'>
          <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$post['tid']}&amp;view=getnewpost", "public",'' ), "{$post['title_seo']}", "showtopicunread" ) . "'><b>{$post['title']}</b></a>&nbsp;<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$post['tid']}&amp;view=getlastpost", "public",'' ), "{$post['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['view_last_post']}'>" . $this->registry->getClass('output')->getReplacement("f_lastpost") . "</a>
          <br/> 
          " . (($this->settings['hsc_rp_showforum']) ? ("
            {$this->lang->words['forum']}: <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$post['forum_id']}", "public",'' ), "{$post['forum_name_seo']}", "showforum" ) . "'>{$post['forum_name']}</a>
            <br/>
          ") : ("")) . " 
          " . (($this->settings['hsc_rp_start']) ? ("
            {$this->lang->words['started_by']}: " . IPSMember::makeProfileLink($post['starter_name'], $post['starter_id'], $post['seo_first_name']) . "&nbsp;<span class='date'>(" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($post['start_date'],"SHORT", 0)) . ")</span> 
            <br/> 
          ") : ("")) . " 
          " . (($this->settings['hsc_rp_post'] == 'F') ? (" 
            {$post['post']} 
            <br/> 
          ") : ("")) . " 
          " . (($this->settings['hsc_rp_views']) ? (" 
            <span class='desc lighter'>{$this->lang->words['views']} " . $this->registry->getClass('class_localization')->formatNumber( $post['views'] ) . " &nbsp; {$this->lang->words['replies']}: " . $this->registry->getClass('class_localization')->formatNumber( $post['posts'] ) . "</span> 
            <br/> 
          ") : ("")) . " 
          " . (($this->settings['hsc_rp_last']) ? (" 
            {$this->lang->words['last_reply']}: " . IPSMember::makeProfileLink($post['last_poster_name'], $post['last_poster_id'], $post['seo_last_name']) . "&nbsp;<span class='date'>(" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($post['last_post'],"SHORT", 0)) . ")</span> 
            <br/> 
          ") : ("")) . " 
          " . (($this->settings['hsc_rp_post'] == 'L' && $post['post']) ? ("
            {$post['post']} 
          ") : ("")) . " 
        </li> 
      
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- sos33popupindex --*/
function sos33popupindex($text) {
$IPBHTML = "";
$IPBHTML .= "<script language='javascript'>
function fechar(){
document.getElementById('sosinvision_popup').style.display = 'none';
}
</script>

<div id=\"sosinvision_popup\" style=\"z-index: 10001; margin-bottom: 16px; top: {$this->settings['sos33_popupindex_topo']}; left: {$this->settings['sos33_popupindex_esq']}; position: fixed; \" class=\"popupWrapper\">
<div class=\"popupInner\" align=\"left\" style=\"width: auto; max-height: auto; \"> 
<h3>{$this->settings['sos33_popupindex_titulo']}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h3> 
<div class=\"ipsBox\" style=\"min-height: auto\" align=\"left\"><div class='ipsBox_container ipsPad'>{$text}</div></div></div>
<div class=\"popupClose clickable\"><a href=\"javascript: fechar();\"><img src=\"{style_images_url}/close_popup.png\" alt=\"x\"></a></div></div>";
return $IPBHTML;
}

/* -- statusReplies --*/
function statusReplies($replies=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['statusReplies'] ) )
{
$count_5fcb41fc8a6f288b1948ba44ba9b930a = is_array($this->functionData['statusReplies']) ? count($this->functionData['statusReplies']) : 0;
$this->functionData['statusReplies'][$count_5fcb41fc8a6f288b1948ba44ba9b930a]['replies'] = $replies;
}
$IPBHTML .= "".$this->__f__e81a3d553636d0e3b0f97b7594569e1a($replies)."";
return $IPBHTML;
}


function __f__e81a3d553636d0e3b0f97b7594569e1a($replies=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $replies as $reply )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<div id='statusReply-{$reply['reply_id']}' class='ipsPad_half'>
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $reply, array( '_customClass' => 'ipsUserPhoto_tiny', 'alt' => sprintf($this->lang->words['users_photo'],$reply['members_display_name']) ) )) : '' ) . "
		<div class='list_content'>
			<div class='right lighter'>
				<span class='desc ipsType_smaller'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($reply['reply_date'],"manual{%d %b}", 0)) . "&nbsp;&nbsp;</span>
				<span class='desc mod_links ipsType_smaller'>
					" . (($reply['_canDelete']) ? ("<a href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteReply&amp;status_id={$reply['reply_status_id']}&amp;reply_id={$reply['reply_id']}&amp;k={$this->member->form_hash}\" id=\"statusReplyDelete-{$reply['reply_status_id']}-{$reply['reply_id']}\" class=\"__sDR __dr{$reply['reply_status_id']}-{$reply['reply_id']}\">{$this->lang->words['status_delete_link']}</a>") : ("")) . "
				</span>
			</div>
			<strong>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($reply) : '' ) . "</strong>
			<p class='index_status_update ipsType_small'>{$reply['reply_content']}</p>
		</div>
	</div>
	" . (($__iteratorCount == count($replies)) ? ("
		<div id='statusReplyBlank-{$reply['reply_status_id']}' style='display: none'></div>
	") : ("")) . "

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusUpdates --*/
function statusUpdates($updates=array(), $smallSpace=0, $latestOnly=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['statusUpdates'] ) )
{
$count_4438b2487b7b4c0f166f61de946e09c5 = is_array($this->functionData['statusUpdates']) ? count($this->functionData['statusUpdates']) : 0;
$this->functionData['statusUpdates'][$count_4438b2487b7b4c0f166f61de946e09c5]['updates'] = $updates;
$this->functionData['statusUpdates'][$count_4438b2487b7b4c0f166f61de946e09c5]['smallSpace'] = $smallSpace;
$this->functionData['statusUpdates'][$count_4438b2487b7b4c0f166f61de946e09c5]['latestOnly'] = $latestOnly;
}
$IPBHTML .= "<script type=\"text/javascript\">
	ipb.status.maxReplies = " . intval($this->settings['su_max_replies']) . ";
	ipb.status.smallSpace = " . intval($smallSpace) . ";
	ipb.status.skin_group = 'boards';
</script>".$this->__f__4daf2fa794442e114bff032e462950ed($updates,$smallSpace,$latestOnly)."";
return $IPBHTML;
}


function __f__4daf2fa794442e114bff032e462950ed($updates=array(), $smallSpace=0, $latestOnly=0)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $updates as $id => $status )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	" . (($this->memberData['member_id'] AND $latestOnly AND $status['member_id'] == $this->memberData['member_id']) ? ("
		<script type=\"text/javascript\">
			ipb.status.myLatest = {$status['status_id']};
		</script>
	") : ("")) . "
	<ul class='ipsList_withminiphoto status_list' id='statusWrap-{$status['status_id']}'>
		<li class='clearfix'>
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($status) : '' ) . "
			<div class='list_content'>
				<div id=\"statusContent-{$status['status_id']}\">
					<div class='right desc lighter'>
						<span class='desc mod_links ipsType_smaller'>
							" . (($status['_canDelete']) ? ("<a rel=\"nofollow\" href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusDelete-{$status['status_id']}\" class=\"__sD __d{$status['status_id']}\">{$this->lang->words['status_delete_link']}</a>") : ("")) . "
							<span id='statusUnlock-{$status['status_id']}' " . (($status['_isLocked'] AND $status['_canUnlock']) ? ("style='display:inline'") : ("style='display:none'")) . "> &middot; <a rel=\"nofollow\"  href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=unlockStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusUnlockLink-{$status['status_id']}\" class=\"__sU __u{$status['status_id']}\">{$this->lang->words['status_unlock_link']}</a></span>
							<span id='statusLock-{$status['status_id']}' " . (($status['_canLock'] AND ! $status['_isLocked']) ? ("style='display:inline'") : ("style='display:none'")) . "> &middot; <a rel=\"nofollow\"  href=\"{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=lockStatus&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}\" id=\"statusLockLink-{$status['status_id']}\" class=\"__sL __l{$status['status_id']}\">{$this->lang->words['status_lock_link']}</a></span>
						</span>
						&nbsp;&nbsp;<span class='ipsType_smaller blend_links'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=single&amp;status_id={$status['status_id']}", "public",'' ), array($status['member_id'], $status['members_seo_name']), "members_status_single" ) . "'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($status['status_date'],"manual{%d %b}", 0)) . "</a></span>
					</div>
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($status) : '' ) . "
					<p class='index_status_update ipsType_small'>{$status['status_content']}</p>
					<span class='desc' id='statusToggle-{$status['status_id']}'>
						<img src=\"{$this->settings['img_url']}/icon_lock.png\" id='statusLockImg-{$status['status_id']}' alt=\"{$this->lang->words['status__locked']}\" " . ((!$status['status_is_locked']) ? ("style='display: none'") : ("")) . " />
						" . ((! $smallSpace AND $status['_creatorImg']) ? ("<img src=\"{$status['_creatorImg']}\" alt='' data-tooltip=\"{$this->lang->words['su_via']} {$status['_creatorText']}\" />") : ("")) . "
						" . (($status['_userCanReply']) ? ("" . (($status['status_replies']) ? ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller \">" . sprintf( $this->lang->words['view_comments_and_add'], $status['status_replies']) . "</a>
							") : ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller\">{$this->lang->words['add_comments_only']}</a>
							")) . "") : ("" . (($status['status_replies']) ? ("
								<a href=\"#\" class=\"__sT __t{$status['status_id']} ipsType_smaller\">" . sprintf( $this->lang->words['view_comments_only'], $status['status_replies']) . "</a>
							") : ("")) . "")) . "
					</span>
					<span class='desc' id='statusToggleOff-{$status['status_id']}' style='display:none'>
						<a href=\"#\" class=\"__sTO __to{$status['status_id']}\">{$this->lang->words['view_comments_collapse']}</a>
					</span>
				</div>
			</div>
			<div id=\"statusFeedback-{$status['status_id']}\" class='status_feedback' style='display:none'>
				<div class='ipsList_withtinyphoto status_list' id='statusReplies-{$status['status_id']}'>
					" . (($status['status_replies'] AND count( $status['replies'] )) ? ("" . (($status['status_replies'] > 3) ? ("
							<div class='status_mini_wrap row2 altrow' id='statusMoreWrap-{$status['status_id']}'>
								<img src=\"{$this->settings['img_url']}/comments.png\" alt=\"\" /> &nbsp;<a href=\"#\" id=\"statusMore-{$status['status_id']}\" class='__showAll __x{$status['status_id']}'>" . sprintf( $this->lang->words['status_show_all_x'], $status['status_replies'] ) . "</a>
							</div>
						") : ("")) . "
						" . ( method_exists( $this->registry->getClass('output')->getTemplate('boards'), 'statusReplies' ) ? $this->registry->getClass('output')->getTemplate('boards')->statusReplies($status['replies']) : '' ) . "") : ("
						<div id='statusReplyBlank-{$status['status_id']}' style='display: none'></div>
					")) . "
				</div>
				" . (($status['_userCanReply']) ? ("
					<div class='ipsList_withtinyphoto status_list status_reply clearfix ipsPad_half' id='statusReply-{$status['status_id']}'>
						" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto(array_merge( $this->memberData, array( '_customClass' => 'ipsUserPhoto_tiny', 'alt' => sprintf($this->lang->words['users_photo'],$this->memberData['members_display_name']) ) )) : '' ) . "
						<div class='list_content'>
							<form id='statusReplyForm-{$status['status_id']}' action='{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=reply&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}&amp;id={$this->memberData['member_id']}' method='post'>
								<textarea class='status_textarea' rows='3' cols='50' name='comment-{$status['status_id']}' id='statusText-{$status['status_id']}'></textarea>
								<div class=\"status_submit\"><input type='submit' class='__submit input_submit' id='statusSubmit-{$status['status_id']}' value='{$this->lang->words['status__dfcomment']}' /></div>
							</form>
							<a href='#' class='__showform' id='statusReplyFormShow-{$status['status_id']}' style='display: none'>{$this->lang->words['status__addcomment']}</a>
						</div>
					</div>
					<script type='text/javascript'>
						if( $('statusReplyForm-{$status['status_id']}') ){
							$('statusReplyForm-{$status['status_id']}').hide();
						}
						if( $('statusReplyFormShow-{$status['status_id']}') ){
							$('statusReplyFormShow-{$status['status_id']}').show();
						}
					</script>
				") : ("")) . "
			</div>
		</li>
	</ul>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>