<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 8               */
/* CACHE FILE: Generated: Sun, 14 Feb 2016 17:34:28 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_portal_8 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['showRecentPosts'] = array('forum','starterInfo','firstPost','views','lastPostInfo','lastPost','posts');


}

/* -- showRecentPosts --*/
function showRecentPosts($recentPosts) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_portal', $this->_funcHooks['showRecentPosts'] ) )
{
$count_27c692cc6a51614f7f3b66c6a3c6d60e = is_array($this->functionData['showRecentPosts']) ? count($this->functionData['showRecentPosts']) : 0;
$this->functionData['showRecentPosts'][$count_27c692cc6a51614f7f3b66c6a3c6d60e]['recentPosts'] = $recentPosts;
}
$IPBHTML .= "<div class='ipsSideBlock'>
  <h3>{$this->lang->words['portal_rp__recentposts_title']}</h3>
  <ul class='ipsList'> 
    ".$this->__f__05673f333b64c7f4c521955d11cad684($recentPosts)."  </ul> 
</div>
<br />";
return $IPBHTML;
}


function __f__05673f333b64c7f4c521955d11cad684($recentPosts)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $recentPosts as $post )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
      <li class='ipsPad_half'>
        <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$post['tid']}&amp;view=getnewpost", "public",'' ), "{$post['title_seo']}", "showtopicunread" ) . "'><b>{$post['title']}</b></a>&nbsp;<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$post['tid']}&amp;view=getlastpost", "public",'' ), "{$post['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['portal_rp__view_last_post']}'>" . $this->registry->getClass('output')->getReplacement("f_lastpost") . "</a>
        <br/> 
        " . (($this->settings['portal_recentposts_showforum'] == 1) ? ("
          {$this->lang->words['portal_rp__forum']}: <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$post['forum_id']}", "public",'' ), "{$post['forum_name_seo']}", "showforum" ) . "'>{$post['forum_name']}</a>
          <br/>
        ") : ("")) . " 
        " . (($this->settings['portal_recentposts_start'] == 1) ? ("
          {$this->lang->words['portal_rp__started_by']}: " . IPSMember::makeProfileLink($post['starter_name'], $post['starter_id'], $post['seo_first_name']) . "&nbsp;<span class='date'>(" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($post['start_date'],"SHORT", 0)) . ")</span> 
          <br/> 
        ") : ("")) . " 
        " . (($this->settings['portal_recentposts_post'] == 'F') ? (" 
          {$post['post']} 
          <br/> 
        ") : ("")) . " 
        " . (($this->settings['portal_recentposts_views'] == 1) ? (" 
          <span class='desc lighter'>{$this->lang->words['portal_rp__views']}: " . $this->registry->getClass('class_localization')->formatNumber( $post['views'] ) . " &nbsp; {$this->lang->words['portal_rp__replies']}: " . $this->registry->getClass('class_localization')->formatNumber( $post['posts'] ) . "</span> 
          <br/> 
        ") : ("")) . " 
        " . (($this->settings['portal_recentposts_last'] == 1) ? (" 
          {$this->lang->words['portal_rp__last_reply']}: " . IPSMember::makeProfileLink($post['last_poster_name'], $post['last_poster_id'], $post['seo_last_name']) . "&nbsp;<span class='date'>(" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($post['last_post'],"SHORT", 0)) . ")</span> 
          <br/> 
        ") : ("")) . " 
        " . (($this->settings['portal_recentposts_post'] == 'L' && $post['post']) ? ("
          {$post['post']} 
        ") : ("")) . " 
      </li> 
    
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>