<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 8               */
/* CACHE FILE: Generated: Sun, 14 Feb 2016 17:34:28 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_jawards_8 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['hoverCard'] = array('UserList','anyThere');
$this->_funcHooks['listings_row'] = array('awardDesc','awardCount');
$this->_funcHooks['profile_award_row'] = array('showDesc','canRemove','showNotes','showLongDesc','noGivenBy');
$this->_funcHooks['profile_unawarded'] = array('showDesc','showDim','showDim','showNotes','showLongDesc');
$this->_funcHooks['topicPost_japab'] = array('count','size','toolTip','awardCount','profileawards');
$this->_funcHooks['topicPost_jappn'] = array('size','toolTip','awardCount','profileawards');
$this->_funcHooks['topicPost_View'] = array('size','toolTip','awardCount','profileawards');
$this->_funcHooks['topicSig_View'] = array('size','toolTip','awardCount','profileawards');


}

/* -- category_row_end --*/
function category_row_end($data="") {
$IPBHTML = "";
$IPBHTML .= "</table>";
return $IPBHTML;
}

/* -- category_row_start --*/
function category_row_start($data="") {
$IPBHTML = "";
$IPBHTML .= "<div class='maintitle'>{$data['title']}</div>
    <table class=\"ipb_table\">
<tr class='header'>
	<td align='center' class=\"jawards_head jawards_hdrawards\">{$this->lang->words['award']}</td>
	<td class=\"jawards_head jawards_hdrdesc\">{$this->lang->words['description']}</td>
	<td class=\"jawards_head jawards_hdrstats\">{$this->lang->words['statistics']}</td>
</tr>";
return $IPBHTML;
}

/* -- giveAward_form --*/
function giveAward_form($member, $options) {
$IPBHTML = "";
$IPBHTML .= "<form name=\"giveAward_public\" method=\"post\" action=\"{$this->settings['base_url']}app=jawards&do=award&mid={$member['member_id']}&submit=true\">
<h2 class=\"maintitle\">{$this->lang->words['give_award_title']} {$member['members_display_name']}</h2>
<div class=\"ipsBox\">
{$this->lang->words['give_award_msg']}
<div class=\"ipsBox\">
  <div class=\"ipsBox_container\">
    <table class=\"ipb_table\">
      <tr>
   	    <td width='35%'>
      	  <strong>{$this->lang->words['choose_award']}</strong>
    	</td>
   	 	<td>
          <select name='award'>
          " . ((count($options)) ? ("".$this->__f__af519c792a20fbd699ebdc6992b3d220($member,$options)."          </select>
          ") : ("")) . "
        </td>
 	  </tr>
  	  <tr>
    	<td><strong>{$this->lang->words['enter_award_notes']}</strong></td>
    	<td>
          <textarea name='notes' style='width:400px' rows='5'></textarea>
        </td>
  	  </tr>
	</table>
    <fieldset class=\"submit\">
      <input type=\"submit\" value=\"{$this->lang->words['give_award_continue']}\" class=\"input_submit\" />
    </fieldset>
  </div>
</div>
</div>
</form>";
return $IPBHTML;
}


function __f__af519c792a20fbd699ebdc6992b3d220($member, $options)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $options as $id => $label )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
              <option value='{$id}'>{$label}</option>
            
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hoverCard --*/
function hoverCard($list) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_jawards', $this->_funcHooks['hoverCard'] ) )
{
$count_8d1fb343c8608f30f8b78bd790472ae2 = is_array($this->functionData['hoverCard']) ? count($this->functionData['hoverCard']) : 0;
$this->functionData['hoverCard'][$count_8d1fb343c8608f30f8b78bd790472ae2]['list'] = $list;
}
$IPBHTML .= "<div style='min-height:200px; height:auto !important; height:200px; '>
	<h2 class=\"maintitle\">{$this->lang->words['awarded']}</h2>
	<div style='text-align: center'>
	" . ((count($list)) ? ("
		<ul class='JLogicaAwardTable'>
		".$this->__f__e78b7bd7c709d715e4a79a3be17d702b($list)."		</ul>
	</div>
	") : ("
		<div style=\"text-align:center;\">
			<br /><br />
			<h2 class='ipsType_subtitle'>{$this->lang->words['no_awards']}</h2>
		</div>
	")) . "
</div>";
return $IPBHTML;
}


function __f__e78b7bd7c709d715e4a79a3be17d702b($list)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $list as $l )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li><b>{$l}</b></li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- listings_container --*/
function listings_container($rows="", $form_hash) {
$IPBHTML = "";
$IPBHTML .= "<h2 class=\"maintitle\">{$this->lang->words['title']}</h2>
<div class=\"ipsBox\">
  <div class=\"ipsBox_container\">
      {$rows}
  </div>
</div>
<script type=\"text/javascript\">
var ajaxUrl = \"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=jawards&module=ajax&section=awards&do=getAwarded&md5check={$form_hash}", "public",'' ), "", "" ) . "\"
ipb.hoverCardRegister.initialize( 'showawarded', { 'w' : '400px', 'delay': 750, 'position' : 'auto' , 'ajaxUrl' : ajaxUrl, 'getId': true, 'setIdParam': 'id' } );
</script>";
return $IPBHTML;
}

/* -- listings_row --*/
function listings_row($cat='', $award="", $upload_url="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_jawards', $this->_funcHooks['listings_row'] ) )
{
$count_6e68b32e3534540e2b27b0ae7b376ed4 = is_array($this->functionData['listings_row']) ? count($this->functionData['listings_row']) : 0;
$this->functionData['listings_row'][$count_6e68b32e3534540e2b27b0ae7b376ed4]['cat'] = $cat;
$this->functionData['listings_row'][$count_6e68b32e3534540e2b27b0ae7b376ed4]['award'] = $award;
$this->functionData['listings_row'][$count_6e68b32e3534540e2b27b0ae7b376ed4]['upload_url'] = $upload_url;
}
$IPBHTML .= "<tr class=\"{$award['class']}\">
  <td width=\"15%\" align=\"center\" class=\"altrow\">
    <input type=\"hidden\" id=\"awrd_id_{$award['id']}\" value=\"{$award['id']}\" />
    <img src=\"{$upload_url}/jawards/{$award['icon']}\" />
  </td>
  <td>
    <h3>{$award['name']}</h3>
    <div class=\"desc\">
    " . (($award['longdesc']) ? ("
    	{$award['longdesc']}
    ") : ("
    	{$award['desc']}
    ")) . "
    </div>
  </td>
  <td width=\"25%\" class=\"altrow\" style=\"font-weight:bold;\">
  	{$this->lang->words['times_awarded']}:
    " . (($award['award_count']) ? ("
  		<a href=\"#\" class=\"_hovertrigger\" hovercard-ref=\"showawarded\" hovercard-id=\"{$award['id']}\">{$award['award_count']} ({$this->lang->words['view_awarded']})</a>
  	") : ("
		{$this->lang->words['no_awards']}
  	")) . "
  	<br />
  	{$this->lang->words['last_awarded']}:  " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($award['last_awarded'],"long", 0)) . "
  	</td>
</tr>";
return $IPBHTML;
}

/* -- profile_award_row --*/
function profile_award_row($data=array(), $uploadURL="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_jawards', $this->_funcHooks['profile_award_row'] ) )
{
$count_8cb6cc9c118563ad23dc182442c8157c = is_array($this->functionData['profile_award_row']) ? count($this->functionData['profile_award_row']) : 0;
$this->functionData['profile_award_row'][$count_8cb6cc9c118563ad23dc182442c8157c]['data'] = $data;
$this->functionData['profile_award_row'][$count_8cb6cc9c118563ad23dc182442c8157c]['uploadURL'] = $uploadURL;
}
$IPBHTML .= "<div class='general_box clearfix'>
        <h3>
        {$data['name']}
        " . (($this->settings['jacore_show_profile_desc']) ? ("
           :: {$data['award_desc']}
        ") : ("")) . "
        </h3>
<table>
  <tr class=\"row2\">
    <td width='10%' class='altrow' align='center'><img src='{$uploadURL}/jawards/{$data['icon']}' border='0' /></td>
    <td>
      " . (($data['remove_option']) ? ("
        <div class='right'>
          {$data['remove_option']}
        </div>
      ") : ("")) . "
        " . (($this->settings['jacore_show_profile_notes']) ? ("
		      {$data['notes']}
		") : ("")) . "
        " . (($this->settings['jacore_show_profile_longdesc']) ? ("
  		    {$data['longdesc']}
  		") : ("")) . "
      <strong>{$this->lang->words['award_given_on']}</strong> {$data['date']} 
      " . (($this->settings['jacore_show_profile_given']) ? ("<strong>{$this->lang->words['award_given_by']}</strong> {$data['given_by']}
        " . ((!$data['given_by']) ? ("
         <em>{$this->lang->words['given_by_unknown']}</em>
        ") : ("")) . "") : ("")) . "
    </td>
  </tr>
</table>
</div>";
return $IPBHTML;
}

/* -- profile_awards_block --*/
function profile_awards_block($rows="") {
$IPBHTML = "";
$IPBHTML .= "<h2 class='maintitle'>{$this->lang->words['awards_profile_view_title']}</h3>
<div class=\"ipsBox\">
  <div class=\"ipsBox_container\">
    {$rows}
  </div>
</div>";
return $IPBHTML;
}

/* -- profile_noawards --*/
function profile_noawards() {
$IPBHTML = "";
$IPBHTML .= "<h2 class='maintitle'>{$this->lang->words['awards_profile_view_title']}</h3>
<div class='general_box clearfix'>
        <h3>
	        {$this->lang->words['error_no_awards']}
        </h3>
</div>";
return $IPBHTML;
}

/* -- profile_unawarded --*/
function profile_unawarded($rows=array(), $uploadURL='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_jawards', $this->_funcHooks['profile_unawarded'] ) )
{
$count_ea3ca9e8e6c92eefb7be426359d62af5 = is_array($this->functionData['profile_unawarded']) ? count($this->functionData['profile_unawarded']) : 0;
$this->functionData['profile_unawarded'][$count_ea3ca9e8e6c92eefb7be426359d62af5]['rows'] = $rows;
$this->functionData['profile_unawarded'][$count_ea3ca9e8e6c92eefb7be426359d62af5]['uploadURL'] = $uploadURL;
}
$IPBHTML .= "<br /><br />
<h2 class='maintitle'>{$this->lang->words['awards_profile_view_unawarded']}</h3>
	<div class='general_box clearfix'>
  <div class=\"ipsBox_container\">
		" . ((count($rows)) ? ("".$this->__f__e4c53de8a55813e5bc67d4ddf988ebeb($rows,$uploadURL)."		") : ("
        	<h3>
	        	{$this->lang->words['error_no_awards']}
        	</h3>
		")) . "
</div>
</div>";
return $IPBHTML;
}


function __f__e4c53de8a55813e5bc67d4ddf988ebeb($rows=array(), $uploadURL='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $rows as $award )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<div class='general_box clearfix'>
        			<h3>
        				{$award['name']}
        				" . (($this->settings['jacore_show_profile_desc']) ? ("
           					:: {$award['award_desc']}
        				") : ("")) . "
        			</h3>
					<table>
  						<tr class=\"row2\">
    						<td width='10%' class='altrow' align='center'>
		        				" . (($this->settings['jacore_profiledim']) ? ("
									<span style='{$this->settings['jacore_profiledim']}'>
								") : ("")) . "
    							<img src='{$uploadURL}/jawards/{$award['icon']}' border='0' />
		        				" . (($this->settings['jacore_profiledim']) ? ("
									</span>
								") : ("")) . "
    						</td>
    						<td>
								" . (($this->settings['jacore_show_profile_notes']) ? ("
		      						{$award['notes']}
								") : ("")) . "
        						" . (($this->settings['jacore_show_profile_longdesc']) ? ("
	  		    					{$award['longdesc']}
  								") : ("")) . "
							</td>
						</tr>
					</table>
				</div>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- topicPost_japab --*/
function topicPost_japab($awards, $member) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_jawards', $this->_funcHooks['topicPost_japab'] ) )
{
$count_ab1ce47eb8dae306a1eb6b1df9617a34 = is_array($this->functionData['topicPost_japab']) ? count($this->functionData['topicPost_japab']) : 0;
$this->functionData['topicPost_japab'][$count_ab1ce47eb8dae306a1eb6b1df9617a34]['awards'] = $awards;
$this->functionData['topicPost_japab'][$count_ab1ce47eb8dae306a1eb6b1df9617a34]['member'] = $member;
}
$IPBHTML .= "<div style=\"margin-top:10px;\">
  <h3><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}&amp;tab=jawards", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "'>{$this->lang->words['awards_achievement_post']}</a></h3>
  <div class=\"row2\" style=\"padding:7px;\">
    ".$this->__f__1e20660360c6bc3eca11e4a2041d0668($awards,$member)."  </div>
</div>";
return $IPBHTML;
}


function __f__1e20660360c6bc3eca11e4a2041d0668($awards, $member)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $awards as $a )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
          " . (($a['count'] == 0) ? ("
              <span style='{$a['dim']}'>
          ") : ("")) . "
          <img src='{$this->settings['upload_url']}/jawards/{$a['icon']}'
          " . (($a['width']) ? ("
              width='{$a['width']}' height='{$a['height']}'
          ") : ("")) . "
          " . (($a['toolTip']) ? ("
              title='{$a['toolTip']}'
          ") : ("")) . "
          />
         " . (($a['count'] > 1) ? ("
             <span class='JLogicaAwardsCount'>{$a['count']}</span>
         ") : ("")) . "
          " . (($a['count'] == 0) ? ("
              </span>
          ") : ("")) . "
         {$a['hook']['settings']['padding']}
    
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- topicPost_japbd --*/
function topicPost_japbd($img) {
$IPBHTML = "";
$IPBHTML .= "<img class=\"JLogicaAwardsTopRight\" src=\"{$this->settings['upload_url']}/jawards/{$img}\">";
return $IPBHTML;
}

/* -- topicPost_jappn --*/
function topicPost_jappn($awards, $member) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_jawards', $this->_funcHooks['topicPost_jappn'] ) )
{
$count_1d7356ad05976a1aa0ead74b24ec1e9d = is_array($this->functionData['topicPost_jappn']) ? count($this->functionData['topicPost_jappn']) : 0;
$this->functionData['topicPost_jappn'][$count_1d7356ad05976a1aa0ead74b24ec1e9d]['awards'] = $awards;
$this->functionData['topicPost_jappn'][$count_1d7356ad05976a1aa0ead74b24ec1e9d]['member'] = $member;
}
$IPBHTML .= "".$this->__f__3971bd68f8b6778fb4c1bd892deb0edc($awards,$member)."";
return $IPBHTML;
}


function __f__3971bd68f8b6778fb4c1bd892deb0edc($awards, $member)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $awards as $a )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
      <img src='{$this->settings['upload_url']}/jawards/{$a['icon']}'
      " . (($a['width']) ? ("
          width='{$a['width']}' height='{$a['height']}'
      ") : ("")) . "
      " . (($a['toolTip']) ? ("
          title='{$a['toolTip']}'
      ") : ("")) . "
      />
     " . (($a['count'] > 1) ? ("
         <span class='JLogicaAwardsCount'>{$a['count']}</span>
     ") : ("")) . "
     {$a['hook']['settings']['padding']}

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- topicPost_View --*/
function topicPost_View($awards, $member) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_jawards', $this->_funcHooks['topicPost_View'] ) )
{
$count_63bf6183c212bdf63cfc175dee3faefd = is_array($this->functionData['topicPost_View']) ? count($this->functionData['topicPost_View']) : 0;
$this->functionData['topicPost_View'][$count_63bf6183c212bdf63cfc175dee3faefd]['awards'] = $awards;
$this->functionData['topicPost_View'][$count_63bf6183c212bdf63cfc175dee3faefd]['member'] = $member;
}
$IPBHTML .= "<div style=\"margin-top:10px;\">
  <h3><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}&amp;tab=jawards", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "'>{$this->lang->words['awards_title_post']}</a></h3>
  <div class=\"row2\" style=\"padding:7px;\">
    ".$this->__f__d0f90390b6584601f0be8e5ca41ec301($awards,$member)."  </div>
</div>";
return $IPBHTML;
}


function __f__d0f90390b6584601f0be8e5ca41ec301($awards, $member)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $awards as $a )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
          <img src='{$this->settings['upload_url']}/jawards/{$a['icon']}'
          " . (($a['width']) ? ("
              width='{$a['width']}' height='{$a['height']}'
          ") : ("")) . "
          " . (($a['toolTip']) ? ("
              title='{$a['toolTip']}'
          ") : ("")) . "
          />
         " . (($a['count'] > 1) ? ("
             <span class='JLogicaAwardsCount'>{$a['count']}</span>
         ") : ("")) . "
         {$a['hook']['settings']['padding']}
    
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- topicSig_View --*/
function topicSig_View($awards, $member) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_jawards', $this->_funcHooks['topicSig_View'] ) )
{
$count_2a53d2c56900a920dc30794ebae2c2c9 = is_array($this->functionData['topicSig_View']) ? count($this->functionData['topicSig_View']) : 0;
$this->functionData['topicSig_View'][$count_2a53d2c56900a920dc30794ebae2c2c9]['awards'] = $awards;
$this->functionData['topicSig_View'][$count_2a53d2c56900a920dc30794ebae2c2c9]['member'] = $member;
}
$IPBHTML .= "" . ((!$member['signature']) ? ("
<div class=\"signature\" align=\"{$awards[0]['hook']['settings']['position']}\">
") : ("
<div align=\"{$awards[0]['hook']['settings']['position']}\">
")) . "
<div class=\"_sharedMediaBbcode\">
  <div class=\"bbcode_mediaWrap\" style=\"text-align:left;\">
    <div class=\"details\" style=\"float:none; margin:0; margin-bottom:10px; padding:0;\"><h5><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}&amp;tab=jawards", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "'>{$this->lang->words['awards_signature_post']}</a></h5></div><br />
    ".$this->__f__b071185e4cfe177907cf565417ecb917($awards,$member)."  </div>
</div>
</div><br />
<br />";
return $IPBHTML;
}


function __f__b071185e4cfe177907cf565417ecb917($awards, $member)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $awards as $a )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
      <img src='{$this->settings['upload_url']}/jawards/{$a['icon']}'
      " . (($a['width']) ? ("
       width='{$a['width']}' height='{$a['height']}'
      ") : ("")) . "
      " . (($a['toolTip']) ? ("
        title='{$a['toolTip']}'
      ") : ("")) . "
      />
         " . (($a['count'] > 1) ? ("
             <span class='JLogicaAwardsCount'>{$a['count']}</span>
         ") : ("")) . "
     {$a['hook']['settings']['padding']}
    
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>