sound/misc/monsterkill.wav
sound/misc/multikill.wav
sound/misc/killingspree.wav
sound/misc/humiliation.wav
sound/misc/ultrakill.wav
sound/misc/headshot.wav
sound/misc/doublekill.wav
sound/misc/firstblood.wav
sound/misc/rampage.wav
sound/misc/unstoppable.wav
sound/misc/dominating.wav
sound/misc/perfect.wav
sound/misc/godlike.wav
sound/misc/rejuvenationtarget1.wav
sound/misc/goodbye.wav
sound/misc/woohoo.wav
sound/misc/woohoo2.wav
sound/misc/awwcrap.wav
sound/misc/awwcrap2.wav
sound/misc/awwman.wav
sound/misc/haha.wav
sound/misc/doh.wav
sound/misc/doh2.wav
sound/misc/doh3.wav
sound/misc/doh4.wav
sound/misc/doh5.wav
sound/misc/doh7.wav
sound/misc/dohoo.wav
sound/misc/dohnuts.wav
sound/misc/bud.wav
sound/misc/weis.wav
sound/misc/er.wav
sound/misc/ow.wav
sound/misc/doomed.wav
sound/misc/adica.wav
sound/misc/alleluja.wav
sound/misc/ALO.wav
sound/misc/amor.wav
sound/misc/ani.wav
sound/misc/aplauze.wav
sound/misc/bastard.wav
sound/misc/Beleste+ochii.wav
sound/misc/bleeeat.wav
sound/misc/bomba.wav
sound/misc/CAPCANA.wav
sound/misc/doomed.wav
sound/misc/goodbye.wav
sound/misc/3morti.wav
sound/misc/alo2.wav
sound/misc/beback.wav
sound/misc/groaza.wav
sound/misc/pro_ctwin_8.wav
sound/misc/lake.wav
sound/misc/idiot.wav
sound/misc/dumnezeii.wav
sound/misc/scooter.wav
sound/misc/copil.wav
sound/misc/cow.wav
sound/misc/kiss.wav 
sound/misc/be_lol.wav
sound/misc/femeie.wav
sound/misc/loli.wav
maps/awp_metro.res