<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 03 Oct 2015 16:55:08 +0000 by Polica
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'cmpt_public_php_from' => "From",
'cmpt_public_php_languages' => "Languages",
'cmpt_public_php_leader_title' => "Title",
'cmpt_public_php_nonefound' => "None Found",
'cmpt_public_php_since' => "Joined",
 ); 
