<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 03 Oct 2015 16:55:08 +0000 by Polica
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'adding_block' => "Добавление нового блока",
'add_block' => "Добавить блок",
'add_new_block' => "Добавить новый блок",
'and_reload' => "и Перезагрузить",
'blocks_page' => "Управление пользовательскими блоками",
'blocks_recached' => "Кеш блоков был обновлён",
'block_added' => "Блок был успешно добавлен",
'block_deleted' => "Блок был успешно удалён!",
'block_details' => "Настройки блока",
'block_edited' => "<%NAME%> блок был успешно изменён!",
'block_title' => "Название блока:",
'boxed' => "В рамке",
'collapsible' => "Блок сворачивается",
'custom_sidebar_blocks' => "Пользовательские блоки",
'delete_block' => "Удалить блок",
'display_content' => "Настройки отображения",
'do_raw_html' => "Включить RAW HTML/JS режим?",
'do_raw_html_exp' => "Если включено, будет происходить без разбора. Хорошо, если вы хотите, показать только HTML/JavaScript, например, поместить виджет или баннер.",
'editing' => "Редактирование",
'edit_block' => "Создать/изменить блок",
'enabled' => "Показать блок?",
'enabled_exp' => "Настройка показа.",
'enter_content_below' => "Введите содержимое блока:",
'enter_content_below_exp' => "HTML и BBкоды разрешены. А так же другие языки программирования.",
'error_none_found' => "Нету блоков соответствующих ID!",
'error_no_id' => "Нету ID совпадений!",
'export_block' => "Экспортировать блок",
'general_config' => "Главные настройки",
'hide_collapse_ability' => "Сделать невозможным свернуть блок?",
'hide_collapse_ability_exp' => "Если включено, то блок нельзя будет свернуть, как другие.",
'hide_from_main_block' => "Скрыть от основных пользовательских блоков?",
'hide_from_main_block_exp' => "Если включено, то этот блок будет пропущен при отображении всех пользовательских блоков в индексе.",
'image' => "Иконка",
'image_name' => "Полное имя изображения (С расширением!):",
'image_name_exp' => "Картинка должна быть загружена в: \"public/style_images/master\"! Или в созданную папку по этому пути.",
'options' => "Опции",
'parsing_options' => "Настройки содержимого",
'perms' => "Права доступа",
'php_based' => "Включить PHP режим?",
'php_based_exp' => "Если включено, и функция выше отключена, всё содержимое блока должно быть в PHP.  Вам нужно возвратить HTML для отображения, и не использовать echo, print, и т.д.  И не используйте открытые/закрытые теги PHP.<br />
	  Все стандартные объекты IPB доступны (registry, DB, memberData, cache, settings, request, и т.д.).",
'php_mode' => "PHP режим",
'preview' => "Предпросмотр",
'raw_mode' => "Raw режим",
'recache_blocks' => "Обновить кеш",
'title_exp' => "Отображается в заголовке блока.",
'use_box' => "Использовать Таблицу/Обводку/Название/Иконку?",
'use_box_exp' => "Настройка того как будет выглядить блок.",
'use_perms' => "Использовать настройки ниже?",
'use_perms_exp' => "Оставьте \"Нет\" чтобы игнорировать настройки ниже.",
 ); 
