<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 03 Oct 2015 16:55:08 +0000 by Polica
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'bbc_after' => "Так отображается",
'bbc_before' => "Так вводите",
'bbc_intro' => "BB-код простой и быстрый способ добавить форматирование в ваши сообщения.<br />Он напоминает HTML теги, с которыми вы возможно уже знакомы.<br />Ниже мы собрали BB-коды, доступные вам, и показали, как их использовать.",
'bbc_title' => "BB-код",
'emo_title' => "Смайлики",
 ); 
