<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 03 Oct 2015 16:55:08 +0000 by Polica
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'mem_change_button' => "Изменить",
'mem_posts' => "Сообщения",
'm_overrride' => "Переопределить права группы следующими масками",
 ); 
