<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 13 Oct 2015 13:34:08 +0000 by Polica
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'award' => "Награда",
'awarded' => "Награжден",
'awards_achievement_post' => "Достижения",
'awards_profile_tab_title' => "Награды",
'awards_profile_view_title' => "Награды",
'awards_profile_view_unawarded' => "У пользователя нету наград",
'awards_signature_post' => "Награды",
'awards_title_post' => "Награды",
'award_added' => "Награда добавлена",
'award_given_by' => "пользователем",
'award_given_on' => "Выдана",
'award_icon' => "Значок награды",
'award_info' => "Название / Описание",
'award_removed' => "Награда удалена",
'choose_award' => "Выберите награду",
'description' => "Описание",
'enter_award_notes' => "Примечание",
'error_invalid_request' => "Ссылка недействительна",
'error_listings_disabled' => "Страница отключена администратором.",
'error_no_awarded' => "Нету пользователей с этой наградой.",
'error_no_awards' => "Нету отображаемых наград для Вас.",
'error_no_permission' => "У Вас нет прав доступа к этой странице",
'given_by_unknown' => "Неизвестно",
'give_award_continue' => "Выдать награду",
'give_award_msg' => "Выберите награду из списка. По желанию можно добавлять примечание.",
'give_award_title' => "Выдал награду",
'hide_awarded' => "Скрыть награждённого",
'last_awarded' => "Последний награждённый",
'no_awards' => "Нету",
'pending_approval' => "Ожидающие утверждения",
'profile_public_award' => "Выдать награду",
'remove_award' => "Удалить награду",
'statistics' => "Статистика",
'times_awarded' => "Награждённых",
'title' => "Награды",
'view_awarded' => "Просмотр",
 ); 
