<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 13 Oct 2015 13:34:08 +0000 by Polica
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'menu__cabinet_permissions' => "Настройки кабинета",
'menu__system_overview' => "Обзор",
 ); 
