<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 03 Oct 2015 16:55:08 +0000 by Polica
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'disable' => "Отключить",
'enable' => "Включить",
'enabled' => "Включено",
'group_name_indicator' => "Индикатор групп",
'g_hidden' => "скрыта",
'g_shown' => "показана",
'g_successfully' => "Группа успешно ",
'g_title' => "Название групп",
'hidden_groups' => "Скрытые группы",
'm_display_order' => "Управление показом",
'no_toggle_guest' => "Можно&#39;t переключить группу гости",
'postform_badmd5' => "Bad key supplied",
'shown_groups' => "Группы",
 ); 
