<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Sun, 27 Sep 2015 13:40:54 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_global_other_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['ajaxPopUpNoPermission'] = array('msg','msg');
$this->_funcHooks['displayBoardOffline'] = array('isGuest','isGuest');
$this->_funcHooks['displayPopUpWindow'] = array('donotminifycss','cssImport','popupcssInline','popupmetaTags','popupjavascript','popuprss','popuprss','popupraw','popupdocumentHeadItems','popupheaditemtype','minifycss','csstominify','hasimportcss','popupcssinline','popupmetatags','popupminfiyrlhttpsp','popupminfiyrlhttpss','popupminfyjsrl','popupjsmodules','popuphttpsp','popuprl','popupjsmodules','popuphttpss','popuprl2','popupminifyjs','popupdocumenthead','popupbefriend','istm','istl','popupswfupload','popupfurl','donotminifycss','cssImport','popupcssInline','popupmetaTags','popupjavascript','popuprss','popuprss','popupraw','popupdocumentHeadItems','popupheaditemtype','minifycss','csstominify','hasimportcss','popupcssinline','popupmetatags','popupminfiyrlhttpsp','popupminfiyrlhttpss','popupminfyjsrl','popuphttpsp','popuprl','popuphttpss','popuprl2','popupminifyjs','popupdocumenthead','popupbefriend','istm','istl','popupswfupload','popupfurl');
$this->_funcHooks['Error'] = array('haserrorcode','savedpost','showerrortitle','haserrorcode','savedpost');
$this->_funcHooks['facebookPop'] = array('hasFbConnected');
$this->_funcHooks['generateTopicIcon'] = array('topicIsMoved','topicIsClosed','topicReadDot','topicUnreadDot','gotolatestwrap','topicIsMoved','topicIsClosed','topicReadDot','topicUnreadDot','gotolatestwrap');
$this->_funcHooks['globalTemplateMinimal'] = array('fbcenabled','pagenumberintitle','isLargeTouch','isSmallTouch','mainpageContent','lastvisit','isfloat','sqldebuglink','closesqldebuglink','showdebuglevel','fbcenabled','pagenumberintitle','brandingBar','messengerlink','memberbox','hasBlog','hasGallery','viewnewcontentapp','mainpageContent','skinchanger','langchooser','isNotMobbyApp');
$this->_funcHooks['inboxList'] = array('loopynotify','hasTopics');
$this->_funcHooks['likeMoreDialogue'] = array('hasVisibleEntries','hasAnonEntries');
$this->_funcHooks['likeSummaryContents'] = array('likeOnlyMembers');
$this->_funcHooks['notificationsList'] = array('loopynotify','hasnotifications','notifications');
$this->_funcHooks['questionAndAnswer'] = array('qadefault');
$this->_funcHooks['quickNavigationPanel'] = array('depth','important','innerAgain','hasTitle','linksisarray','outer');
$this->_funcHooks['quickNavigationWrapper'] = array('active','navTabs','isLargeTouch');
$this->_funcHooks['redirectTemplate'] = array('redirectcssImport','redirctcssInline','redirectjs','redirectrss','redirectrsd','redirectraw','redirectdocumentHeadItemsSub','redirectdocumentHeadItems','redirectfull','redirectcssimport','redirectcssinline','redirectdh','redirectmozfull','redirectlink','redirectcssImport','redirctcssInline','redirectjs','redirectrss','redirectrsd','redirectraw','redirectdocumentHeadItemsSub','redirectdocumentHeadItems','redirectfull','redirectcssimport','redirectcssinline','redirectdh','redirectmozfull','redirectlink');
$this->_funcHooks['repButtons'] = array('hasNoLikes','giveRepUp','giveRepDown','canGiveRep','pos','giveRepUp','giveRepDown','canGiveRep','hasNoRep','hasPosRep','hasNegRep','isNotLike','isLike','canRep','reputationBox','giveRepUp','canGiveRep','canGiveRep','giveRepDown','isLike','canRep','giveRepUp','giveRepDown','giveRepUp','giveRepDown','canGiveRep','isLike','canRep','reputationBox');
$this->_funcHooks['socialSharePostStrip'] = array('canShareThis','services','canSave','canShare');
$this->_funcHooks['tagCloud'] = array('eachTag','eachTag');
$this->_funcHooks['tagEntry'] = array('noClass','inSearch','inSearchSub','hasSearchSection','noClass','inSearch','inSearchSub','hasSearchSection');
$this->_funcHooks['tagPrefix'] = array('inSearch','inSearchSub','hasSearchSection','inSearch','inSearchSub','hasSearchSection');
$this->_funcHooks['tagTextEntryBox'] = array('isClosedField','prefixChecked','canPrefix');


}

/* -- ajaxPopUpNoPermission --*/
function ajaxPopUpNoPermission($msg='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['ajaxPopUpNoPermission'] ) )
{
$count_a534adfdda2c4a813dbe2080dfeef0e5 = is_array($this->functionData['ajaxPopUpNoPermission']) ? count($this->functionData['ajaxPopUpNoPermission']) : 0;
$this->functionData['ajaxPopUpNoPermission'][$count_a534adfdda2c4a813dbe2080dfeef0e5]['msg'] = $msg;
}
$IPBHTML .= "<h3>{$this->lang->words['ap_error']}</h3>
<div class='general_box'>
	<div>
		" . (($msg) ? ("
			$msg
		") : ("
			{$this->lang->words['ap_np_msg']}
		")) . "
	</div>
</div>";
return $IPBHTML;
}

/* -- captchaGD --*/
function captchaGD($captcha_unique_id) {
$IPBHTML = "";
$IPBHTML .= "<input type=\"hidden\" name=\"captcha_unique_id\" value=\"{$captcha_unique_id}\" />
<div class='ipsField'>
	<label for='gd' class='ipsField_title'>{$this->lang->words['glb_captcha_image']}</label>
	<img id='gd-antispam' class='antispam_img' src='{$this->settings['base_url']}app=core&amp;module=global&amp;section=captcha&amp;do=showimage&amp;captcha_unique_id={$captcha_unique_id}' class='ipd' />
	<br /><br />
	<!--<span class='desc'>{$this->lang->words['gbl_captcha_image_desc']}</span>-->
	<!--{$this->lang->words['glb_captcha_enter']}<br />-->
	<input type=\"text\" class='input_text' size=\"30\" maxlength=\"30\" value=\"\" name=\"captcha_string\" tabindex='0' /><br />
	<!--<span class='desc'>{$this->lang->words['glb_captcha_text']}</span>-->
</div>";
return $IPBHTML;
}

/* -- captchaKeycaptcha --*/
function captchaKeycaptcha($challenge="") {
$IPBHTML = "";
$IPBHTML .= "<div id=\"keycaptcha_div\" style=\"text-align:center\">
	<table>
		<tr>
			<td>{$this->lang->words['complete_antispam_task']}</td>
		</tr>
		<tr>
			<td align=\"center\">{$challenge}</td>
		</tr>
	</table>
</div>";
return $IPBHTML;
}

/* -- captchaRecaptcha --*/
function captchaRecaptcha($html="") {
$IPBHTML = "";
$IPBHTML .= "<div class='row'>
	<strong>{$this->lang->words['glb_captcha_image']}</strong>
	{$html}
</div>";
return $IPBHTML;
}

/* -- displayBoardOffline --*/
function displayBoardOffline($message="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['displayBoardOffline'] ) )
{
$count_3ab49a1388e9f1d087572bd50264c336 = is_array($this->functionData['displayBoardOffline']) ? count($this->functionData['displayBoardOffline']) : 0;
$this->functionData['displayBoardOffline'][$count_3ab49a1388e9f1d087572bd50264c336]['message'] = $message;
}
$IPBHTML .= "<h1 class='ipsType_pagetitle'>" . sprintf( $this->lang->words['board_offline_desc'], $this->settings['board_name']) . "</h1>
<div class='ipsType_pagedesc'>{$message}</div>
<br /><br />
<p>
	" . ((!$this->memberData['member_id']) ? ("
		<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login", "public",'' ), "", "" ) . "' title='{$this->lang->words['attempt_login']}' class='ipsButton'>{$this->lang->words['click_login']}</a>
	") : ("
		<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login&amp;do=logout&amp;k={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['log_out']}' class='ipsButton_secondary'>{$this->lang->words['log_out']}</a>
	")) . "
</p>";
return $IPBHTML;
}

/* -- displayPopUpWindow --*/
function displayPopUpWindow($documentHeadItems, $css, $jsLoaderItems, $title="", $output="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['displayPopUpWindow'] ) )
{
$count_79bb4656db823f74b0a6626b2f8affbe = is_array($this->functionData['displayPopUpWindow']) ? count($this->functionData['displayPopUpWindow']) : 0;
$this->functionData['displayPopUpWindow'][$count_79bb4656db823f74b0a6626b2f8affbe]['documentHeadItems'] = $documentHeadItems;
$this->functionData['displayPopUpWindow'][$count_79bb4656db823f74b0a6626b2f8affbe]['css'] = $css;
$this->functionData['displayPopUpWindow'][$count_79bb4656db823f74b0a6626b2f8affbe]['jsLoaderItems'] = $jsLoaderItems;
$this->functionData['displayPopUpWindow'][$count_79bb4656db823f74b0a6626b2f8affbe]['title'] = $title;
$this->functionData['displayPopUpWindow'][$count_79bb4656db823f74b0a6626b2f8affbe]['output'] = $output;
}

$this->minify = array();
$IPBHTML .= "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"> 
<html xml:lang=\"ru\" lang=\"ru\" xmlns=\"http://www.w3.org/1999/xhtml\"> 
	<head>
		<!-- THIS TEMPLATE (displayPopUpWindow) IS DEPRICATED AND WILL BE REMOVED IN A FUTURE VERSION -->
		<meta http-equiv=\"content-type\" content=\"text/html; charset={$this->settings['gb_char_set']}\" />
		<title>{$title}</title>
		<link rel=\"shortcut icon\" href=\"favicon.ico\" />
		" . ((is_array( $css['import'] )) ? ("" . (($this->settings['use_minify']) ? ("") : ("")) . "
			".$this->__f__2bb7719343f52dd27d6461323dbf0a92($documentHeadItems,$css,$jsLoaderItems,$title,$output)."			" . (($this->settings['use_minify'] AND count($this->minify)) ? ("
				<link rel=\"stylesheet\" type=\"text/css\" media='screen,print' href=\"{$this->settings['css_base_url']}min/index.php?ipbv={$this->registry->output->antiCacheHash}&amp;f=" . str_replace( $this->settings['css_base_url'], PUBLIC_DIRECTORY . '/', implode( ',', $this->minify ) ) . "\" />
			") : ("")) . "") : ("")) . "
		" . ((is_array( $css['inline'] ) AND count( $css['inline'] )) ? ("
			".$this->__f__85850b52dacfb239582dc4fe8e2c90c2($documentHeadItems,$css,$jsLoaderItems,$title,$output)."		") : ("")) . "
		<!--[if lte IE 7]>
			<link rel=\"stylesheet\" type=\"text/css\" title='Main' media=\"screen\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_ie.css\" />
		<![endif]-->
		
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeRTL' ) ? $this->registry->getClass('output')->getTemplate('global')->includeRTL() : '' ) . "	
		" . ((is_array( $metaTags ) AND count( $metaTags )) ? ("
			".$this->__f__2ba6346d79ed48b093c5255b10984a66($documentHeadItems,$css,$jsLoaderItems,$title,$output)."		") : ("")) . "
		<script type='text/javascript'>
			jsDebug		= " . intval($this->settings['_jsDebug']) . "; /* Must come before JS includes */
			USE_RTE		= 1;
			var inACP	= false;
			var isRTL	= false;
			var rtlIe	= '';
			var rtlFull	= '';
		</script>
		" . (($this->settings['use_minify']) ? ("" . (($this->settings['remote_load_js']) ? ("<script type='text/javascript' src='" . (($this->registry->output->isHTTPS) ? ("https") : ("http")) . "://ajax.googleapis.com/ajax/libs/prototype/1.7/prototype.js'></script>
				<script type='text/javascript' src='" . (($this->registry->output->isHTTPS) ? ("https") : ("http")) . "://ajax.googleapis.com/ajax/libs/scriptaculous/1.8/scriptaculous.js?load=effects,dragdrop,builder'></script>") : ("
				<script type='text/javascript' src='{$this->settings['public_dir']}min/index.php?g=js'></script>
			")) . "") : ("" . (($this->settings['remote_load_js']) ? ("<script type='text/javascript' src='" . (($this->registry->output->isHTTPS) ? ("https") : ("http")) . "://ajax.googleapis.com/ajax/libs/prototype/1.7/prototype.js'></script>") : ("
				<script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/prototype.js'></script>
			")) . "
			
			" . (($this->settings['remote_load_js']) ? ("<script type='text/javascript' src='" . (($this->registry->output->isHTTPS) ? ("https") : ("http")) . "://ajax.googleapis.com/ajax/libs/scriptaculous/1.8/scriptaculous.js?load=effects,dragdrop,builder'></script>") : ("
				<script type='text/javascript' src='{$this->settings['public_dir']}js/3rd_party/scriptaculous/scriptaculous-cache.js'></script>
			")) . "")) . "
		
		<!--Remove if you don't want touch devices-->
		<script type=\"text/javascript\" src=\"{$this->settings['public_dir']}js/mobile_touch.js\"></script>
		<script type=\"text/javascript\" src='{$this->settings['cache_dir']}lang_cache/{$this->lang->lang_id}/ipb.lang.js' charset='{$this->settings['gb_char_set']}'></script>
		" . ((count($documentHeadItems)) ? ("
			".$this->__f__7dc83e20573099d616ccf05b41f57e90($documentHeadItems,$css,$jsLoaderItems,$title,$output)."		") : ("")) . "
		
		<script type='text/javascript'>
		//<![CDATA[
			/* ---- URLs ---- */
			ipb.vars['base_url'] 			= '" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "", "public",'' ), "", "" ) . "';
			ipb.vars['board_url']			= '{$this->settings['board_url']}';
			ipb.vars['loading_img'] 		= '{$this->settings['img_url']}/loading.gif';
			ipb.vars['active_app']			= '{$this->registry->getCurrentApplication()}';
			ipb.vars['upload_url']			= '{$this->settings['upload_url']}';
			/* ---- Member ---- */
			ipb.vars['member_id']			= parseInt( {$this->memberData['member_id']} ),
			ipb.vars['is_supmod']			= parseInt( " . intval($this->memberData['g_is_supmod']) . " ),
			ipb.vars['is_admin']			= parseInt( {$this->memberData['g_access_cp']} ),
			ipb.vars['secure_hash'] 		= '{$this->member->form_hash}';
			ipb.vars['session_id']			= '{$this->member->session_id}';
			ipb.vars['can_befriend']		= " . (($this->settings['friends_enabled'] AND $this->memberData['g_can_add_friends']) ? ("true") : ("false")) . ";
			ipb.vars['auto_dst']			= parseInt( {$this->memberData['members_auto_dst']} );
			ipb.vars['dst_in_use']			= parseInt( {$this->memberData['dst_in_use']} );
			ipb.vars['is_touch']			= " . (($this->registry->output->isLargeTouchDevice()) ? ("'large';") : ("" . (($this->registry->output->isSmallTouchDevice()) ? ("'small';") : ("false;")) . "")) . "
			ipb.vars['member_group']		= " . json_encode( array( 'g_mem_info' => $this->memberData['g_mem_info'] ) ) . "
			/* ---- cookies ----- */
			ipb.vars['cookie_id'] 			= '{$this->settings['cookie_id']}';
			ipb.vars['cookie_domain'] 		= '{$this->settings['cookie_domain']}';
			ipb.vars['cookie_path']			= '{$this->settings['cookie_path']}';
			/* ---- Rate imgs ---- */
			ipb.vars['rate_img_on']			= '{$this->settings['img_url']}/bullet_star.png';
			ipb.vars['rate_img_off']		= '{$this->settings['img_url']}/bullet_star_off.png';
			ipb.vars['rate_img_rated']		= '{$this->settings['img_url']}/bullet_star_rated.png';
			/* ---- Uploads ---- */
			ipb.vars['swfupload_swf']		= '" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "js/3rd_party/swfupload/swfupload.swf", "public_dir",'true' ), "", "" ) . "';
			ipb.vars['swfupload_enabled']	= " . (($this->settings['uploadFormType']) ? ("true") : ("false")) . ";
			ipb.vars['use_swf_upload']		= ( '{$this->memberData['member_uploader']}' == 'flash' ) ? true : false;
			ipb.vars['swfupload_debug']		= false;
			/* ---- other ---- */
			ipb.vars['highlight_color']		= \"#ade57a\";
			ipb.vars['charset']				= \"{$this->settings['gb_char_set']}\";
			ipb.vars['use_rte']				= 1;
			ipb.vars['image_resize_force']  = " . intval($this->settings['resize_img_force']) . ";
			ipb.vars['seo_enabled']			= " . intval($this->settings['use_friendly_urls']) . ";
			" . (($this->settings['use_friendly_urls']) ? ("
			ipb.vars['seo_params']			= " . json_encode($this->registry->getClass('output')->seoTemplates['__data__']) . ";
			") : ("")) . "
			/* Templates/Language */
			ipb.templates['ajax_loading'] 	= \"<div id='ajax_loading'>\" + ipb.lang['loading'] + \"</div>\";
			ipb.templates['close_popup']	= \"<img src='{$this->settings['img_url']}/close_popup.png' alt='x' />\";
			ipb.templates['rss_shell']		= new Template(\"<ul id='rss_menu'>#{items}</ul>\");
			ipb.templates['rss_item']		= new Template(\"<li><a href='#{url}' title='#{title}'>#{title}</a></li>\");
			ipb.templates['resized_img']	= new Template(\"<span>{$this->lang->words['resized_image']}</span>\");
			" . (($this->memberData['member_id']) ? ("
				ipb.templates['m_add_friend']	= new Template(\"<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=add&amp;member_id=#{id}", "public",'' ), "", "" ) . "' title='{$this->lang->words['add_friend']}'>" . $this->registry->getClass('output')->getReplacement("add_friend") . "</a>\");
				ipb.templates['m_rem_friend']	= new Template(\"<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=friends&amp;do=remove&amp;member_id=#{id}", "public",'' ), "", "" ) . "' title='{$this->lang->words['remove_friend']}'>" . $this->registry->getClass('output')->getReplacement("remove_friend") . "</a>\");
			") : ("")) . "
			ipb.templates['autocomplete_wrap'] = new Template(\"<ul id='#{id}' class='ipb_autocomplete' style='width: 250px;'></ul>\");
			ipb.templates['autocomplete_item'] = new Template(\"<li id='#{id}' data-url='#{url}'><img src='#{img}' alt='' width='#{img_w}' height='#{img_h}' />&nbsp;&nbsp;#{itemvalue}</li>\");
			ipb.templates['page_jump']		= new Template(\"<div id='#{id}_wrap' class='ipbmenu_content'><h3 class='bar'>{$this->lang->words['global_page_jump']}</h3><input type='text' class='input_text' id='#{id}_input' size='8' /> <input type='submit' value='{$this->lang->words['jmp_go']}' class='input_submit add_folder' id='#{id}_submit' /></div>\");
			Loader.boot();
		//]]>
		</script>
	</head>
	<body id='ipboard_body' style='padding: 20px'>
		<div id='ipbwrapper'>
			{$output}
		</div>
	</body>
</html>";
return $IPBHTML;
}


function __f__2bb7719343f52dd27d6461323dbf0a92($documentHeadItems, $css, $jsLoaderItems, $title="", $output="")
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $css['import'] as $data )
	{
		
if( $this->settings['use_minify'] AND ( ! $data['attributes'] OR stripos( $data['attributes'], 'screen' ) !== false ) )
					{
						$this->minify[] = "{$data['content']}";
					}

		$__iteratorCount++;
		$_ips___x_retval .= "
								" . ((!$this->settings['use_minify'] OR ( $data['attributes'] AND stripos( $data['attributes'], 'screen' ) === false )) ? ("
					<link rel=\"stylesheet\" type=\"text/css\" {$data['attributes']} href=\"{$data['content']}?ipbv={$this->registry->output->antiCacheHash}\" />
				") : ("")) . "
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__85850b52dacfb239582dc4fe8e2c90c2($documentHeadItems, $css, $jsLoaderItems, $title="", $output="")
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $css['inline'] as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<style type=\"text/css\" {$data['attributes']}>
				/* Inline CSS */
				{$data['content']}
			</style>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__2ba6346d79ed48b093c5255b10984a66($documentHeadItems, $css, $jsLoaderItems, $title="", $output="")
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $metaTags as $tag => $content )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<meta name=\"{$tag}\" content=\"$content\" />
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__71a6e006ab9818707e25e234b8cb8c3c($documentHeadItems, $css, $jsLoaderItems, $title="", $output="",$type='',$idx='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $documentHeadItems[ $type ] as $idx => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . (($type == 'javascript') ? ("
						<script type=\"text/javascript\" src=\"{$data}\" charset=\"<% CHARSET %>\"></script>
					") : ("")) . "
					" . (($type == 'rss') ? ("
						<link rel=\"alternate feed\" type=\"application/rss+xml\" title=\"{$data['title']}\" href=\"{$data['url']}\" />
					") : ("")) . "
					" . (($type == 'rsd') ? ("
						<link rel=\"EditURI\" type=\"application/rsd+xml\" title=\"{$data['title']}\" href=\"{$data['url']}\" />
					") : ("")) . "
					" . (($type == 'raw') ? ("
						{$data}
					") : ("")) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__7dc83e20573099d616ccf05b41f57e90($documentHeadItems, $css, $jsLoaderItems, $title="", $output="")
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $documentHeadItems as $type => $idx )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				".$this->__f__71a6e006ab9818707e25e234b8cb8c3c($documentHeadItems,$css,$jsLoaderItems,$title,$output,$type,$idx)."			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- Error --*/
function Error($message="",$code=0,$ad_email_one="",$ad_email_two="", $title="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['Error'] ) )
{
$count_9343e83aaab48ed4c11be3d83987a62c = is_array($this->functionData['Error']) ? count($this->functionData['Error']) : 0;
$this->functionData['Error'][$count_9343e83aaab48ed4c11be3d83987a62c]['message'] = $message;
$this->functionData['Error'][$count_9343e83aaab48ed4c11be3d83987a62c]['code'] = $code;
$this->functionData['Error'][$count_9343e83aaab48ed4c11be3d83987a62c]['ad_email_one'] = $ad_email_one;
$this->functionData['Error'][$count_9343e83aaab48ed4c11be3d83987a62c]['ad_email_two'] = $ad_email_two;
$this->functionData['Error'][$count_9343e83aaab48ed4c11be3d83987a62c]['title'] = $title;
}
$IPBHTML .= "<script type=\"text/javascript\">
<!--
function contact_admin() {
  // Very basic spam bot stopper
  admin_email_one = '{$ad_email_one}';
  admin_email_two = '{$ad_email_two}';
  window.location = 'mailto:'+admin_email_one+'@'+admin_email_two+'?subject={$this->lang->words['mailto_erroronforums']}';  
}
//-->
</script>
<h2>{$this->lang->words['error_title']}</h2>
" . (($show_top_msg == 1) ? ("
	<p>{$this->lang->words['exp_text']}</p>
	<br />
") : ("")) . "
<div class='message error'>
	 " . (($code) ? ("[#{$code}] ") : ("")) . "{$message}
</div>
{$login}
" . (($post) ? ("
	<div class='general_box alt'>
		{$post}
	</div>
<br />
") : ("")) . "
<div class='master_list'>
<div class='general_box alt'>	
	<h3>{$this->lang->words['er_useful_links']}</h3>
	<ul class='bullets row'>
		" . ((! $this->memberData['member_id']) ? ("
			<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login", "public",'' ), "", "" ) . "' title='{$this->lang->words['submit_li']}'>{$this->lang->words['click_login']}</a></li>
		") : ("")) . "
		<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&module=help", "public",'' ), "", "" ) . "\" rel=\"help\" title='{$this->lang->words['er_help_files']}'>{$this->lang->words['er_help_files']}</a></li>
		<li><a href=\"javascript:contact_admin();\" title='{$this->lang->words['er_contact_admin']}'>{$this->lang->words['er_contact_admin']}</a></li>
	</ul>
	<p class=\"submit\">
		<strong><a href=\"javascript:history.go(-1)\">{$this->lang->words['error_back']}</a></strong>
	</p>
</div>
</div>";
return $IPBHTML;
}

/* -- facebookDone --*/
function facebookDone($user) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- facebookPop --*/
function facebookPop($user=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['facebookPop'] ) )
{
$count_a64f31414597c3a2bfd05dbc45635df5 = is_array($this->functionData['facebookPop']) ? count($this->functionData['facebookPop']) : 0;
$this->functionData['facebookPop'][$count_a64f31414597c3a2bfd05dbc45635df5]['user'] = $user;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- followUnsubscribe --*/
function followUnsubscribe($data, $meta) {
$IPBHTML = "";
$IPBHTML .= "<form action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=like&amp;do=doUnsubscribe", "public",'' ), "", "" ) . "\" method=\"post\">
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='like_rel_id' value='{$data[ $this->memberData['member_id'] ]['like_rel_id']}' />
<input type='hidden' name='like_area' value='{$data[ $this->memberData['member_id'] ]['like_area']}' />
<input type='hidden' name='like_app' value='{$data[ $this->memberData['member_id'] ]['like_app']}' />
<input type='hidden' name='like_id' value='{$data[ $this->memberData['member_id'] ]['like_id']}' />
<div class='master_list general_box alt'>	
	<h2>{$this->lang->words['pg_unfollow_title']}</h2>
	<div class=\"row\">
		<div class='rowContent'>
		" . sprintf( $this->lang->words['pg_unfollow_text'], $data[ $this->memberData['member_id'] ]['members_display_name'], $meta['like.url'], $meta['like.title'] ) . "
		<br />
		<br />
		<p>
			<input type=\"submit\" value=\"{$this->lang->words['pg_unfollow_confirm']}\" class='button' style='width:auto'>
			{$this->lang->words['or']}
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=followed", "public",'' ), "", "" ) . "' title='{$this->lang->words['cancel']}' class='cancel' tabindex='0'>{$this->lang->words['cancel']}</a>
		</p>
		</div>
	</div>
</div>
</form>";
return $IPBHTML;
}

/* -- generateTopicIcon --*/
function generateTopicIcon($imgArray, $unreadUrl) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['generateTopicIcon'] ) )
{
$count_95fdbcf13d136a76cb9f93d7757b443e = is_array($this->functionData['generateTopicIcon']) ? count($this->functionData['generateTopicIcon']) : 0;
$this->functionData['generateTopicIcon'][$count_95fdbcf13d136a76cb9f93d7757b443e]['imgArray'] = $imgArray;
$this->functionData['generateTopicIcon'][$count_95fdbcf13d136a76cb9f93d7757b443e]['unreadUrl'] = $unreadUrl;
}
$IPBHTML .= "" . (($imgArray['is_moved']) ? ("
	<span title=\"{$this->lang->words['pm_moved']}\">" . $this->registry->getClass('output')->getReplacement("t_moved") . "</span>
") : ("")) . "
" . (($imgArray['is_closed']) ? ("
	<span title=\"{$this->lang->words['pm_locked']}\">" . $this->registry->getClass('output')->getReplacement("t_closed") . "</span>
") : ("")) . "
" . (($imgArray['show_dot'] && empty( $unreadUrl )) ? ("" . $this->registry->getClass('output')->getReplacement("t_read_dot") . "") : ("")) . "
" . ((! empty( $unreadUrl ) && ! $imgArray['is_moved']) ? ("<a href='{$unreadUrl}' title='{$this->lang->words['first_unread_post']}'>
	" . (($imgArray['show_dot']) ? ("
		" . $this->registry->getClass('output')->getReplacement("t_unread_dot") . "
	") : ("
		" . $this->registry->getClass('output')->getReplacement("t_unread") . "
	")) . "
	</a>") : ("")) . "";
return $IPBHTML;
}

/* -- globalTemplateMinimal --*/
function globalTemplateMinimal($html, $documentHeadItems, $css, $jsModules, $metaTags, array $header_items, $items=array(), $footer_items=array(), $stats=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['globalTemplateMinimal'] ) )
{
$count_8a95e9196edfd5892eb53134ed6ea04c = is_array($this->functionData['globalTemplateMinimal']) ? count($this->functionData['globalTemplateMinimal']) : 0;
$this->functionData['globalTemplateMinimal'][$count_8a95e9196edfd5892eb53134ed6ea04c]['html'] = $html;
$this->functionData['globalTemplateMinimal'][$count_8a95e9196edfd5892eb53134ed6ea04c]['documentHeadItems'] = $documentHeadItems;
$this->functionData['globalTemplateMinimal'][$count_8a95e9196edfd5892eb53134ed6ea04c]['css'] = $css;
$this->functionData['globalTemplateMinimal'][$count_8a95e9196edfd5892eb53134ed6ea04c]['jsModules'] = $jsModules;
$this->functionData['globalTemplateMinimal'][$count_8a95e9196edfd5892eb53134ed6ea04c]['metaTags'] = $metaTags;
$this->functionData['globalTemplateMinimal'][$count_8a95e9196edfd5892eb53134ed6ea04c]['header_items'] = $header_items;
$this->functionData['globalTemplateMinimal'][$count_8a95e9196edfd5892eb53134ed6ea04c]['items'] = $items;
$this->functionData['globalTemplateMinimal'][$count_8a95e9196edfd5892eb53134ed6ea04c]['footer_items'] = $footer_items;
$this->functionData['globalTemplateMinimal'][$count_8a95e9196edfd5892eb53134ed6ea04c]['stats'] = $stats;
}
$IPBHTML .= "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">
	<html xml:lang=\"ru\" lang=\"ru\" xmlns=\"http://www.w3.org/1999/xhtml\"" . ((IPSLib::fbc_enabled() === TRUE) ? (" xmlns:fb=\"http://www.facebook.com/2008/fbml\"") : ("")) . ">
	<head>
		<meta http-equiv=\"content-type\" content=\"text/html; charset={$this->settings['gb_char_set']}\" />
		<title>{$header_items['title']}" . (($header_items['page']) ? (" {$this->lang->words['page_title_page']} {$header_items['page']}") : ("")) . "</title>
		<link rel=\"shortcut icon\" href='" . (($this->registry->output->isHTTPS) ? ("{$this->settings['board_url_https']}") : ("{$this->settings['board_url']}")) . "/favicon.ico' />
		
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeJS' ) ? $this->registry->getClass('output')->getTemplate('global')->includeJS($jsModules) : '' ) . "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeCSS' ) ? $this->registry->getClass('output')->getTemplate('global')->includeCSS($css) : '' ) . "
		<!--<meta http-equiv=\"X-UA-Compatible\" content=\"IE=7\" />-->
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeMeta' ) ? $this->registry->getClass('output')->getTemplate('global')->includeMeta($metaTags) : '' ) . "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeFeeds' ) ? $this->registry->getClass('output')->getTemplate('global')->includeFeeds($documentHeadItems) : '' ) . "" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeRTL' ) ? $this->registry->getClass('output')->getTemplate('global')->includeRTL() : '' ) . "
		
		<!--<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">-->
		<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\" />
		<meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1, user-scalable = no;\">
	</head>
	<body id='ipboard_body'>
		<div id='ipbwrapper'>
			" . ((count( $items['navigation'] ) > 1 && !$this->settings['_mobile_nav_home']) ? ("" . (($this->nav_count=count($items['navigation'])) ? ("") : ("")) . "" . (($this->nav_back = ( isset( $this->settings['_mobile_back_nav'] ) ) ? $this->settings['_mobile_back_nav'] : 2) ? ("") : ("")) . "
				<div id='secondary_navigation'>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$items['navigation'][ $this->nav_count - $this->nav_back ][1]}", "public",'' ), "{$items['navigation'][ $this->nav_count - $this->nav_back ][2]}", "{$items['navigation'][ $this->nav_count - $this->nav_back ][3]}" ) . "'>{$this->lang->words['_larr']} &nbsp;{$items['navigation'][ $this->nav_count - $this->nav_back ][0]}</a>
				</div>") : ("" . ((( count( $items['navigation'] ) == 1 || $this->settings['_mobile_nav_home'] ) && ! $this->settings['_mobile_hide_nav']) ? ("
					<div id='secondary_navigation'>
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "act=idx", "public",'' ), "false", "" ) . "' class='back'>{$this->lang->words['_larr']} {$this->lang->words['home']}</a>
					</div>
				") : ("")) . "")) . "
			" . ((method_exists( $this->registry->output->getTemplate( $this->registry->getCurrentApplication() . '_global' ), 'overwriteHeader' )) ? ("
				" . ( method_exists( $this->registry->getClass('output')->getTemplate(''.$this->registry->getCurrentApplication().'_global'), 'overwriteHeader' ) ? $this->registry->getClass('output')->getTemplate(''.$this->registry->getCurrentApplication().'_global')->overwriteHeader() : '' ) . "
			") : ("
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'defaultHeader' ) ? $this->registry->getClass('output')->getTemplate('global')->defaultHeader() : '' ) . "
			")) . "
			<div id=\"options-button\">&raquo;</div>	
			<div id='user_navigation'>
				" . ((!$this->memberData['member_id']) ? ("
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login", "public",'' ), "", "" ) . "' title='{$this->lang->words['sign_in']}'>{$this->lang->words['sign_in']}</a>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=register", "public",'' ), "", "" ) . "\" title='{$this->lang->words['register']}'>{$this->lang->words['register']}</a>
				") : ("<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login&amp;do=logout&amp;k={$this->member->form_hash}", "public",'' ), "", "" ) . "\">{$this->lang->words['log_out']} ({$this->memberData['members_display_name']})</a>
					" . (($this->memberData['g_use_pm'] AND $this->memberData['members_disable_pm'] == 0) ? ("
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging", "public",'' ), "", "" ) . "' title='{$this->lang->words['your_messenger']}'>{$this->lang->words['your_messenger']}</a>
					") : ("")) . "")) . "
				" . ((!ipsRegistry::$applications['members']['app_hide_tab'] && !count(ipsRegistry::$applications['members']['app_tab_groups']) && !IPSMember::isInGroup( $this->memberData, ipsRegistry::$applications['members']['app_tab_groups'] )) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members", "public",'' ), "false", "" ) . "' title='{$this->lang->words['go_to_memberlist']}'>{$this->lang->words['tb_mlist']}</a>") : ("")) . "
				" . ((ipsRegistry::$applications['blog']['app_enabled']) ? ("
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog", "public",'' ), "false", "" ) . "' title='{$this->lang->words['go_to_prefix']}" . IPSLib::getAppTitle( 'blog' ) . "'>" . IPSLib::getAppTitle( 'blog' ) . "</a>
				") : ("")) . "
				" . ((ipsRegistry::$applications['gallery']['app_enabled']) ? ("
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery", "public",'' ), "false", "" ) . "' title='{$this->lang->words['go_to_prefix']}" . IPSLib::getAppTitle( 'gallery' ) . "'>" . IPSLib::getAppTitle( 'gallery' ) . "</a>
				") : ("")) . "
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=viewNewContent&amp;search_app=" . (($this->registry->getCurrentApplication() != 'core' AND IPSLib::appIsSearchable( $this->registry->getCurrentApplication() )) ? ("{$this->registry->getCurrentApplication()}") : ("forums")) . "", "public",'' ), "", "" ) . "' accesskey='2'>{$this->lang->words['view_new_posts']}</a>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=profile&amp;section=status&amp;type=all", "public",'' ), "true", "members_status_all" ) . "'>{$this->lang->words['mob_status_updates']}</a>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search", "public",'' ), "", "" ) . "' accesskey='2'>{$this->lang->words['sj_search']}</a>
			</div>
			<script type=\"text/javascript\">
				/* Prevent flash of header */
				document.getElementById('user_navigation').style.display = 'none';
			</script>
			
			<div id='content' class='clear'>
				" . (($html) ? ("{$html}") : ("")) . "
			</div>
			
			<div id='footer' class='clear'>
				" . ((( $this->memberData['userAgentType'] != 'mobileAppLegacy' || $this->registry->output->isLargeTouchDevice() )) ? ("
					<a id='full_version' href='#'>{$this->lang->words['full_version']}</a>
				") : ("")) . "
				" . ((count( $footer_items['lang_chooser']['options'] )) ? ("
					<a href='#' id='show_langs'>{$footer_items['lang_chooser']['default']}</a>
					<div id='show_langs_box' style='display: none'>
						<form action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$this->settings['query_string_formatted']}", "public",'' ), "", "" ) . "\" method=\"post\">
							<fieldset>
								<input type='hidden' name='k' value='{$this->member->form_hash}' />
								<input type='hidden' name='setlanguage' value='1' />
								<input type=\"hidden\" name=\"langurlbits\" value=\"cal_id={$this->request['cal_id']}\" />
								<label for='newLang' class='hide'>{$this->lang->words['language_prefix']}</label>
								<select name=\"langid\" id='newLang'>
									".$this->__f__c554ba5e86ab29b732ba13f69847e19d($html,$documentHeadItems,$css,$jsModules,$metaTags,$header_items,$items,$footer_items,$stats)."								</select>
								<input type='submit' class='input_submit alt' value='{$this->lang->words['jmp_go']}' id='newLangSubmit' />
							</fieldset>
						</form>
					</div>
				") : ("")) . "
				" . ((($this->memberData['userAgentKey'] == 'iphone' || $this->memberData['userAgentKey'] == 'ipodtouch') AND ! $this->member->isMobileApp) ? ("
					<div><a href=\"http://www.invisionpower.com/download/goiphone.php\">{$this->lang->words['freeiphoneapp']}</a></div>
				") : ("")) . "
			</div>
			<div id='task'>{$stats['task']}</div>
		</div>
		<div id='shade' style='display:none'></div>
		<!-- pre-load -->
		<div style='display:none'><img src='{style_images_url}/wait.gif' /></div>
	</body>
</html>";
return $IPBHTML;
}


function __f__c554ba5e86ab29b732ba13f69847e19d($html, $documentHeadItems, $css, $jsModules, $metaTags, array $header_items, $items=array(), $footer_items=array(), $stats=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $footer_items['lang_chooser']['options'] as $lang )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
										<option value='{$lang['id']}' " . (($lang['selected']) ? ("selected='selected'") : ("")) . ">
											{$lang['title']}
										</option>
									
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- inboxList --*/
function inboxList($topics) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['inboxList'] ) )
{
$count_8d03a57e12fefc039dd6aa34948b6adb = is_array($this->functionData['inboxList']) ? count($this->functionData['inboxList']) : 0;
$this->functionData['inboxList'][$count_8d03a57e12fefc039dd6aa34948b6adb]['topics'] = $topics;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- inlineUploaderComplete --*/
function inlineUploaderComplete($json) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- likeMoreDialogue --*/
function likeMoreDialogue($data, $relId, $cache) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['likeMoreDialogue'] ) )
{
$count_1ab3561926c30e6a224e792cdcb6d7bb = is_array($this->functionData['likeMoreDialogue']) ? count($this->functionData['likeMoreDialogue']) : 0;
$this->functionData['likeMoreDialogue'][$count_1ab3561926c30e6a224e792cdcb6d7bb]['data'] = $data;
$this->functionData['likeMoreDialogue'][$count_1ab3561926c30e6a224e792cdcb6d7bb]['relId'] = $relId;
$this->functionData['likeMoreDialogue'][$count_1ab3561926c30e6a224e792cdcb6d7bb]['cache'] = $cache;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- likeSetDialogue --*/
function likeSetDialogue($app, $area, $relid, $data) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- likeSummary --*/
function likeSummary($data, $relId, $opts) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- likeSummaryContents --*/
function likeSummaryContents($data, $relId, $opts=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['likeSummaryContents'] ) )
{
$count_cd3f264cddf83013309c139988c73c6f = is_array($this->functionData['likeSummaryContents']) ? count($this->functionData['likeSummaryContents']) : 0;
$this->functionData['likeSummaryContents'][$count_cd3f264cddf83013309c139988c73c6f]['data'] = $data;
$this->functionData['likeSummaryContents'][$count_cd3f264cddf83013309c139988c73c6f]['relId'] = $relId;
$this->functionData['likeSummaryContents'][$count_cd3f264cddf83013309c139988c73c6f]['opts'] = $opts;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- notificationsList --*/
function notificationsList($notifications) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['notificationsList'] ) )
{
$count_ea3bdb0a952fbb516a9a13d74d8ad8fb = is_array($this->functionData['notificationsList']) ? count($this->functionData['notificationsList']) : 0;
$this->functionData['notificationsList'][$count_ea3bdb0a952fbb516a9a13d74d8ad8fb]['notifications'] = $notifications;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- privacyPolicy --*/
function privacyPolicy($title, $text) {
$IPBHTML = "";
$IPBHTML .= "<h2>{$title}</h2>
<div class='master_list'>
<div class='row ipsPad' style='line-height: 1.6'>
	{$text}
</div>
</div>";
return $IPBHTML;
}

/* -- questionAndAnswer --*/
function questionAndAnswer($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['questionAndAnswer'] ) )
{
$count_11c053c6e90b60a3b23e13544f75df4a = is_array($this->functionData['questionAndAnswer']) ? count($this->functionData['questionAndAnswer']) : 0;
$this->functionData['questionAndAnswer'][$count_11c053c6e90b60a3b23e13544f75df4a]['data'] = $data;
}
$IPBHTML .= "<input type=\"hidden\" name=\"qanda_id\" value=\"{$data['qa_id']}\" />
<div class='ipsField'>
	<label for='qna' class='ipsField_title'>{$data['qa_question']}</label>	
	<input type=\"text\" class='input_text' size=\"30\" maxlength=\"100\" value=\"\" name=\"qa_answer\" id='qna' tabindex='0' /><br />
	<span class='desc'>{$this->lang->words['qa_question_desc']}</span>
</div>";
return $IPBHTML;
}

/* -- quickNavigationOffline --*/
function quickNavigationOffline($message) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- quickNavigationPanel --*/
function quickNavigationPanel($data=array(), $currentApp='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['quickNavigationPanel'] ) )
{
$count_bc6442f7c1d535292d8d46f015ffd3b6 = is_array($this->functionData['quickNavigationPanel']) ? count($this->functionData['quickNavigationPanel']) : 0;
$this->functionData['quickNavigationPanel'][$count_bc6442f7c1d535292d8d46f015ffd3b6]['data'] = $data;
$this->functionData['quickNavigationPanel'][$count_bc6442f7c1d535292d8d46f015ffd3b6]['currentApp'] = $currentApp;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- quickNavigationWrapper --*/
function quickNavigationWrapper($tabs=array(), $data=array(), $currentApp='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['quickNavigationWrapper'] ) )
{
$count_3e227c107f96b0c4fd20dc8f20a62c6c = is_array($this->functionData['quickNavigationWrapper']) ? count($this->functionData['quickNavigationWrapper']) : 0;
$this->functionData['quickNavigationWrapper'][$count_3e227c107f96b0c4fd20dc8f20a62c6c]['tabs'] = $tabs;
$this->functionData['quickNavigationWrapper'][$count_3e227c107f96b0c4fd20dc8f20a62c6c]['data'] = $data;
$this->functionData['quickNavigationWrapper'][$count_3e227c107f96b0c4fd20dc8f20a62c6c]['currentApp'] = $currentApp;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- redirectTemplate --*/
function redirectTemplate($documentHeadItems, $css, $jsLoaderItems, $text="",$url="", $full=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['redirectTemplate'] ) )
{
$count_f244e61d8576401fc181acbb58bc113b = is_array($this->functionData['redirectTemplate']) ? count($this->functionData['redirectTemplate']) : 0;
$this->functionData['redirectTemplate'][$count_f244e61d8576401fc181acbb58bc113b]['documentHeadItems'] = $documentHeadItems;
$this->functionData['redirectTemplate'][$count_f244e61d8576401fc181acbb58bc113b]['css'] = $css;
$this->functionData['redirectTemplate'][$count_f244e61d8576401fc181acbb58bc113b]['jsLoaderItems'] = $jsLoaderItems;
$this->functionData['redirectTemplate'][$count_f244e61d8576401fc181acbb58bc113b]['text'] = $text;
$this->functionData['redirectTemplate'][$count_f244e61d8576401fc181acbb58bc113b]['url'] = $url;
$this->functionData['redirectTemplate'][$count_f244e61d8576401fc181acbb58bc113b]['full'] = $full;
}
$IPBHTML .= "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"> 
<html xml:lang=\"ru\" lang=\"ru\" xmlns=\"http://www.w3.org/1999/xhtml\"> 
	<head>
	    <meta http-equiv=\"content-type\" content=\"text/html; charset=<% CHARSET %>\" /> 
		<title>{$this->lang->words['stand_by']}</title>
		" . (($full==true) ? ("
			<meta http-equiv=\"refresh\" content=\"2; url=" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "$url", "none",'' ), "", "" ) . "\" />
		") : ("
			<meta http-equiv=\"refresh\" content=\"2; url=" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "$url", "public",'' ), "", "" ) . "\" />
		")) . "
		<link rel=\"shortcut icon\" href='" . (($this->registry->output->isHTTPS) ? ("{$this->settings['board_url_https']}") : ("{$this->settings['board_url']}")) . "/favicon.ico' />
		" . ((is_array( $css['import'] )) ? ("
			".$this->__f__a7a1c3b709c764ed8a6a3bbb0ed94fbd($documentHeadItems,$css,$jsLoaderItems,$text,$url,$full)."		") : ("")) . "
		" . ((is_array( $css['inline'] ) AND count( $css['inline'] )) ? ("
			".$this->__f__c17b3a276a36cd15ee0316ee478b2501($documentHeadItems,$css,$jsLoaderItems,$text,$url,$full)."		") : ("")) . "
		<!--[if lte IE 7]>
			<link rel=\"stylesheet\" type=\"text/css\" title='Main' media=\"screen\" href=\"{$this->settings['public_dir']}style_css/{$this->registry->output->skin['_csscacheid']}/ipb_ie.css\" />
		<![endif]-->
		
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'includeRTL' ) ? $this->registry->getClass('output')->getTemplate('global')->includeRTL() : '' ) . "	
		<script type='text/javascript'>
			jsDebug		= 0; /* Must come before JS includes */
			var isRTL	= false;
			var rtlIe	= '';
			var rtlFull	= '';
		</script>
		" . ((count($documentHeadItems)) ? ("
			".$this->__f__68047a05fd750362d1b09463709c1364($documentHeadItems,$css,$jsLoaderItems,$text,$url,$full)."		") : ("")) . "
		<!--/CSS-->
		<script type='text/javascript'>
		//<![CDATA[
		// Fix Mozilla bug: 209020
		if ( navigator.product == 'Gecko' )
		{
			navstring = navigator.userAgent.toLowerCase();
			geckonum  = navstring.replace( /.*gecko\\/(\\d+)/, \"$1\" );
			setTimeout(\"moz_redirect()\",1500);
		}
		function moz_redirect()
		{
			" . (($full==true) ? ("
				var url_bit     = \"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "$url", "none",'' ), "", "" ) . "\";
			") : ("
				var url_bit     = \"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "$url", "public",'' ), "", "" ) . "\";
			")) . "
			window.location = url_bit.replace( new RegExp( \"&amp;\", \"g\" ) , '&' );
		}
		//>
		</script>
	</head>
	<body  id='ipboard_body' class='redirector'>
		<div id='ipbredirectwrapper'>
			<p class='message'>
				<strong>{$text}</strong>
				<br /><br />
				{$this->lang->words['transfer_you']}
				<br />
				<span class='desc'>(<a href=\"" . (($full==true) ? ("" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$url}", "none",'' ), "", "" ) . "") : ("" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$url}", "public",'' ), "", "" ) . "")) . "\">{$this->lang->words['dont_wait']}</a>)</span>	
			</p>
		</div>
	</body>
</html>";
return $IPBHTML;
}


function __f__a7a1c3b709c764ed8a6a3bbb0ed94fbd($documentHeadItems, $css, $jsLoaderItems, $text="",$url="", $full=false)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $css['import'] as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<link rel=\"stylesheet\" type=\"text/css\" {$data['attributes']} href=\"{$data['content']}\">
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__c17b3a276a36cd15ee0316ee478b2501($documentHeadItems, $css, $jsLoaderItems, $text="",$url="", $full=false)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $css['inline'] as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<style type=\"text/css\" {$data['attributes']}>
					/* Inline CSS */
					{$data['content']}
				</style>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__871ac9bf4ca7fe9c49b4dec3d8ff13fe($documentHeadItems, $css, $jsLoaderItems, $text="",$url="", $full=false,$type='',$idx='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $documentHeadItems[ $type ] as $idx => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . (($type == 'javascript') ? ("
						<script type=\"text/javascript\" src=\"{$data}\" charset=\"<% CHARSET %>\"></script>
					") : ("")) . "
					" . (($type == 'rss') ? ("
						<link rel=\"alternate\" type=\"application/rss+xml\" title=\"{$data['title']}\" href=\"{$data['url']}\" />
					") : ("")) . "
					" . (($type == 'rsd') ? ("
						<link rel=\"EditURI\" type=\"application/rsd+xml\" title=\"{$data['title']}\" href=\"{$data['url']}\" />
					") : ("")) . "
					" . (($type == 'raw') ? ("
						$data
					") : ("")) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__68047a05fd750362d1b09463709c1364($documentHeadItems, $css, $jsLoaderItems, $text="",$url="", $full=false)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $documentHeadItems as $type => $idx )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				".$this->__f__871ac9bf4ca7fe9c49b4dec3d8ff13fe($documentHeadItems,$css,$jsLoaderItems,$text,$url,$full,$type,$idx)."			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- repButtons --*/
function repButtons($member, $data=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['repButtons'] ) )
{
$count_81c52cca41dc78290d1ac8f33f0b09b3 = is_array($this->functionData['repButtons']) ? count($this->functionData['repButtons']) : 0;
$this->functionData['repButtons'][$count_81c52cca41dc78290d1ac8f33f0b09b3]['member'] = $member;
$this->functionData['repButtons'][$count_81c52cca41dc78290d1ac8f33f0b09b3]['data'] = $data;
}
$IPBHTML .= "" . (($this->settings['reputation_enabled']) ? ("" . ((!( $this->settings['reputation_protected_groups'] && in_array( $member['member_group_id'], explode( ',', $this->settings['reputation_protected_groups'] ) ) )) ? ("" . (($this->settings['reputation_point_types'] == 'like') ? ("<ul class='ipsList_inline post_rep'>
				<li " . ((IPSMember::canRepUp( $data, $member ) === false) ? ("style=\"display:none\"") : ("")) . " >
					<a class='ipsLikeButton ipsLikeButton_enabled rep_up' href='{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}' title='{$this->lang->words['reputation_up']}'>{$this->lang->words['like_this']}</a>
				</li>
				<li " . ((IPSMember::canRepDown( $data, $member ) === false) ? ("style=\"display:none\"") : ("")) . " >
					<a class='ipsLikeButton ipsLikeButton_disabled rep_down'  href='{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=-1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}' title='{$this->lang->words['reputation_down']}'>{$this->lang->words['unlike_this']}</a>
				</li>
			</ul>") : ("<ul class='ipsList_inline post_rep'>
				" . ((IPSMember::canGiveRep( $data, $member ) !== false) ? ("<li " . ((IPSMember::canRepUp( $data, $member ) === false) ? ("style=\"display:none\"") : ("")) . ">
						<a href='{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}' class='rep_up' title='{$this->lang->words['reputation_up']}'>" . $this->registry->getClass('output')->getReplacement("rep_up") . "</a>
					</li>
					<li " . ((IPSMember::canRepDown( $data, $member ) === false) ? ("style=\"display:none\"") : ("")) . ">
						<a href='{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=-1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}' class='rep_down' title='{$this->lang->words['reputation_down']}'>" . $this->registry->getClass('output')->getReplacement("rep_down") . "</a>
					</li>") : ("")) . "
			</ul>")) . "") : ("")) . "") : ("")) . "";
return $IPBHTML;
}

/* -- repMoreDialogue --*/
function repMoreDialogue($data, $relId) {
$IPBHTML = "";
$IPBHTML .= "<h3>{$this->lang->words['liked_by_title']}</h3>
<div class='likepop fixed_inner'>
	<ul class='ipsList_withminiphoto'>
		".$this->__f__531ad58ac788f9b4915846a2b8496dfa($data,$relId)."	</ul>
</div>";
return $IPBHTML;
}


function __f__531ad58ac788f9b4915846a2b8496dfa($data, $relId)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data as $mid => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li class='clearfix ipsPad_half " . (($data['like_is_anon']) ? ("faded") : ("")) . "'>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$data['member_id']}", "public",'' ), "{$data['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' class='ipsUserPhotoLink left'>
					<img src='{$data['pp_small_photo']}' class='ipsUserPhoto ipsUserPhoto_mini' />
				</a>
				<div class='list_content'>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$data['member_id']}", "public",'' ), "{$data['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'><strong>{$data['members_display_name']}</strong></a>
					<em class='desc'>{$this->lang->words['likeadded']} " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($data['rep_date'],"short", 0)) . "</em>
					<p class='desc'>
						" . IPSMember::makeNameFormatted( $data['g_title'], $data['g_id'] ) . "
					</p>
				</div>
			</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- reputationPopup --*/
function reputationPopup($reps) {
$IPBHTML = "";
$IPBHTML .= "<div>
	<h3>{$this->lang->words['rep_given']}</h3>
	<div class='ipsPad' style='min-height: 60px'>
		" . ((empty($reps)) ? ("
			<em>{$this->lang->words['no_rep']}</em>
		") : ("".$this->__f__22c3a8bb16a8bb61f528c781d29b0f47($reps)."		")) . "
	</div>
</div>";
return $IPBHTML;
}


function __f__22c3a8bb16a8bb61f528c781d29b0f47($reps)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $reps as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				" . (($r['rep_rating'] > 0) ? ("
					" . $this->registry->getClass('output')->getReplacement("rep_up") . "
				") : ("
					" . $this->registry->getClass('output')->getReplacement("rep_down") . "
				")) . "
				 <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member']['member_id']}", "public",'' ), "{$r['member']['members_seo_name']}", "showuser" ) . "'>{$r['member']['members_display_name']}</a><br />
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- socialSharePostStrip --*/
function socialSharePostStrip($id=null) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['socialSharePostStrip'] ) )
{
$count_1916677b67c876637e73b8f8e5fa7d69 = is_array($this->functionData['socialSharePostStrip']) ? count($this->functionData['socialSharePostStrip']) : 0;
$this->functionData['socialSharePostStrip'][$count_1916677b67c876637e73b8f8e5fa7d69]['id'] = $id;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- tagCloud --*/
function tagCloud($tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagCloud'] ) )
{
$count_251a7aa0ef01521f5df519a52602086f = is_array($this->functionData['tagCloud']) ? count($this->functionData['tagCloud']) : 0;
$this->functionData['tagCloud'][$count_251a7aa0ef01521f5df519a52602086f]['tags'] = $tags;
}
$IPBHTML .= "<h3 class='maintitle'>{$this->lang->words['mob_tags']}</h3>
<div class='ipsBox'>
	<div class='ipsBox_container ipsPad'>
		<ul class='ipsList_inline'>
		".$this->__f__71649e7d618142d7aff378a5d9e529e3($tags)."		</ul>
	</div>
</div>";
return $IPBHTML;
}


function __f__71649e7d618142d7aff378a5d9e529e3($tags)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $tags['tags'] as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li><span class=\"{$data['className']}\">{$data['tagWithUrl']}</span></li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- tagEntry --*/
function tagEntry($tag, $noClass=false, $app='all', $section='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagEntry'] ) )
{
$count_56baef24c57733f3a2a684094f905e10 = is_array($this->functionData['tagEntry']) ? count($this->functionData['tagEntry']) : 0;
$this->functionData['tagEntry'][$count_56baef24c57733f3a2a684094f905e10]['tag'] = $tag;
$this->functionData['tagEntry'][$count_56baef24c57733f3a2a684094f905e10]['noClass'] = $noClass;
$this->functionData['tagEntry'][$count_56baef24c57733f3a2a684094f905e10]['app'] = $app;
$this->functionData['tagEntry'][$count_56baef24c57733f3a2a684094f905e10]['section'] = $section;
}
$IPBHTML .= "<a " . ((!$noClass) ? ("class='ipsTag'") : ("")) . " href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=search&amp;search_tags=" . IPSText::urlencode_furlSafe($tag) . "&amp;search_app=" . ((isset($this->request['search_app']) AND $this->request['search_app']) ? ("{$this->request['search_app']}") : ("{$app}")) . "" . (($section) ? ("&amp;search_app_filters[" . ((isset($this->request['search_app']) AND $this->request['search_app']) ? ("{$this->request['search_app']}") : ("{$app}")) . "][searchInKey]={$section}") : ("")) . "", "public",'' ), "false", "tags" ) . "\" data-tooltip=\"" . sprintf( $this->lang->words['find_more_tags'], $tag ) . "\"><span>{$tag}</span></a>";
return $IPBHTML;
}

/* -- tagPrefix --*/
function tagPrefix($tag, $app='', $section='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagPrefix'] ) )
{
$count_e37fe45545ca705a3013bddc7ae58f67 = is_array($this->functionData['tagPrefix']) ? count($this->functionData['tagPrefix']) : 0;
$this->functionData['tagPrefix'][$count_e37fe45545ca705a3013bddc7ae58f67]['tag'] = $tag;
$this->functionData['tagPrefix'][$count_e37fe45545ca705a3013bddc7ae58f67]['app'] = $app;
$this->functionData['tagPrefix'][$count_e37fe45545ca705a3013bddc7ae58f67]['section'] = $section;
}
$IPBHTML .= "<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=search&amp;search_tags=" . urlencode($tag) . "&amp;search_app=" . ((isset($this->request['search_app']) AND $this->request['search_app']) ? ("{$this->request['search_app']}") : ("{$app}")) . "" . (($section) ? ("&amp;search_app_filters[" . ((isset($this->request['search_app']) AND $this->request['search_app']) ? ("{$this->request['search_app']}") : ("{$app}")) . "][searchInKey]={$section}") : ("")) . "", "public",'' ), "false", "tags" ) . "\" class='ipsBadge ipsBadge_lightgrey' data-tooltip=\"" . sprintf( $this->lang->words['find_more_tags'], $tag ) . "\">{$tag}</a>";
return $IPBHTML;
}

/* -- tagsAsPopUp --*/
function tagsAsPopUp($tags) {
$IPBHTML = "";
$IPBHTML .= "<div class='ipsBox'>
	<div class='ipsBox_container ipsPad'>
		{$tags['formatted']['parsedWithoutComma']}
	</div>
</div>";
return $IPBHTML;
}

/* -- tagTextEntryBox --*/
function tagTextEntryBox($tags, $options, $where) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagTextEntryBox'] ) )
{
$count_b98c013fd890949ad23d84f9b6f00a59 = is_array($this->functionData['tagTextEntryBox']) ? count($this->functionData['tagTextEntryBox']) : 0;
$this->functionData['tagTextEntryBox'][$count_b98c013fd890949ad23d84f9b6f00a59]['tags'] = $tags;
$this->functionData['tagTextEntryBox'][$count_b98c013fd890949ad23d84f9b6f00a59]['options'] = $options;
$this->functionData['tagTextEntryBox'][$count_b98c013fd890949ad23d84f9b6f00a59]['where'] = $where;
}

$options['lang']['tag_add_link']	= $this->lang->words['add_a_tag'];
	$options['lang']['tip_text']		= $this->lang->words['tag_tip'];
	$options['forceLowercase']			= $this->settings['tags_force_lower'];
	$options['existingTags']			= count($tags['tags']) ? $tags['tags'] : null;
	
	$_tmp = $options;
	
	/* Always return as UTF-8 */
	$jsonEncoded = IPSText::jsonEncodeForTemplate( $_tmp );
$IPBHTML .= "<script type='text/javascript' src=\"{$this->settings['public_dir']}js/ips.tags.mobile.js\"></script>
<a href='#' id='{$options['fieldId']}_tag_button' class='ipsTagBox_launcher'>{$this->lang->words['mob_edit_tags']}</a>
<div class='ipsFilterPane' id='{$options['fieldId']}_tag_pane' style='display: none'>
	<a href='#' id='{$options['fieldId']}_close_pane' class='ipsFilterPane_close'><span>&times;</span></a>
	<div>
		<h4>{$this->lang->words['topictagsh4']}</h4>
		" . ((!$options['minTags'] && $options['maxTags']) ? ("
			<h5>" . sprintf( $this->lang->words['tags_max_no_min'], $options['maxTags'] ) . "</h5>
		") : ("")) . "" . (($options['minTags'] && !$options['maxTags']) ? ("
			<h5>" . sprintf( $this->lang->words['tags_min_no_max'], $options['minTags'] ) . "</h5>
		") : ("")) . "" . (($options['minTags'] && $options['maxTags']) ? ("
			<h5>" . sprintf( $this->lang->words['tags_max_and_min'], $options['minTags'], $options['maxTags'] ) . "</h5>
		") : ("")) . "
		<div class='ipsFilterPane_inner'>
			<div class='ipsTagBox'>
				<ul id='{$options['fieldId']}_tags' class='ipsTagBox_taglist'></ul>
			</div>
			<div class='ipsTagBox_editor'>
				<span id='{$options['fieldId']}_addwrap'>
					" . ((!$options['isOpenSystem']) ? ("<select id='{$options['fieldId']}_tag_select' class='input_select'>
							" . ((!empty( $options['predefinedTags'] )) ? ("".$this->__f__a8038ec259299c32abbd0c36cfdfbf1f($tags,$options,$where)."							") : ("")) . "
						</select>") : ("
						<input type='text' id='{$options['fieldId']}_tag_input' class='input_text' />
					")) . " <input type='submit' value='{$this->lang->words['mob_add_tag']}' class='input_submit' id='{$options['fieldId']}_tag_add' />
				</span>
				<span id='{$options['fieldId']}_removewrap' style='display: none'>
					<input type='submit' value='{$this->lang->words['mob_remove_tag']}' id='{$options['fieldId']}_tag_remove' class='input_submit ipsTagBox_remove' />
				</span>
			</div>
		</div>
	</div>
</div>
<input type=\"text\" value=\"\" name=\"{$options['fieldId']}\" id=\"{$options['fieldId']}\" style='display: none' /><script type=\"text/javascript\">
	$( \"{$options['fieldId']}\" ).mobileTagify( {$jsonEncoded} );
</script>";
return $IPBHTML;
}


function __f__a8038ec259299c32abbd0c36cfdfbf1f($tags, $options, $where)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $options['predefinedTags'] as $tag )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
									<option value=\"$tag\">{$tag}</option>
								
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- twitterDone --*/
function twitterDone($user) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- twitterPop --*/
function twitterPop($user) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>