<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 27 Sep 2015 13:40:54 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_global_comments_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['comment'] = array('canEditNoPost','commentQueued','authorwarn','userIgnoredLang','hasauthormemid','hasauthormidclose','commentignored','moderateCheckbox','enableRep','hasQ','canReply','canEdit','canHide','canApprove','canDelete','hasReport','commentinitignored');
$this->_funcHooks['commentHidden'] = array('canEditNoPost','moderateCheckbox','canUnhide','canDelete');
$this->_funcHooks['commentsList'] = array('comments','comments_top','comments_bottom','hasCaptcha','guestName','allow_comments');
$this->_funcHooks['form'] = array('comment_errors','isEditing','guest_captcha');


}

/* -- comment --*/
function comment($r, $parent, $settings) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['comment'] ) )
{
$count_3c6b5b8c3c440b3e12de2fdda3383515 = is_array($this->functionData['comment']) ? count($this->functionData['comment']) : 0;
$this->functionData['comment'][$count_3c6b5b8c3c440b3e12de2fdda3383515]['r'] = $r;
$this->functionData['comment'][$count_3c6b5b8c3c440b3e12de2fdda3383515]['parent'] = $parent;
$this->functionData['comment'][$count_3c6b5b8c3c440b3e12de2fdda3383515]['settings'] = $settings;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- commentHidden --*/
function commentHidden($r, $parent, $settings) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['commentHidden'] ) )
{
$count_71d6d914b54857b8882f5287087ae552 = is_array($this->functionData['commentHidden']) ? count($this->functionData['commentHidden']) : 0;
$this->functionData['commentHidden'][$count_71d6d914b54857b8882f5287087ae552]['r'] = $r;
$this->functionData['commentHidden'][$count_71d6d914b54857b8882f5287087ae552]['parent'] = $parent;
$this->functionData['commentHidden'][$count_71d6d914b54857b8882f5287087ae552]['settings'] = $settings;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- commentsList --*/
function commentsList($comments, $settings, $pages, $parent, $preReply='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['commentsList'] ) )
{
$count_2ae85492b94dda5fca2446d2fbcf9c4c = is_array($this->functionData['commentsList']) ? count($this->functionData['commentsList']) : 0;
$this->functionData['commentsList'][$count_2ae85492b94dda5fca2446d2fbcf9c4c]['comments'] = $comments;
$this->functionData['commentsList'][$count_2ae85492b94dda5fca2446d2fbcf9c4c]['settings'] = $settings;
$this->functionData['commentsList'][$count_2ae85492b94dda5fca2446d2fbcf9c4c]['pages'] = $pages;
$this->functionData['commentsList'][$count_2ae85492b94dda5fca2446d2fbcf9c4c]['parent'] = $parent;
$this->functionData['commentsList'][$count_2ae85492b94dda5fca2446d2fbcf9c4c]['preReply'] = $preReply;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- form --*/
function form($comment, $parent, $editor="", $settings, $errors="", $do='saveEdit') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['form'] ) )
{
$count_cb14e139daa795bade0bac7a2c977032 = is_array($this->functionData['form']) ? count($this->functionData['form']) : 0;
$this->functionData['form'][$count_cb14e139daa795bade0bac7a2c977032]['comment'] = $comment;
$this->functionData['form'][$count_cb14e139daa795bade0bac7a2c977032]['parent'] = $parent;
$this->functionData['form'][$count_cb14e139daa795bade0bac7a2c977032]['editor'] = $editor;
$this->functionData['form'][$count_cb14e139daa795bade0bac7a2c977032]['settings'] = $settings;
$this->functionData['form'][$count_cb14e139daa795bade0bac7a2c977032]['errors'] = $errors;
$this->functionData['form'][$count_cb14e139daa795bade0bac7a2c977032]['do'] = $do;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- getEditJs --*/
function getEditJs() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>