<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 27 Sep 2015 13:40:54 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_search_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['asForumPosts'] = array('notLastFtAsForum','topicsForumTrail','moderated','postMid','postModSelected','postModCheckbox','postMember','hasForumTrail');
$this->_funcHooks['asForumTopics'] = array('notLastFtAsForum','topicsForumTrail','haslastpage','pages','archivedBadge','hasPrefix','resultIsPostTR','isNewPostTR','hasTags','multipages','bothSearchUnderTitle','isFollowedStuff','replylang','bothSearch','forumsDigests','isArchivedCb','isAdmin','isFollowedStuff','notLastFtAsForum','topicsForumTrail','resultIsPostAsForum','isNewPostAsForum');
$this->_funcHooks['followData'] = array('hasFrequence','isAnonymous');
$this->_funcHooks['followedContentForumsWrapper'] = array('NCresultsAsForum');
$this->_funcHooks['followedContentForumsWrapperForums'] = array('showSubForumsLit','subforums','showSubForums','isFollowedStuff','hasphoto','lastPosterID','hideDateUrl','hasLastTopicId','hideLastInfo','forumsDigests','NCresultsAsForum');
$this->_funcHooks['followedContentView'] = array('appIsSearched','supportsLikes','apps','hasconfirm','haslikeserror','forumsTab','memberFollow','membersTab','memberFollow','searchedApp','forumsDigests','hasLikeForMod','NPTotal');
$this->_funcHooks['forumAdvancedSearchFilters'] = array('hasArchives');
$this->_funcHooks['forumsVncFilters'] = array('hasFiltersSet','depth','hasFiltersSet','hasTitle','forumlist','noFiltersSet','noFiltersSet');
$this->_funcHooks['helpSearchResult'] = array('showHelpContent');
$this->_funcHooks['memberCommentsSearchResult'] = array('isUpdate','hasMore','maxReplies');
$this->_funcHooks['newContentView'] = array('appIsSearched','appIsSearchable','apps','forumsTab','membersTab','helpTab','hazVNC','hazMember','checked','userModeAll','userModeTitle','hasFilters','vncFilterForumsOnly','canFollowFilter','searchismod','NPTotal');
$this->_funcHooks['searchAdvancedForm'] = array('appLoop','calendarlocale','searchTermsRemoved','searchError','isFullText','tagyouareit');
$this->_funcHooks['searchResults'] = array('subResult','results','hasResults','subResult','results');
$this->_funcHooks['searchResultsAsForum'] = array('NCresultsAsForum','asTawpiks','asPostsStart','asPostsEnd','isAdminBottom','isAdmin','disablelightbox','asTawpiks2');
$this->_funcHooks['searchResultsWrapper'] = array('appIsSearched','appIsSearchable','apps','hasSearchResultsCut','hasSearchResultsTags','hasSearchResults','forumsTab','membersTab','helpTab','searchismod','noResultsTerm','hasTotal');
$this->_funcHooks['searchRowGenericFormat'] = array('showGenericContent','isUpdated','hasMemberId','isUpdatedOrHasMemberId');
$this->_funcHooks['topicPostSearchResultAsForum'] = array('whichWayToGo');
$this->_funcHooks['userPostsView'] = array('appIsSearched','appIsSearchable','apps','NPhasResults','forumsTab','membersTab','helpTab','searchismod','NPTotal');


}

/* -- asForumPosts --*/
function asForumPosts($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['asForumPosts'] ) )
{
$count_a6ed6bb63c2fa8fbcc61f23f9992ca27 = is_array($this->functionData['asForumPosts']) ? count($this->functionData['asForumPosts']) : 0;
$this->functionData['asForumPosts'][$count_a6ed6bb63c2fa8fbcc61f23f9992ca27]['data'] = $data;
}
$IPBHTML .= "<template>searchResultsAsPost</template>
<searchResults>
</searchResults>";
return $IPBHTML;
}

/* -- asForumTopics --*/
function asForumTopics($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['asForumTopics'] ) )
{
$count_3a88aa014261fbe407010896a8f07206 = is_array($this->functionData['asForumTopics']) ? count($this->functionData['asForumTopics']) : 0;
$this->functionData['asForumTopics'][$count_3a88aa014261fbe407010896a8f07206]['data'] = $data;
}
$IPBHTML .= "<searchResult>
	<tid>{$data['tid']}</tid>
	<title>{$data['_shortTitle']}</title>
	<state>{$data['state']}</state>
	<url>" . (($data['_unreadUrl']) ? ("{$data['_unreadUrl']}") : ("" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['type_id_2']}&amp;view=" . (($this->request['do']=='new_posts' OR $this->request['do']=='active') ? ("getnewpost") : ("" . (($data['misc']) ? ("findpost&amp;p={$data['misc']}") : ("")) . "")) . "&amp;hl={$this->request['search_higlight']}&amp;fromsearch=1", "public",'' ), "{$data['title_seo']}", "showtopic" ) . "")) . "</url>
	<isRead>" . (($data['_isRead'] == 1) ? ("1") : ("0")) . "</isRead>
	<authorid>{$data['author_id']}</authorid>
	<author>{$data['author_name']}</author>
	".$this->__f__8a14a2bea1d8e0ae16c33847c204a0e3($data)."</searchResult>";
return $IPBHTML;
}


function __f__8a14a2bea1d8e0ae16c33847c204a0e3($data)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data['_forum_trail'] as $i => $f )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "" . (($i+1 == count( $data['_forum_trail'] )) ? ("<forum>{$f[0]}</forum>") : ("")) . "
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- followData --*/
function followData($followData) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followData'] ) )
{
$count_a31ec61c8d4eb4c36bc6a724d6e26034 = is_array($this->functionData['followData']) ? count($this->functionData['followData']) : 0;
$this->functionData['followData'][$count_a31ec61c8d4eb4c36bc6a724d6e26034]['followData'] = $followData;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentForumsWrapper --*/
function followedContentForumsWrapper($results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followedContentForumsWrapper'] ) )
{
$count_970022a999e54cf4551473a245fca359 = is_array($this->functionData['followedContentForumsWrapper']) ? count($this->functionData['followedContentForumsWrapper']) : 0;
$this->functionData['followedContentForumsWrapper'][$count_970022a999e54cf4551473a245fca359]['results'] = $results;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentForumsWrapperForums --*/
function followedContentForumsWrapperForums($results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followedContentForumsWrapperForums'] ) )
{
$count_ce4b898cd7182b26ad7d66eb290d725d = is_array($this->functionData['followedContentForumsWrapperForums']) ? count($this->functionData['followedContentForumsWrapperForums']) : 0;
$this->functionData['followedContentForumsWrapperForums'][$count_ce4b898cd7182b26ad7d66eb290d725d]['results'] = $results;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentView --*/
function followedContentView($results, $pagination, $total, $error, $contentTypes) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followedContentView'] ) )
{
$count_903b61971d5e9fad321fba97cc0c5f81 = is_array($this->functionData['followedContentView']) ? count($this->functionData['followedContentView']) : 0;
$this->functionData['followedContentView'][$count_903b61971d5e9fad321fba97cc0c5f81]['results'] = $results;
$this->functionData['followedContentView'][$count_903b61971d5e9fad321fba97cc0c5f81]['pagination'] = $pagination;
$this->functionData['followedContentView'][$count_903b61971d5e9fad321fba97cc0c5f81]['total'] = $total;
$this->functionData['followedContentView'][$count_903b61971d5e9fad321fba97cc0c5f81]['error'] = $error;
$this->functionData['followedContentView'][$count_903b61971d5e9fad321fba97cc0c5f81]['contentTypes'] = $contentTypes;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumAdvancedSearchFilters --*/
function forumAdvancedSearchFilters($forums, $archivedPostCount=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['forumAdvancedSearchFilters'] ) )
{
$count_5efc628fea6bd688c9fcce59c255ff24 = is_array($this->functionData['forumAdvancedSearchFilters']) ? count($this->functionData['forumAdvancedSearchFilters']) : 0;
$this->functionData['forumAdvancedSearchFilters'][$count_5efc628fea6bd688c9fcce59c255ff24]['forums'] = $forums;
$this->functionData['forumAdvancedSearchFilters'][$count_5efc628fea6bd688c9fcce59c255ff24]['archivedPostCount'] = $archivedPostCount;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumsVncFilters --*/
function forumsVncFilters($data, $currentPrefs) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['forumsVncFilters'] ) )
{
$count_b43935ab5c354cf5cd88b796495dcb42 = is_array($this->functionData['forumsVncFilters']) ? count($this->functionData['forumsVncFilters']) : 0;
$this->functionData['forumsVncFilters'][$count_b43935ab5c354cf5cd88b796495dcb42]['data'] = $data;
$this->functionData['forumsVncFilters'][$count_b43935ab5c354cf5cd88b796495dcb42]['currentPrefs'] = $currentPrefs;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- helpSearchResult --*/
function helpSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['helpSearchResult'] ) )
{
$count_3fe6d34717b8c2a60d418afa47d45cf4 = is_array($this->functionData['helpSearchResult']) ? count($this->functionData['helpSearchResult']) : 0;
$this->functionData['helpSearchResult'][$count_3fe6d34717b8c2a60d418afa47d45cf4]['r'] = $r;
$this->functionData['helpSearchResult'][$count_3fe6d34717b8c2a60d418afa47d45cf4]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberCommentsSearchResult --*/
function memberCommentsSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['memberCommentsSearchResult'] ) )
{
$count_fd99fda701834a9de30de53a0d13fffc = is_array($this->functionData['memberCommentsSearchResult']) ? count($this->functionData['memberCommentsSearchResult']) : 0;
$this->functionData['memberCommentsSearchResult'][$count_fd99fda701834a9de30de53a0d13fffc]['r'] = $r;
$this->functionData['memberCommentsSearchResult'][$count_fd99fda701834a9de30de53a0d13fffc]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberSearchResult --*/
function memberSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- newContentView --*/
function newContentView($results, $pagination, $total, $sortDropDown, $sortIn, $dateCutSet=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['newContentView'] ) )
{
$count_35f1fa2211a22af7888eb2b265ffcf9f = is_array($this->functionData['newContentView']) ? count($this->functionData['newContentView']) : 0;
$this->functionData['newContentView'][$count_35f1fa2211a22af7888eb2b265ffcf9f]['results'] = $results;
$this->functionData['newContentView'][$count_35f1fa2211a22af7888eb2b265ffcf9f]['pagination'] = $pagination;
$this->functionData['newContentView'][$count_35f1fa2211a22af7888eb2b265ffcf9f]['total'] = $total;
$this->functionData['newContentView'][$count_35f1fa2211a22af7888eb2b265ffcf9f]['sortDropDown'] = $sortDropDown;
$this->functionData['newContentView'][$count_35f1fa2211a22af7888eb2b265ffcf9f]['sortIn'] = $sortIn;
$this->functionData['newContentView'][$count_35f1fa2211a22af7888eb2b265ffcf9f]['dateCutSet'] = $dateCutSet;
}
$IPBHTML .= "{$results}";
return $IPBHTML;
}

/* -- searchAdvancedForm --*/
function searchAdvancedForm($filters='', $msg='', $current_app, $removed_search_terms=array(), $isFT=false, $canTag=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchAdvancedForm'] ) )
{
$count_6219e04baa299a418c1c46865b5f9836 = is_array($this->functionData['searchAdvancedForm']) ? count($this->functionData['searchAdvancedForm']) : 0;
$this->functionData['searchAdvancedForm'][$count_6219e04baa299a418c1c46865b5f9836]['filters'] = $filters;
$this->functionData['searchAdvancedForm'][$count_6219e04baa299a418c1c46865b5f9836]['msg'] = $msg;
$this->functionData['searchAdvancedForm'][$count_6219e04baa299a418c1c46865b5f9836]['current_app'] = $current_app;
$this->functionData['searchAdvancedForm'][$count_6219e04baa299a418c1c46865b5f9836]['removed_search_terms'] = $removed_search_terms;
$this->functionData['searchAdvancedForm'][$count_6219e04baa299a418c1c46865b5f9836]['isFT'] = $isFT;
$this->functionData['searchAdvancedForm'][$count_6219e04baa299a418c1c46865b5f9836]['canTag'] = $canTag;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- searchResults --*/
function searchResults($results, $titlesOnly) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchResults'] ) )
{
$count_d5d939f7a03ddf62ddcfe62fd2621b08 = is_array($this->functionData['searchResults']) ? count($this->functionData['searchResults']) : 0;
$this->functionData['searchResults'][$count_d5d939f7a03ddf62ddcfe62fd2621b08]['results'] = $results;
$this->functionData['searchResults'][$count_d5d939f7a03ddf62ddcfe62fd2621b08]['titlesOnly'] = $titlesOnly;
}
$IPBHTML .= "" . ((is_array( $results )) ? ("".$this->__f__9f165bbf27fd211646a614433f80f5da($results,$titlesOnly)."		") : ("")) . "";
return $IPBHTML;
}


function __f__9f165bbf27fd211646a614433f80f5da($results, $titlesOnly)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $results as $result )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . (($result['sub']) ? ("
					{$result['html']}
				
			") : ("
					{$result['html']}
				
			")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- searchResultsAsForum --*/
function searchResultsAsForum($results, $titlesOnly) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchResultsAsForum'] ) )
{
$count_72909ac1dd384af5c39ce77e245f9361 = is_array($this->functionData['searchResultsAsForum']) ? count($this->functionData['searchResultsAsForum']) : 0;
$this->functionData['searchResultsAsForum'][$count_72909ac1dd384af5c39ce77e245f9361]['results'] = $results;
$this->functionData['searchResultsAsForum'][$count_72909ac1dd384af5c39ce77e245f9361]['titlesOnly'] = $titlesOnly;
}
$IPBHTML .= "<template>searchResultsAsTopic</template>
<searchResults>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('search'), 'searchResults' ) ? $this->registry->getClass('output')->getTemplate('search')->searchResults($results, $titlesOnly) : '' ) . "
</searchResults>";
return $IPBHTML;
}

/* -- searchResultsWrapper --*/
function searchResultsWrapper($results, $sortDropDown, $sortIn, $pagination, $total, $showing, $search_term, $url_string, $current_key, $removed_search_terms=array(), $limited=0, $wasLimited=false, $search_tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchResultsWrapper'] ) )
{
$count_a714e9b24ed9fb2e3527744e574672dc = is_array($this->functionData['searchResultsWrapper']) ? count($this->functionData['searchResultsWrapper']) : 0;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['results'] = $results;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['sortDropDown'] = $sortDropDown;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['sortIn'] = $sortIn;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['pagination'] = $pagination;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['total'] = $total;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['showing'] = $showing;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['search_term'] = $search_term;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['url_string'] = $url_string;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['current_key'] = $current_key;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['removed_search_terms'] = $removed_search_terms;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['limited'] = $limited;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['wasLimited'] = $wasLimited;
$this->functionData['searchResultsWrapper'][$count_a714e9b24ed9fb2e3527744e574672dc]['search_tags'] = $search_tags;
}
$IPBHTML .= "{$results}";
return $IPBHTML;
}

/* -- searchRowGenericFormat --*/
function searchRowGenericFormat($r, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchRowGenericFormat'] ) )
{
$count_9a31a984823e4a5e407a75495e694068 = is_array($this->functionData['searchRowGenericFormat']) ? count($this->functionData['searchRowGenericFormat']) : 0;
$this->functionData['searchRowGenericFormat'][$count_9a31a984823e4a5e407a75495e694068]['r'] = $r;
$this->functionData['searchRowGenericFormat'][$count_9a31a984823e4a5e407a75495e694068]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- topicPostSearchResultAsForum --*/
function topicPostSearchResultAsForum($data, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['topicPostSearchResultAsForum'] ) )
{
$count_006813adc04aa3a1e0269779bb7c4eeb = is_array($this->functionData['topicPostSearchResultAsForum']) ? count($this->functionData['topicPostSearchResultAsForum']) : 0;
$this->functionData['topicPostSearchResultAsForum'][$count_006813adc04aa3a1e0269779bb7c4eeb]['data'] = $data;
$this->functionData['topicPostSearchResultAsForum'][$count_006813adc04aa3a1e0269779bb7c4eeb]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "" . ( method_exists( $this->registry->getClass('output')->getTemplate('search'), 'asForumTopics' ) ? $this->registry->getClass('output')->getTemplate('search')->asForumTopics($data) : '' ) . "";
return $IPBHTML;
}

/* -- userPostsView --*/
function userPostsView($results, $pagination, $total, $member, $limited=0, $wasLimited=false, $beginTime=0, $sortIn=null, $sortDropDown=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['userPostsView'] ) )
{
$count_1eed01fa4f5263920f322e2d3d7f571c = is_array($this->functionData['userPostsView']) ? count($this->functionData['userPostsView']) : 0;
$this->functionData['userPostsView'][$count_1eed01fa4f5263920f322e2d3d7f571c]['results'] = $results;
$this->functionData['userPostsView'][$count_1eed01fa4f5263920f322e2d3d7f571c]['pagination'] = $pagination;
$this->functionData['userPostsView'][$count_1eed01fa4f5263920f322e2d3d7f571c]['total'] = $total;
$this->functionData['userPostsView'][$count_1eed01fa4f5263920f322e2d3d7f571c]['member'] = $member;
$this->functionData['userPostsView'][$count_1eed01fa4f5263920f322e2d3d7f571c]['limited'] = $limited;
$this->functionData['userPostsView'][$count_1eed01fa4f5263920f322e2d3d7f571c]['wasLimited'] = $wasLimited;
$this->functionData['userPostsView'][$count_1eed01fa4f5263920f322e2d3d7f571c]['beginTime'] = $beginTime;
$this->functionData['userPostsView'][$count_1eed01fa4f5263920f322e2d3d7f571c]['sortIn'] = $sortIn;
$this->functionData['userPostsView'][$count_1eed01fa4f5263920f322e2d3d7f571c]['sortDropDown'] = $sortDropDown;
}
$IPBHTML .= "test
<pagination>{$pagination}</pagination>
{$results}";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>