<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 27 Sep 2015 13:40:54 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_modcp_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['deletedPosts'] = array('post_data','disablelightbox','hasPosts');
$this->_funcHooks['deletedTopics'] = array('hastopics');
$this->_funcHooks['editUserForm'] = array('editusercfielddesc','custom_fields','displaynamehistory','modPreview','postingRestricted','suspended','hasRestrictions','groupCanStatus','editusercfields');
$this->_funcHooks['latestWarnLogs'] = array('warningloop','haswarnings');
$this->_funcHooks['membersList'] = array('weAreSupmod','memberwarn','sendpm','blog','gallery','norep','posrep','negrep','repson','isnotbanned','isnotbanned2','members','showmembers');
$this->_funcHooks['membersModIPForm'] = array('modIpIe');
$this->_funcHooks['membersModIPFormMembers'] = array('ipMembers','modIPMembers');
$this->_funcHooks['membersModIPFormPosts'] = array('ipPosts','modFindMemberPosts');
$this->_funcHooks['modAnnounceForm'] = array('buttonlang','announceMessage','buttonlang');
$this->_funcHooks['modAnnouncements'] = array('announce_forums','notactive','notactive','announceHasForums','announceForum','announcements','hasAnnouncements');
$this->_funcHooks['modcpMessage'] = array('hasMessage');
$this->_funcHooks['modCPpost'] = array('reputation','noRep','posRep','negRep','repIgnored','postMid','postMember','postAdmin','postIp','postIsHardDeleted','canSoftDelete','canHardDelete','hasDeletedReasonRow','hasDeletedReason','showReason','postDeletedReason','isDeleted','canEdit','approveUnapprove','approvePost','canDelete','reportedPostData','isUnapproved','postEditByReason','postEditBy','reportedPostData');
$this->_funcHooks['modCPtopic'] = array('haslastpage','pages','isLink','isLinkEnd','multipages','hasStarterId','isntLink','hasDeletedReason','showReason','topicDeletedReason','replylang','isntLink3','tidRestoreLink','canHardDeleteLinkFromDb','topicIsHardDeleted','tidRestore','canHardDeleteFromDb','isntLink4','canSoftDelete','canHardDelete','topics');
$this->_funcHooks['overview'] = array('canEditMember');
$this->_funcHooks['portalPage'] = array('tabs','accessRC');
$this->_funcHooks['subTabLoop'] = array('subTabs','isMainTab','findTab');
$this->_funcHooks['unapprovedPosts'] = array('post_data','disablelightbox','hasPosts');
$this->_funcHooks['unapprovedTopics'] = array('hastopics');


}

/* -- deletedPosts --*/
function deletedPosts($posts, $other_data=array(), $pagelinks='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['deletedPosts'] ) )
{
$count_09d78e4da6590d7a51c1cfdf9658b778 = is_array($this->functionData['deletedPosts']) ? count($this->functionData['deletedPosts']) : 0;
$this->functionData['deletedPosts'][$count_09d78e4da6590d7a51c1cfdf9658b778]['posts'] = $posts;
$this->functionData['deletedPosts'][$count_09d78e4da6590d7a51c1cfdf9658b778]['other_data'] = $other_data;
$this->functionData['deletedPosts'][$count_09d78e4da6590d7a51c1cfdf9658b778]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- deletedTopics --*/
function deletedTopics($topics, $sdelete=array(), $pagelinks='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['deletedTopics'] ) )
{
$count_c3ec56eff577da2632e2221a9bea62eb = is_array($this->functionData['deletedTopics']) ? count($this->functionData['deletedTopics']) : 0;
$this->functionData['deletedTopics'][$count_c3ec56eff577da2632e2221a9bea62eb]['topics'] = $topics;
$this->functionData['deletedTopics'][$count_c3ec56eff577da2632e2221a9bea62eb]['sdelete'] = $sdelete;
$this->functionData['deletedTopics'][$count_c3ec56eff577da2632e2221a9bea62eb]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- editUserForm --*/
function editUserForm($profile, $custom_fields=null) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['editUserForm'] ) )
{
$count_58cace3150696a48af6651a915fa414e = is_array($this->functionData['editUserForm']) ? count($this->functionData['editUserForm']) : 0;
$this->functionData['editUserForm'][$count_58cace3150696a48af6651a915fa414e]['profile'] = $profile;
$this->functionData['editUserForm'][$count_58cace3150696a48af6651a915fa414e]['custom_fields'] = $custom_fields;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- inlineModIPMessage --*/
function inlineModIPMessage($msg='') {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- latestWarnLogs --*/
function latestWarnLogs($warnings, $pagelinks) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['latestWarnLogs'] ) )
{
$count_1a634d82fe95c0497216af5cde7d4773 = is_array($this->functionData['latestWarnLogs']) ? count($this->functionData['latestWarnLogs']) : 0;
$this->functionData['latestWarnLogs'][$count_1a634d82fe95c0497216af5cde7d4773]['warnings'] = $warnings;
$this->functionData['latestWarnLogs'][$count_1a634d82fe95c0497216af5cde7d4773]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberLookup --*/
function memberLookup() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersList --*/
function membersList($type, $members, $pagelinks='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersList'] ) )
{
$count_066394cdb0fce2c9bd6b61eb777f6677 = is_array($this->functionData['membersList']) ? count($this->functionData['membersList']) : 0;
$this->functionData['membersList'][$count_066394cdb0fce2c9bd6b61eb777f6677]['type'] = $type;
$this->functionData['membersList'][$count_066394cdb0fce2c9bd6b61eb777f6677]['members'] = $members;
$this->functionData['membersList'][$count_066394cdb0fce2c9bd6b61eb777f6677]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersModIPForm --*/
function membersModIPForm($ip="", $inlineMsg='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersModIPForm'] ) )
{
$count_059b4f78e829f6dcc854070529a7a320 = is_array($this->functionData['membersModIPForm']) ? count($this->functionData['membersModIPForm']) : 0;
$this->functionData['membersModIPForm'][$count_059b4f78e829f6dcc854070529a7a320]['ip'] = $ip;
$this->functionData['membersModIPForm'][$count_059b4f78e829f6dcc854070529a7a320]['inlineMsg'] = $inlineMsg;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersModIPFormMembers --*/
function membersModIPFormMembers($pages="",$members) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersModIPFormMembers'] ) )
{
$count_237b4870c6ac224edaacc0f54f1a8146 = is_array($this->functionData['membersModIPFormMembers']) ? count($this->functionData['membersModIPFormMembers']) : 0;
$this->functionData['membersModIPFormMembers'][$count_237b4870c6ac224edaacc0f54f1a8146]['pages'] = $pages;
$this->functionData['membersModIPFormMembers'][$count_237b4870c6ac224edaacc0f54f1a8146]['members'] = $members;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersModIPFormPosts --*/
function membersModIPFormPosts($count=0, $pageLinks='', $results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersModIPFormPosts'] ) )
{
$count_04c58817462c1f336a226683750930fd = is_array($this->functionData['membersModIPFormPosts']) ? count($this->functionData['membersModIPFormPosts']) : 0;
$this->functionData['membersModIPFormPosts'][$count_04c58817462c1f336a226683750930fd]['count'] = $count;
$this->functionData['membersModIPFormPosts'][$count_04c58817462c1f336a226683750930fd]['pageLinks'] = $pageLinks;
$this->functionData['membersModIPFormPosts'][$count_04c58817462c1f336a226683750930fd]['results'] = $results;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modAnnounceForm --*/
function modAnnounceForm($announce,$forum_html,$type,$editor_html,$msg="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modAnnounceForm'] ) )
{
$count_3144683f5a99089baaaf86057012244b = is_array($this->functionData['modAnnounceForm']) ? count($this->functionData['modAnnounceForm']) : 0;
$this->functionData['modAnnounceForm'][$count_3144683f5a99089baaaf86057012244b]['announce'] = $announce;
$this->functionData['modAnnounceForm'][$count_3144683f5a99089baaaf86057012244b]['forum_html'] = $forum_html;
$this->functionData['modAnnounceForm'][$count_3144683f5a99089baaaf86057012244b]['type'] = $type;
$this->functionData['modAnnounceForm'][$count_3144683f5a99089baaaf86057012244b]['editor_html'] = $editor_html;
$this->functionData['modAnnounceForm'][$count_3144683f5a99089baaaf86057012244b]['msg'] = $msg;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modAnnouncements --*/
function modAnnouncements($announcements) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modAnnouncements'] ) )
{
$count_cdd3b67af5461b7cd1ec5db634dbd480 = is_array($this->functionData['modAnnouncements']) ? count($this->functionData['modAnnouncements']) : 0;
$this->functionData['modAnnouncements'][$count_cdd3b67af5461b7cd1ec5db634dbd480]['announcements'] = $announcements;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modcpMessage --*/
function modcpMessage($message='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modcpMessage'] ) )
{
$count_0726f34cf260de498b36ec2eec113305 = is_array($this->functionData['modcpMessage']) ? count($this->functionData['modcpMessage']) : 0;
$this->functionData['modcpMessage'][$count_0726f34cf260de498b36ec2eec113305]['message'] = $message;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- modCPpost --*/
function modCPpost($post, $displayData, $topic, $type) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modCPpost'] ) )
{
$count_f5d568fb16616303af5ccd9f91d9d3d8 = is_array($this->functionData['modCPpost']) ? count($this->functionData['modCPpost']) : 0;
$this->functionData['modCPpost'][$count_f5d568fb16616303af5ccd9f91d9d3d8]['post'] = $post;
$this->functionData['modCPpost'][$count_f5d568fb16616303af5ccd9f91d9d3d8]['displayData'] = $displayData;
$this->functionData['modCPpost'][$count_f5d568fb16616303af5ccd9f91d9d3d8]['topic'] = $topic;
$this->functionData['modCPpost'][$count_f5d568fb16616303af5ccd9f91d9d3d8]['type'] = $type;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modCPtopic --*/
function modCPtopic($topics, $pagelinks, $type, $sdelete=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modCPtopic'] ) )
{
$count_021d257e52a410e6de0e6a4eb21ca920 = is_array($this->functionData['modCPtopic']) ? count($this->functionData['modCPtopic']) : 0;
$this->functionData['modCPtopic'][$count_021d257e52a410e6de0e6a4eb21ca920]['topics'] = $topics;
$this->functionData['modCPtopic'][$count_021d257e52a410e6de0e6a4eb21ca920]['pagelinks'] = $pagelinks;
$this->functionData['modCPtopic'][$count_021d257e52a410e6de0e6a4eb21ca920]['type'] = $type;
$this->functionData['modCPtopic'][$count_021d257e52a410e6de0e6a4eb21ca920]['sdelete'] = $sdelete;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- overview --*/
function overview() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['overview'] ) )
{
$count_bb38cabc58b51d79f476303cf4f86e02 = is_array($this->functionData['overview']) ? count($this->functionData['overview']) : 0;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- portalPage --*/
function portalPage($output, $tabs=array(), $_activeNav=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['portalPage'] ) )
{
$count_40883fb407e25ca800b5ecfcc008ffbf = is_array($this->functionData['portalPage']) ? count($this->functionData['portalPage']) : 0;
$this->functionData['portalPage'][$count_40883fb407e25ca800b5ecfcc008ffbf]['output'] = $output;
$this->functionData['portalPage'][$count_40883fb407e25ca800b5ecfcc008ffbf]['tabs'] = $tabs;
$this->functionData['portalPage'][$count_40883fb407e25ca800b5ecfcc008ffbf]['_activeNav'] = $_activeNav;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- subTabLoop --*/
function subTabLoop() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['subTabLoop'] ) )
{
$count_b891e4cb881664fc40956ec810217332 = is_array($this->functionData['subTabLoop']) ? count($this->functionData['subTabLoop']) : 0;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- unapprovedPosts --*/
function unapprovedPosts($posts, $pagelinks) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['unapprovedPosts'] ) )
{
$count_6bce6d356535dd44da426cb169235af8 = is_array($this->functionData['unapprovedPosts']) ? count($this->functionData['unapprovedPosts']) : 0;
$this->functionData['unapprovedPosts'][$count_6bce6d356535dd44da426cb169235af8]['posts'] = $posts;
$this->functionData['unapprovedPosts'][$count_6bce6d356535dd44da426cb169235af8]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- unapprovedTopics --*/
function unapprovedTopics($topics, $pagelinks) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['unapprovedTopics'] ) )
{
$count_0f86bdf7e946976b8c18c7f04d6db1dd = is_array($this->functionData['unapprovedTopics']) ? count($this->functionData['unapprovedTopics']) : 0;
$this->functionData['unapprovedTopics'][$count_0f86bdf7e946976b8c18c7f04d6db1dd]['topics'] = $topics;
$this->functionData['unapprovedTopics'][$count_0f86bdf7e946976b8c18c7f04d6db1dd]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>