<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 27 Sep 2015 13:40:54 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_editors_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['ajaxEditBox'] = array('jsNotLoaded','ajaxerror','forceStd','showreason','appendedit','showappendedit','htmlstatus','showeditoptions');
$this->_funcHooks['editor'] = array('hasWrningInfo','jsNotLoaded','ismini','ismini','hasContent','hasType','ismini','hasHeight','hasMinimize','hasCallback','hasSaveKey','showEditor','hasToAcknowledge');
$this->_funcHooks['editorLoadJs'] = array('bypassCkEditor','hasimages','hasPastePlain');
$this->_funcHooks['mediaGenericWrapper'] = array('haswidth','hasheight','hasimage','hasdescription','genericmedia','hasrows');
$this->_funcHooks['sharedMedia'] = array('mediatabs');


}

/* -- ajaxEditBox --*/
function ajaxEditBox($post="", $pid=0, $error_msg="", $extraData) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['ajaxEditBox'] ) )
{
$count_b9723e897b735510b1301fe3a8d64cc1 = is_array($this->functionData['ajaxEditBox']) ? count($this->functionData['ajaxEditBox']) : 0;
$this->functionData['ajaxEditBox'][$count_b9723e897b735510b1301fe3a8d64cc1]['post'] = $post;
$this->functionData['ajaxEditBox'][$count_b9723e897b735510b1301fe3a8d64cc1]['pid'] = $pid;
$this->functionData['ajaxEditBox'][$count_b9723e897b735510b1301fe3a8d64cc1]['error_msg'] = $error_msg;
$this->functionData['ajaxEditBox'][$count_b9723e897b735510b1301fe3a8d64cc1]['extraData'] = $extraData;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- editor --*/
function editor($formField='post', $content='', $options=array(), $autoSaveData=array(), $warningInfo='', $acknowledge=FALSE) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['editor'] ) )
{
$count_bb8855e19d1d5a59f4bf452491495758 = is_array($this->functionData['editor']) ? count($this->functionData['editor']) : 0;
$this->functionData['editor'][$count_bb8855e19d1d5a59f4bf452491495758]['formField'] = $formField;
$this->functionData['editor'][$count_bb8855e19d1d5a59f4bf452491495758]['content'] = $content;
$this->functionData['editor'][$count_bb8855e19d1d5a59f4bf452491495758]['options'] = $options;
$this->functionData['editor'][$count_bb8855e19d1d5a59f4bf452491495758]['autoSaveData'] = $autoSaveData;
$this->functionData['editor'][$count_bb8855e19d1d5a59f4bf452491495758]['warningInfo'] = $warningInfo;
$this->functionData['editor'][$count_bb8855e19d1d5a59f4bf452491495758]['acknowledge'] = $acknowledge;
}
$IPBHTML .= "<content><![CDATA[{$content}]]></content>";
return $IPBHTML;
}

/* -- editorLoadJs --*/
function editorLoadJs($options='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['editorLoadJs'] ) )
{
$count_d516cbdbe5cd428a23761f222a3981d8 = is_array($this->functionData['editorLoadJs']) ? count($this->functionData['editorLoadJs']) : 0;
$this->functionData['editorLoadJs'][$count_d516cbdbe5cd428a23761f222a3981d8]['options'] = $options;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- editorSettings --*/
function editorSettings() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- mediaGenericWrapper --*/
function mediaGenericWrapper($rows, $pages, $app, $plugin) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['mediaGenericWrapper'] ) )
{
$count_0877cc1763d164f7066c353504704309 = is_array($this->functionData['mediaGenericWrapper']) ? count($this->functionData['mediaGenericWrapper']) : 0;
$this->functionData['mediaGenericWrapper'][$count_0877cc1763d164f7066c353504704309]['rows'] = $rows;
$this->functionData['mediaGenericWrapper'][$count_0877cc1763d164f7066c353504704309]['pages'] = $pages;
$this->functionData['mediaGenericWrapper'][$count_0877cc1763d164f7066c353504704309]['app'] = $app;
$this->functionData['mediaGenericWrapper'][$count_0877cc1763d164f7066c353504704309]['plugin'] = $plugin;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- sharedMedia --*/
function sharedMedia($tabs) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['sharedMedia'] ) )
{
$count_ce6ddb9980ed0b0efe0f9bac43953004 = is_array($this->functionData['sharedMedia']) ? count($this->functionData['sharedMedia']) : 0;
$this->functionData['sharedMedia'][$count_ce6ddb9980ed0b0efe0f9bac43953004]['tabs'] = $tabs;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- sharedMediaDefault --*/
function sharedMediaDefault() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>