<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 27 Sep 2015 13:40:54 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_ucp_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['coreAttachments'] = array('attachmentThumbLocation','attachmentPost','attach','attachAlmostFull','hasAttachLimit','hasPagesTop','hasAttachments','attachmentMultiDelete','hasPagesBottom');
$this->_funcHooks['displayNameForm'] = array('dnameOkMessage','dnameFbUser');
$this->_funcHooks['emailPasswordChangeForm'] = array('hideMessageIfAdmin','emailIsAdmin','passFbUser','removeUser','removeUser2','removeUser3','removeUser4','emailIsNotAdmin');
$this->_funcHooks['field_entry'] = array('cfieldDesc','cfieldDesc');
$this->_funcHooks['membersFacebookConnect'] = array('fbShowStatus','fbSyncPic','fbSyncStatus','canUpdateStatus','fbSyncStatus','statusImportGroup','fbLastSync','pImgE','pCheckE','pImgPS','pCheckPS','pImgRS','pCheckRS','fbPassword','fbDefaultEmail','fbMismatch');
$this->_funcHooks['membersIgnoredUsersForm'] = array('ignoreMemberTopics','ignoreMemberSigs','ignoreGlobal','ignoreMemberPms','ignoreUserchats','hasChatRow','members','canSee','topPagination','hasChat','hasChatNone','bottomPagination','hasChatRowCheckbox');
$this->_funcHooks['membersProfileForm'] = array('isOurTimezone','timezones','monthSelected','months','daySelected','days','yearSelected','years','canUploadPhoto','dstError','doAutoDst','doManualDst','doManualDst','showComments','yesModComments','showLastVisitors','showFriends','yesModFriends','friendsEnabled','changeMemberTitle','birthdayFields','showProfileInfo','requiredCfields','optionalCfields');
$this->_funcHooks['membersSignatureForm'] = array('hasSignatureLimits','htmlModeOn','canUseHtml','disablelightbox');
$this->_funcHooks['membersTwitterConnect'] = array('tcHasPic','tcShowStatus','tcHasPic','tcLastSync','tcSyncPic','tcSyncStatus','tcSyncIStatus','statusImportGroup','tcSyncAboutMe','tcSyncBgImg','canBG','twitterPassword');
$this->_funcHooks['notificationsForm'] = array('hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','keyExists','groupKeys','isPrivateMsg','badConfig','isTopicsOrPosts','notifyGroupsList','isCoreNot','updateLastApp','newNotApp','hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','keyNotDone','notifyOther','allowAdminMails');
$this->_funcHooks['notificationsLog'] = array('hasReadNotify','hasReadNotify','categories','hasconfirm','hasnotifyerror','hasNotifications','hasNotifyForMod','notifications');
$this->_funcHooks['userCPTemplate'] = array('isSettings','isSettingsInactive','active_tab','tabs','tabsMenus_active','items','errors','has_max_upload','usercp_form','hasMoreThanOneTabClass','hasMoreThanOneTabSidebar','hasMoreThanOneTabClassContent','has_errors','didSave','submit_button','end_form');


}

/* -- coreAttachments --*/
function coreAttachments($info="",$pages="",$attachments) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['coreAttachments'] ) )
{
$count_d0fce600056e6b51cdee4f77cc74e464 = is_array($this->functionData['coreAttachments']) ? count($this->functionData['coreAttachments']) : 0;
$this->functionData['coreAttachments'][$count_d0fce600056e6b51cdee4f77cc74e464]['info'] = $info;
$this->functionData['coreAttachments'][$count_d0fce600056e6b51cdee4f77cc74e464]['pages'] = $pages;
$this->functionData['coreAttachments'][$count_d0fce600056e6b51cdee4f77cc74e464]['attachments'] = $attachments;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- displayNameForm --*/
function displayNameForm($form=array(),$error="",$okmessage="", $isFB=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['displayNameForm'] ) )
{
$count_41d06ca9404538814cf1e424e2645147 = is_array($this->functionData['displayNameForm']) ? count($this->functionData['displayNameForm']) : 0;
$this->functionData['displayNameForm'][$count_41d06ca9404538814cf1e424e2645147]['form'] = $form;
$this->functionData['displayNameForm'][$count_41d06ca9404538814cf1e424e2645147]['error'] = $error;
$this->functionData['displayNameForm'][$count_41d06ca9404538814cf1e424e2645147]['okmessage'] = $okmessage;
$this->functionData['displayNameForm'][$count_41d06ca9404538814cf1e424e2645147]['isFB'] = $isFB;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- emailPasswordChangeForm --*/
function emailPasswordChangeForm($txt, $_message, $isFB=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['emailPasswordChangeForm'] ) )
{
$count_4751a414f2bb70429ae68b8aec2c1cec = is_array($this->functionData['emailPasswordChangeForm']) ? count($this->functionData['emailPasswordChangeForm']) : 0;
$this->functionData['emailPasswordChangeForm'][$count_4751a414f2bb70429ae68b8aec2c1cec]['txt'] = $txt;
$this->functionData['emailPasswordChangeForm'][$count_4751a414f2bb70429ae68b8aec2c1cec]['_message'] = $_message;
$this->functionData['emailPasswordChangeForm'][$count_4751a414f2bb70429ae68b8aec2c1cec]['isFB'] = $isFB;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_dropdown --*/
function field_dropdown($name="",$options="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_entry --*/
function field_entry($title="",$desc="",$content="",$id="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['field_entry'] ) )
{
$count_9b2e33c7cff38233030f10a0071adc1c = is_array($this->functionData['field_entry']) ? count($this->functionData['field_entry']) : 0;
$this->functionData['field_entry'][$count_9b2e33c7cff38233030f10a0071adc1c]['title'] = $title;
$this->functionData['field_entry'][$count_9b2e33c7cff38233030f10a0071adc1c]['desc'] = $desc;
$this->functionData['field_entry'][$count_9b2e33c7cff38233030f10a0071adc1c]['content'] = $content;
$this->functionData['field_entry'][$count_9b2e33c7cff38233030f10a0071adc1c]['id'] = $id;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_textarea --*/
function field_textarea($name="",$value="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_textinput --*/
function field_textinput($name="",$value="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersFacebookConnect --*/
function membersFacebookConnect($fbuid, $fbUserData, $linkedMemberData, $perms) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersFacebookConnect'] ) )
{
$count_9fa6ffc258133b53f09dbbe7b0d14413 = is_array($this->functionData['membersFacebookConnect']) ? count($this->functionData['membersFacebookConnect']) : 0;
$this->functionData['membersFacebookConnect'][$count_9fa6ffc258133b53f09dbbe7b0d14413]['fbuid'] = $fbuid;
$this->functionData['membersFacebookConnect'][$count_9fa6ffc258133b53f09dbbe7b0d14413]['fbUserData'] = $fbUserData;
$this->functionData['membersFacebookConnect'][$count_9fa6ffc258133b53f09dbbe7b0d14413]['linkedMemberData'] = $linkedMemberData;
$this->functionData['membersFacebookConnect'][$count_9fa6ffc258133b53f09dbbe7b0d14413]['perms'] = $perms;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersIgnoredUsersForm --*/
function membersIgnoredUsersForm($members) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersIgnoredUsersForm'] ) )
{
$count_fe6d411221c000c00333df078f0da7fd = is_array($this->functionData['membersIgnoredUsersForm']) ? count($this->functionData['membersIgnoredUsersForm']) : 0;
$this->functionData['membersIgnoredUsersForm'][$count_fe6d411221c000c00333df078f0da7fd]['members'] = $members;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersProfileCustomize --*/
function membersProfileCustomize($options, $input, $errors) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersProfileForm --*/
function membersProfileForm($custom_fields='',$group_titles='',$day='',$mon='',$year='', $amEditor='', $times=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersProfileForm'] ) )
{
$count_5f6b30bfadb11e8d1980ef63361c92a6 = is_array($this->functionData['membersProfileForm']) ? count($this->functionData['membersProfileForm']) : 0;
$this->functionData['membersProfileForm'][$count_5f6b30bfadb11e8d1980ef63361c92a6]['custom_fields'] = $custom_fields;
$this->functionData['membersProfileForm'][$count_5f6b30bfadb11e8d1980ef63361c92a6]['group_titles'] = $group_titles;
$this->functionData['membersProfileForm'][$count_5f6b30bfadb11e8d1980ef63361c92a6]['day'] = $day;
$this->functionData['membersProfileForm'][$count_5f6b30bfadb11e8d1980ef63361c92a6]['mon'] = $mon;
$this->functionData['membersProfileForm'][$count_5f6b30bfadb11e8d1980ef63361c92a6]['year'] = $year;
$this->functionData['membersProfileForm'][$count_5f6b30bfadb11e8d1980ef63361c92a6]['amEditor'] = $amEditor;
$this->functionData['membersProfileForm'][$count_5f6b30bfadb11e8d1980ef63361c92a6]['times'] = $times;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- membersSignatureForm --*/
function membersSignatureForm($editor_html="",$sig_restrictions=array(),$signature='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersSignatureForm'] ) )
{
$count_b688478ba92986917a1fc9f89b20bc67 = is_array($this->functionData['membersSignatureForm']) ? count($this->functionData['membersSignatureForm']) : 0;
$this->functionData['membersSignatureForm'][$count_b688478ba92986917a1fc9f89b20bc67]['editor_html'] = $editor_html;
$this->functionData['membersSignatureForm'][$count_b688478ba92986917a1fc9f89b20bc67]['sig_restrictions'] = $sig_restrictions;
$this->functionData['membersSignatureForm'][$count_b688478ba92986917a1fc9f89b20bc67]['signature'] = $signature;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersSignatureFormError --*/
function membersSignatureFormError($form) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersTwitterConnect --*/
function membersTwitterConnect($isConnected, $twitterUser=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersTwitterConnect'] ) )
{
$count_d8979833381408e8773b3a62b362d075 = is_array($this->functionData['membersTwitterConnect']) ? count($this->functionData['membersTwitterConnect']) : 0;
$this->functionData['membersTwitterConnect'][$count_d8979833381408e8773b3a62b362d075]['isConnected'] = $isConnected;
$this->functionData['membersTwitterConnect'][$count_d8979833381408e8773b3a62b362d075]['twitterUser'] = $twitterUser;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- notificationsForm --*/
function notificationsForm($config, $emailData) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['notificationsForm'] ) )
{
$count_b5b7ce1d5b268c33719854c149109282 = is_array($this->functionData['notificationsForm']) ? count($this->functionData['notificationsForm']) : 0;
$this->functionData['notificationsForm'][$count_b5b7ce1d5b268c33719854c149109282]['config'] = $config;
$this->functionData['notificationsForm'][$count_b5b7ce1d5b268c33719854c149109282]['emailData'] = $emailData;
}
$IPBHTML .= "test";
return $IPBHTML;
}

/* -- notificationsLog --*/
function notificationsLog($notifications, $error='', $pages='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['notificationsLog'] ) )
{
$count_6e8db470b219d989acad9b25c230f10e = is_array($this->functionData['notificationsLog']) ? count($this->functionData['notificationsLog']) : 0;
$this->functionData['notificationsLog'][$count_6e8db470b219d989acad9b25c230f10e]['notifications'] = $notifications;
$this->functionData['notificationsLog'][$count_6e8db470b219d989acad9b25c230f10e]['error'] = $error;
$this->functionData['notificationsLog'][$count_6e8db470b219d989acad9b25c230f10e]['pages'] = $pages;
}
$IPBHTML .= "<template>popoverNotifications</template>
<notifications>
	".$this->__f__278a82d5d1a381a7d26245a8cc93a8e3($notifications,$error,$pages)."</notifications>";
return $IPBHTML;
}


function __f__278a82d5d1a381a7d26245a8cc93a8e3($notifications, $error='', $pages='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $notifications as $notification )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<notification>
			<id>{$notification['notify_id']}</id>
			<url><![CDATA[{$notification['notify_url']}]]></url>
			<icon><![CDATA[{$notification['member']['pp_thumb_photo']}]]></icon>
			<text><![CDATA[{$notification['notify_title']}]]></text>
		</notification>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- showNotification --*/
function showNotification($notification) {
$IPBHTML = "";
$IPBHTML .= "test";
return $IPBHTML;
}

/* -- unsubscribed --*/
function unsubscribed() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- userCPTemplate --*/
function userCPTemplate($current_tab, $html, $tabs, $current_area, $errors=array(), $hide_form=0, $maxUpload=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['userCPTemplate'] ) )
{
$count_66622216eeb6483fbbadc7f39383fff4 = is_array($this->functionData['userCPTemplate']) ? count($this->functionData['userCPTemplate']) : 0;
$this->functionData['userCPTemplate'][$count_66622216eeb6483fbbadc7f39383fff4]['current_tab'] = $current_tab;
$this->functionData['userCPTemplate'][$count_66622216eeb6483fbbadc7f39383fff4]['html'] = $html;
$this->functionData['userCPTemplate'][$count_66622216eeb6483fbbadc7f39383fff4]['tabs'] = $tabs;
$this->functionData['userCPTemplate'][$count_66622216eeb6483fbbadc7f39383fff4]['current_area'] = $current_area;
$this->functionData['userCPTemplate'][$count_66622216eeb6483fbbadc7f39383fff4]['errors'] = $errors;
$this->functionData['userCPTemplate'][$count_66622216eeb6483fbbadc7f39383fff4]['hide_form'] = $hide_form;
$this->functionData['userCPTemplate'][$count_66622216eeb6483fbbadc7f39383fff4]['maxUpload'] = $maxUpload;
}
$IPBHTML .= "{$html}";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>