<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 27 Sep 2015 13:40:54 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_profile_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['acknowledgeWarning'] = array('valueIsPermanent','hasValue','options','memberNote','hasReasonAndContent','hasContent','hasReason','hasExpireDate','hasExpiration','hasPoints','isVerbalWarning');
$this->_funcHooks['addWarning'] = array('reasons','canUseAsBanGroup','banGroups','hasOtherOption','currentMq','currentRpa','currentSuspend');
$this->_funcHooks['customField__gender'] = array('male','female','nottelling','gender_set');
$this->_funcHooks['customField__generic'] = array('genericIsArray');
$this->_funcHooks['customFieldGroup__contact'] = array('cfieldgroups','cf_icon','cf_skype','cf_jabber','cf_website','cf_icq','cf_yahoo','cf_msn','cf_aim','cf_array','contact_field');
$this->_funcHooks['customizeProfile'] = array('hasBackgroundColor','backgroundIsFixed','hasBackgroundImage','hasBodyCustomization');
$this->_funcHooks['dnameWrapper'] = array('records','isAjaxModule','hasDnameHistory');
$this->_funcHooks['explainPoints'] = array('reasons','valueIsPermanent','hasValue','options','actions','hasActions');
$this->_funcHooks['friendsList'] = array('norep','posrep','negrep','repson','weAreSupmod','addfriend','notus','sendpm','blog','gallery','norep','posrep','negrep','repson','loopOnPending','friendsList','friendListPages','tabIsList','tabIsPending','friendListNone','hasFriendsList','friendListPagesBottom');
$this->_funcHooks['listWarnings'] = array('hasReason','warnings','paginationTop','canWarn','hasPaginationOrWarn','noWarnings','paginationBottom');
$this->_funcHooks['photoEditor'] = array('canHasUpload','canHasURL','allowGravatars','hasTwitter','hasFacebook');
$this->_funcHooks['profileModern'] = array('tabactive','tabs','warnClickable','warnPopup','warnIsSet','warnsLoop','pcfieldsLoop','pcfieldsEmptyValue','pcfieldsOtherLoopCheckInner','pcfieldsOtherLoopCheck2','pcfieldsOtherLoopCheck','pcfieldsOtherLoop','cfields','friendsLoop','visitorismember','latest_visitors_loop','jsIsFriend','friendsEnabled','hasCustomization','weAreSupmod','weAreOwner','supModCustomization','canEditUser','canEditPic','haswarn','hasWarns','onlineDetails','userStatus','rate1','rate2','rate3','rate4','rate5','rated1','rated2','rated3','rated4','rated5','hasrating','noRateYourself','allowRate','isFriend','noFriendYourself','pmlink','member_title','member_age','member_bday_year','member_birthday','pcfields','pcfieldsOther','showContactHead','isadmin','member_contact_fields','hasContactFields','RepPositive','RepNegative','RepZero','RepText','RepImage','ourReputation','authorspammerinner','authorspammer','dnameHistory','supModCustomizationDisable','checkModTools','hasFriends','has_visitors','latest_visitors','thisIsNotUs','tabs','pmlink');
$this->_funcHooks['reputationPage'] = array('isTheActiveApp','apps','hasMoreThanOneApp','hasResults');
$this->_funcHooks['showCard'] = array('cardRepPos','cardRepNeg','cardRepZero','cardRep','cardSendPm','cardStatus','cardOnline','cardWhere','isadmin','authorspammerinner','authorspammer','cardIsFriend','cardFriend','cardBlog','cardGallery');
$this->_funcHooks['statusReplies'] = array('canDelete','innerLoop','noWrapperTop','noWrapperBottom','canDelete');
$this->_funcHooks['statusUpdates'] = array('isUs','moderated','forSomeoneElse','noLocked','cImg','creatorText','canDelete','isLocked','canLock','isUnapproved','addReturn','hasMore','hasReplies','canReply','maxReplies','statusApproved','outerLoop','canDelete','outerLoop');
$this->_funcHooks['statusUpdatesPage'] = array('tabactive','tabactive2','updateTwitter','updateFacebook','update','canCreate','hasUpdates','hasPagination');
$this->_funcHooks['tabFriends'] = array('friends','friends_loop','friends','friends');
$this->_funcHooks['tabReputation'] = array('isTheActiveApp','apps','hasMoreThanOneApp','currentIsGiven','canViewRep','currentIsReceived','hasResults','bottomPagination');
$this->_funcHooks['tabReputation_calendar'] = array('postMid','postMember','postMid','postMember');
$this->_funcHooks['tabReputation_posts'] = array('notLastFtAsForum','topicsForumTrail','postMid','postMember','hasForumTrail');
$this->_funcHooks['tabSingleColumn'] = array('singleColumnUrl','singleColumnTitle','date');
$this->_funcHooks['tabStatusUpdates'] = array('updateTwitter','updateFacebook','update','canCreate','leave_comment','hasUpdates','canCreate','leave_comment','hasUpdates');


}

/* -- acknowledgeWarning --*/
function acknowledgeWarning($warning) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['acknowledgeWarning'] ) )
{
$count_a705ceab80475da3a8de3f8151812365 = is_array($this->functionData['acknowledgeWarning']) ? count($this->functionData['acknowledgeWarning']) : 0;
$this->functionData['acknowledgeWarning'][$count_a705ceab80475da3a8de3f8151812365]['warning'] = $warning;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- addWarning --*/
function addWarning($member, $reasons, $errors, $editor) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['addWarning'] ) )
{
$count_679f0d13332a224a0a965d8b5e6408b6 = is_array($this->functionData['addWarning']) ? count($this->functionData['addWarning']) : 0;
$this->functionData['addWarning'][$count_679f0d13332a224a0a965d8b5e6408b6]['member'] = $member;
$this->functionData['addWarning'][$count_679f0d13332a224a0a965d8b5e6408b6]['reasons'] = $reasons;
$this->functionData['addWarning'][$count_679f0d13332a224a0a965d8b5e6408b6]['errors'] = $errors;
$this->functionData['addWarning'][$count_679f0d13332a224a0a965d8b5e6408b6]['editor'] = $editor;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- customField__gender --*/
function customField__gender($f) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['customField__gender'] ) )
{
$count_da7969cb2338a8324312e3dd1e3d8d03 = is_array($this->functionData['customField__gender']) ? count($this->functionData['customField__gender']) : 0;
$this->functionData['customField__gender'][$count_da7969cb2338a8324312e3dd1e3d8d03]['f'] = $f;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- customField__generic --*/
function customField__generic($f) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['customField__generic'] ) )
{
$count_dbeeecbeeea7e9f2bf0e3babd618319b = is_array($this->functionData['customField__generic']) ? count($this->functionData['customField__generic']) : 0;
$this->functionData['customField__generic'][$count_dbeeecbeeea7e9f2bf0e3babd618319b]['f'] = $f;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- customFieldGroup__contact --*/
function customFieldGroup__contact($f) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['customFieldGroup__contact'] ) )
{
$count_a6dde71d0662883af917d1ae42d5e498 = is_array($this->functionData['customFieldGroup__contact']) ? count($this->functionData['customFieldGroup__contact']) : 0;
$this->functionData['customFieldGroup__contact'][$count_a6dde71d0662883af917d1ae42d5e498]['f'] = $f;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- customizeProfile --*/
function customizeProfile($member) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['customizeProfile'] ) )
{
$count_46125c607e422c7b71072ec82a624aca = is_array($this->functionData['customizeProfile']) ? count($this->functionData['customizeProfile']) : 0;
$this->functionData['customizeProfile'][$count_46125c607e422c7b71072ec82a624aca]['member'] = $member;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- dnameWrapper --*/
function dnameWrapper($member_name="",$records=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['dnameWrapper'] ) )
{
$count_5e1f1e6aa577eac4c9628c91e40423c6 = is_array($this->functionData['dnameWrapper']) ? count($this->functionData['dnameWrapper']) : 0;
$this->functionData['dnameWrapper'][$count_5e1f1e6aa577eac4c9628c91e40423c6]['member_name'] = $member_name;
$this->functionData['dnameWrapper'][$count_5e1f1e6aa577eac4c9628c91e40423c6]['records'] = $records;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- explainPoints --*/
function explainPoints($reasons, $actions) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['explainPoints'] ) )
{
$count_d6ae01ae7a7014f6d49545a9e999c066 = is_array($this->functionData['explainPoints']) ? count($this->functionData['explainPoints']) : 0;
$this->functionData['explainPoints'][$count_d6ae01ae7a7014f6d49545a9e999c066]['reasons'] = $reasons;
$this->functionData['explainPoints'][$count_d6ae01ae7a7014f6d49545a9e999c066]['actions'] = $actions;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- friendsList --*/
function friendsList($friends, $pages) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['friendsList'] ) )
{
$count_74ed2fe6e3ec28303ab6593ba019439f = is_array($this->functionData['friendsList']) ? count($this->functionData['friendsList']) : 0;
$this->functionData['friendsList'][$count_74ed2fe6e3ec28303ab6593ba019439f]['friends'] = $friends;
$this->functionData['friendsList'][$count_74ed2fe6e3ec28303ab6593ba019439f]['pages'] = $pages;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- listWarnings --*/
function listWarnings($member, $warnings, $pagination, $reasons, $canWarn) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['listWarnings'] ) )
{
$count_48197f56d14f49e0da22d9a145ef3b46 = is_array($this->functionData['listWarnings']) ? count($this->functionData['listWarnings']) : 0;
$this->functionData['listWarnings'][$count_48197f56d14f49e0da22d9a145ef3b46]['member'] = $member;
$this->functionData['listWarnings'][$count_48197f56d14f49e0da22d9a145ef3b46]['warnings'] = $warnings;
$this->functionData['listWarnings'][$count_48197f56d14f49e0da22d9a145ef3b46]['pagination'] = $pagination;
$this->functionData['listWarnings'][$count_48197f56d14f49e0da22d9a145ef3b46]['reasons'] = $reasons;
$this->functionData['listWarnings'][$count_48197f56d14f49e0da22d9a145ef3b46]['canWarn'] = $canWarn;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- photoEditor --*/
function photoEditor($data, $member) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['photoEditor'] ) )
{
$count_3c645001f6724e37cd0ade71f23ed55d = is_array($this->functionData['photoEditor']) ? count($this->functionData['photoEditor']) : 0;
$this->functionData['photoEditor'][$count_3c645001f6724e37cd0ade71f23ed55d]['data'] = $data;
$this->functionData['photoEditor'][$count_3c645001f6724e37cd0ade71f23ed55d]['member'] = $member;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- profileModern --*/
function profileModern($tabs=array(), $member=array(), $visitors=array(), $default_tab='status', $default_tab_content='', $friends=array(), $status=array(), $warns=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['profileModern'] ) )
{
$count_f2d1f58371471e55c42ad8b64d0de98f = is_array($this->functionData['profileModern']) ? count($this->functionData['profileModern']) : 0;
$this->functionData['profileModern'][$count_f2d1f58371471e55c42ad8b64d0de98f]['tabs'] = $tabs;
$this->functionData['profileModern'][$count_f2d1f58371471e55c42ad8b64d0de98f]['member'] = $member;
$this->functionData['profileModern'][$count_f2d1f58371471e55c42ad8b64d0de98f]['visitors'] = $visitors;
$this->functionData['profileModern'][$count_f2d1f58371471e55c42ad8b64d0de98f]['default_tab'] = $default_tab;
$this->functionData['profileModern'][$count_f2d1f58371471e55c42ad8b64d0de98f]['default_tab_content'] = $default_tab_content;
$this->functionData['profileModern'][$count_f2d1f58371471e55c42ad8b64d0de98f]['friends'] = $friends;
$this->functionData['profileModern'][$count_f2d1f58371471e55c42ad8b64d0de98f]['status'] = $status;
$this->functionData['profileModern'][$count_f2d1f58371471e55c42ad8b64d0de98f]['warns'] = $warns;
}
$IPBHTML .= "<template>profileView</template>
<profileData>
	<id>{$member['member_id']}</id>
	<name><![CDATA[{$member['members_display_name']}]]></name>
	<memberTitle><![CDATA[{$member['title']}]]></memberTitle>
	<reputation>{$member['pp_reputation_points']}</reputation>
	<postCount>{$member['posts']}</postCount>
	<avatar><![CDATA[{$member['pp_main_photo']}]]></avatar>	
</profileData>
<tab><![CDATA[{$default_tab}]]></tab>
" . (($default_tab == 'core:info') ? ("" . ((($member['member_id'] != $this->memberData['member_id']) AND $this->memberData['g_use_pm'] AND $this->memberData['members_disable_pm'] == 0 AND IPSLib::moduleIsEnabled( 'messaging', 'members' ) AND $member['members_disable_pm'] == 0) ? ("
<pmMeLink><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=members&amp;module=messaging&amp;section=send&amp;do=form&amp;fromMemberID={$member['member_id']}", "public",'' ), "", "" ) . "]]></pmMeLink>
") : ("")) . "
<viewMyContent><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;mid={$member['member_id']}", "public",'' ), "", "" ) . "]]></viewMyContent>
<profileTabs>
	".$this->__f__d3e961d1003e998e9290b1c8bfb8642e($tabs,$member,$visitors,$default_tab,$default_tab_content,$friends,$status,$warns)."</profileTabs>") : ("
	{$default_tab_content}
")) . "";
return $IPBHTML;
}


function __f__d3e961d1003e998e9290b1c8bfb8642e($tabs=array(), $member=array(), $visitors=array(), $default_tab='status', $default_tab_content='', $friends=array(), $status=array(), $warns=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $tabs as $tab )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<profileTab>
			<name><![CDATA[{$tab['_lang']}]]></name>
			<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}&amp;tab={$tab['plugin_key']}", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "]]></url>
		</profileTab>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- reputationPage --*/
function reputationPage($langBit, $currentApp='', $supportedApps=array(), $processedResults='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['reputationPage'] ) )
{
$count_4765ad5a5b8bd378640c468c116ecab2 = is_array($this->functionData['reputationPage']) ? count($this->functionData['reputationPage']) : 0;
$this->functionData['reputationPage'][$count_4765ad5a5b8bd378640c468c116ecab2]['langBit'] = $langBit;
$this->functionData['reputationPage'][$count_4765ad5a5b8bd378640c468c116ecab2]['currentApp'] = $currentApp;
$this->functionData['reputationPage'][$count_4765ad5a5b8bd378640c468c116ecab2]['supportedApps'] = $supportedApps;
$this->functionData['reputationPage'][$count_4765ad5a5b8bd378640c468c116ecab2]['processedResults'] = $processedResults;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- showCard --*/
function showCard($member, $download=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['showCard'] ) )
{
$count_445c8fcbc8174e9b1d0960e3166b9ab2 = is_array($this->functionData['showCard']) ? count($this->functionData['showCard']) : 0;
$this->functionData['showCard'][$count_445c8fcbc8174e9b1d0960e3166b9ab2]['member'] = $member;
$this->functionData['showCard'][$count_445c8fcbc8174e9b1d0960e3166b9ab2]['download'] = $download;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- statusReplies --*/
function statusReplies($replies=array(), $no_wrapper=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['statusReplies'] ) )
{
$count_d812919fa31a1126b0e0e50c9ff4990b = is_array($this->functionData['statusReplies']) ? count($this->functionData['statusReplies']) : 0;
$this->functionData['statusReplies'][$count_d812919fa31a1126b0e0e50c9ff4990b]['replies'] = $replies;
$this->functionData['statusReplies'][$count_d812919fa31a1126b0e0e50c9ff4990b]['no_wrapper'] = $no_wrapper;
}
$IPBHTML .= "<commentReplies>
	".$this->__f__43493421384627f3074c63e009d8796c($replies,$no_wrapper)."</commentReplies>";
return $IPBHTML;
}


function __f__43493421384627f3074c63e009d8796c($replies=array(), $no_wrapper=false)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $replies as $reply )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<commentReply>
			<author><![CDATA[{$reply['members_display_name']}]]></author>
			<avatar><![CDATA[{$reply['pp_main_photo']}]]></avatar>	
			<reply><![CDATA[{$reply['reply_content']}]]></reply>
			<date>{$reply['reply_date_formatted']}</date>
			<canDelete>" . (($reply['_canDelete']) ? ("1") : ("0")) . "</canDelete>
			<deleteURL><![CDATA[{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteReply&amp;status_id={$reply['reply_status_id']}&amp;reply_id={$reply['reply_id']}&amp;k={$this->member->form_hash}]]></deleteURL>
		</commentReply>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusUpdates --*/
function statusUpdates($updates=array(), $smallSpace=0, $latestOnly=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['statusUpdates'] ) )
{
$count_c0ec5166c2b7437fe8d4855b68fcae6b = is_array($this->functionData['statusUpdates']) ? count($this->functionData['statusUpdates']) : 0;
$this->functionData['statusUpdates'][$count_c0ec5166c2b7437fe8d4855b68fcae6b]['updates'] = $updates;
$this->functionData['statusUpdates'][$count_c0ec5166c2b7437fe8d4855b68fcae6b]['smallSpace'] = $smallSpace;
$this->functionData['statusUpdates'][$count_c0ec5166c2b7437fe8d4855b68fcae6b]['latestOnly'] = $latestOnly;
}
$IPBHTML .= "<profileComments>".$this->__f__ef573bc023989bb5fa3b64d639cfa290($updates,$smallSpace,$latestOnly)."</profileComments>";
return $IPBHTML;
}


function __f__ef573bc023989bb5fa3b64d639cfa290($updates=array(), $smallSpace=0, $latestOnly=0)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $updates as $id => $status )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<profileComment>
			<author><![CDATA[{$status['members_display_name']}]]></author>
			<avatar><![CDATA[{$status['pp_main_photo']}]]></avatar>	
			<reply><![CDATA[{$status['status_content']}]]></reply>
			<date>{$status['status_date_formatted']}</date>
			<canDelete>" . (($status['_canDelete']) ? ("1") : ("0")) . "</canDelete>
			<deleteURL><![CDATA[{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=deleteReply&amp;status_id={$status['status_status_id']}&amp;reply_id={$status['status_id']}&amp;k={$this->member->form_hash}]]></deleteURL>
			" . (($status['status_replies'] AND count( $status['replies'] )) ? ("
				" . ( method_exists( $this->registry->getClass('output')->getTemplate('profile'), 'statusReplies' ) ? $this->registry->getClass('output')->getTemplate('profile')->statusReplies($status['replies'], 1) : '' ) . "
			") : ("")) . "
			" . (($status['_userCanReply']) ? ("
					<replyURL><![CDATA[{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=reply&amp;status_id={$status['status_id']}&amp;k={$this->member->form_hash}&amp;id={$this->memberData['member_id']}]]></replyURL>
			") : ("")) . "
		</profileComment>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusUpdatesPage --*/
function statusUpdatesPage($updates=array(), $pages='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['statusUpdatesPage'] ) )
{
$count_26424d2125e2f1d38d5753e81212e678 = is_array($this->functionData['statusUpdatesPage']) ? count($this->functionData['statusUpdatesPage']) : 0;
$this->functionData['statusUpdatesPage'][$count_26424d2125e2f1d38d5753e81212e678]['updates'] = $updates;
$this->functionData['statusUpdatesPage'][$count_26424d2125e2f1d38d5753e81212e678]['pages'] = $pages;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- tabFriends --*/
function tabFriends($friends=array(), $member=array(), $pagination='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabFriends'] ) )
{
$count_4dc6f29c2890680ba69c6e1af6cd5ea7 = is_array($this->functionData['tabFriends']) ? count($this->functionData['tabFriends']) : 0;
$this->functionData['tabFriends'][$count_4dc6f29c2890680ba69c6e1af6cd5ea7]['friends'] = $friends;
$this->functionData['tabFriends'][$count_4dc6f29c2890680ba69c6e1af6cd5ea7]['member'] = $member;
$this->functionData['tabFriends'][$count_4dc6f29c2890680ba69c6e1af6cd5ea7]['pagination'] = $pagination;
}
$IPBHTML .= "<pagination>{$pagination}</pagination>
<friends>
	".$this->__f__c9e5a39aa99ac89833b86f9f7dc6f708($friends,$member,$pagination)."</friends>";
return $IPBHTML;
}


function __f__c9e5a39aa99ac89833b86f9f7dc6f708($friends=array(), $member=array(), $pagination='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $friends as $friend )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<friend>
			<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", "public",'' ), "{$friend['members_seo_name']}", "showuser" ) . "]]></url>
			<avatar><![CDATA[{$friend['pp_small_photo']}]]></avatar>
			<name><![CDATA[{$friend['members_display_name']}]]></name>
			<memberTitle><![CDATA[{$friend['member_title']}]]></memberTitle>
		</friend>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- tabNoContent --*/
function tabNoContent($langkey) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- tabPosts --*/
function tabPosts($content) {
$IPBHTML = "";
$IPBHTML .= "<posts>
	{$content}
</posts>";
return $IPBHTML;
}

/* -- tabReputation --*/
function tabReputation($member, $currentApp='', $type='', $supportedApps=array(), $processedResults='', $pagination='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabReputation'] ) )
{
$count_9bc69c46e172e6106dba95baab8acf8f = is_array($this->functionData['tabReputation']) ? count($this->functionData['tabReputation']) : 0;
$this->functionData['tabReputation'][$count_9bc69c46e172e6106dba95baab8acf8f]['member'] = $member;
$this->functionData['tabReputation'][$count_9bc69c46e172e6106dba95baab8acf8f]['currentApp'] = $currentApp;
$this->functionData['tabReputation'][$count_9bc69c46e172e6106dba95baab8acf8f]['type'] = $type;
$this->functionData['tabReputation'][$count_9bc69c46e172e6106dba95baab8acf8f]['supportedApps'] = $supportedApps;
$this->functionData['tabReputation'][$count_9bc69c46e172e6106dba95baab8acf8f]['processedResults'] = $processedResults;
$this->functionData['tabReputation'][$count_9bc69c46e172e6106dba95baab8acf8f]['pagination'] = $pagination;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- tabReputation_calendar --*/
function tabReputation_calendar($results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabReputation_calendar'] ) )
{
$count_98154e8d694df41fb5ac739265f4c28f = is_array($this->functionData['tabReputation_calendar']) ? count($this->functionData['tabReputation_calendar']) : 0;
$this->functionData['tabReputation_calendar'][$count_98154e8d694df41fb5ac739265f4c28f]['results'] = $results;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- tabReputation_posts --*/
function tabReputation_posts($results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabReputation_posts'] ) )
{
$count_4c2e6f8b4fd2ee4fbef98e260e8ab75b = is_array($this->functionData['tabReputation_posts']) ? count($this->functionData['tabReputation_posts']) : 0;
$this->functionData['tabReputation_posts'][$count_4c2e6f8b4fd2ee4fbef98e260e8ab75b]['results'] = $results;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- tabSingleColumn --*/
function tabSingleColumn($row=array(), $read_more_link='', $url='', $title='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabSingleColumn'] ) )
{
$count_3c0e0288e508380613065a4dd52a929e = is_array($this->functionData['tabSingleColumn']) ? count($this->functionData['tabSingleColumn']) : 0;
$this->functionData['tabSingleColumn'][$count_3c0e0288e508380613065a4dd52a929e]['row'] = $row;
$this->functionData['tabSingleColumn'][$count_3c0e0288e508380613065a4dd52a929e]['read_more_link'] = $read_more_link;
$this->functionData['tabSingleColumn'][$count_3c0e0288e508380613065a4dd52a929e]['url'] = $url;
$this->functionData['tabSingleColumn'][$count_3c0e0288e508380613065a4dd52a929e]['title'] = $title;
}
$IPBHTML .= "<post>
<title><![CDATA[" . IPSText::truncate( $title, 90 ) . "]]></title>
<url><![CDATA[{$url}]]></url>
<text><![CDATA[{$row['post']}]]></text>
<date>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($row['_raw_date'],"long", 0)) . "</date>
</post>";
return $IPBHTML;
}

/* -- tabStatusUpdates --*/
function tabStatusUpdates($updates=array(), $actions, $member=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_profile', $this->_funcHooks['tabStatusUpdates'] ) )
{
$count_a078f4d7b37ce150196803a3205e9695 = is_array($this->functionData['tabStatusUpdates']) ? count($this->functionData['tabStatusUpdates']) : 0;
$this->functionData['tabStatusUpdates'][$count_a078f4d7b37ce150196803a3205e9695]['updates'] = $updates;
$this->functionData['tabStatusUpdates'][$count_a078f4d7b37ce150196803a3205e9695]['actions'] = $actions;
$this->functionData['tabStatusUpdates'][$count_a078f4d7b37ce150196803a3205e9695]['member'] = $member;
}
$IPBHTML .= "" . (($this->memberData['member_id'] AND ( $this->memberData['member_id'] == $member['member_id'] ) AND $this->registry->getClass('memberStatus')->canCreate( $member )) ? ("
<newStatusURL><![CDATA[{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=new&amp;k={$this->member->form_hash}&amp;id={$this->memberData['member_id']}&amp;forMemberId={$member['member_id']}]]>
</newStatusURL>
") : ("")) . "
" . (($this->memberData['member_id'] && $this->memberData['member_id'] != $member['member_id'] && $member['pp_setting_count_comments']) ? ("
<profileCommentURL>
<![CDATA[{$this->settings['base_url']}app=members&amp;module=profile&amp;section=status&amp;do=new&amp;k={$this->member->form_hash}&amp;id={$this->memberData['member_id']}&amp;forMemberId={$member['member_id']}]]>
</profileCommentURL>
") : ("")) . "

" . ((count( $updates )) ? ("
	" . ( method_exists( $this->registry->getClass('output')->getTemplate('profile'), 'statusUpdates' ) ? $this->registry->getClass('output')->getTemplate('profile')->statusUpdates($updates) : '' ) . "
") : ("
<commentReplies>
	<commentReply>
		<reply><![CDATA[{$this->lang->words['status_updates_none']}]]></reply>
	</commentReply>
</commentReplies>
")) . "";
return $IPBHTML;
}

/* -- tabTopics --*/
function tabTopics($content) {
$IPBHTML = "";
$IPBHTML .= "<posts>
		{$content}
<posts>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>